import type { FastifyInstance } from "fastify";
import { buildAdvanceDmPayloads, calculateRecPotw, clearPendingEosBatch, generateWeeklyChallenges, getActiveGameChannels, getChallengeAudit, getGameChannelPlans, getReminderState, markGameChannelDeleted, recordGameChannel, recordGameChannelCheckin, recordReminder, runPostAdvanceAutomation, setEconomyConfig, setLeagueWeek, setNextAdvance, viewEconomyConfig, viewLeagueWeek, getGotwCandidates, selectGotwCandidate, recordGotwPollMessage, recordGotwVote, getGotwVotes, applyAdvanceRecords, createActiveCheck, recordActiveCheckMessage, recordActiveCheckResponse, getActiveCheckStatus, closeActiveCheck, getOpenActiveChecks, recordStreamPost, settleGotwVotes, reviewStreamPayout, evaluateWeeklyChallenges, evaluateStreamCompliance, issueRecPotwPayouts, issueWeeklyGamePayouts, processAdvanceResults, processPotwAward, finalizeAdvanceStep, processPlayoffGotw, previewEosPayouts, calculateAndStorePowerRankings, getLatestPowerRankings } from "./advance.service.js";

export async function advanceRoutes(app: FastifyInstance) {
  app.post("/v1/advance/post-advance", async (request) => runPostAdvanceAutomation(request.body as any));
  app.post("/v1/advance/process-results", async (request) => processAdvanceResults((request.body as any).guildId));
  app.post("/v1/advance/process-potw", async (request) => processPotwAward((request.body as any).guildId));
  app.post("/v1/advance/finalize", async (request) => finalizeAdvanceStep((request.body as any).guildId));
  app.post("/v1/advance/playoff-gotw", async (request) => processPlayoffGotw((request.body as any).guildId));
  app.post("/v1/advance/preview-eos", async (request) => previewEosPayouts((request.body as any).guildId));
  app.post("/v1/advance/power-rankings/calculate", async (request) => calculateAndStorePowerRankings((request.body as any).guildId));
  app.post("/v1/advance/power-rankings/latest", async (request) => getLatestPowerRankings((request.body as any).guildId));
  app.post("/v1/advance/apply-records", async (request) => applyAdvanceRecords((request.body as any).guildId));
  app.post("/v1/advance/issue-game-payouts", async (request) => issueWeeklyGamePayouts((request.body as any).guildId));
  app.post("/v1/advance/dm-payloads", async (request) => buildAdvanceDmPayloads((request.body as any).guildId));
  app.post("/v1/league-week/view", async (request) => viewLeagueWeek((request.body as any).guildId));
  app.post("/v1/league-week/set", async (request) => setLeagueWeek(request.body as any));
  app.post("/v1/advance/set-next-advance", async (request) => setNextAdvance(request.body as any));
  app.post("/v1/economy/config/view", async (request) => viewEconomyConfig((request.body as any).guildId));
  app.post("/v1/economy/config/set", async (request) => setEconomyConfig(request.body as any));
  app.post("/v1/eos/clear-pending", async (request) => clearPendingEosBatch(request.body as any));
  app.post("/v1/challenges/generate", async (request) => generateWeeklyChallenges(request.body as any));
  app.post("/v1/challenges/regenerate", async (request) => generateWeeklyChallenges({ ...(request.body as any), regenerate: true }));
  app.post("/v1/challenges/audit", async (request) => getChallengeAudit((request.body as any).guildId));
  app.post("/v1/challenges/evaluate", async (request) => evaluateWeeklyChallenges((request.body as any).guildId));
  app.post("/v1/streams/evaluate-compliance", async (request) => evaluateStreamCompliance((request.body as any).guildId));
  app.post("/v1/awards/potw/calculate", async (request) => calculateRecPotw((request.body as any).guildId));
  app.post("/v1/awards/potw/issue", async (request) => issueRecPotwPayouts((request.body as any).guildId));
  app.post("/v1/game-channels/plans", async (request) => getGameChannelPlans((request.body as any).guildId));
  app.post("/v1/game-channels/active", async (request) => getActiveGameChannels((request.body as any).guildId));
  app.post("/v1/game-channels/record", async (request) => recordGameChannel(request.body as any));
  app.post("/v1/game-channels/deleted", async (request) => markGameChannelDeleted(request.body as any));
  app.post("/v1/game-channels/checkin", async (request) => recordGameChannelCheckin(request.body as any));
  app.post("/v1/game-channels/reminder-state", async (request) => getReminderState((request.body as any).guildId));
  app.post("/v1/game-channels/reminder", async (request) => recordReminder(request.body as any));
  app.post("/v1/gotw/candidates", async (request) => getGotwCandidates((request.body as any).guildId));
  app.post("/v1/gotw/select", async (request) => selectGotwCandidate(request.body as any));
  app.post("/v1/gotw/poll-message", async (request) => recordGotwPollMessage(request.body as any));
  app.post("/v1/gotw/vote", async (request) => recordGotwVote(request.body as any));
  app.post("/v1/gotw/votes", async (request) => getGotwVotes((request.body as any).pollId));
  app.post("/v1/gotw/settle", async (request) => settleGotwVotes((request.body as any).guildId));
  app.post("/v1/active-check/create", async (request) => createActiveCheck(request.body as any));
  app.post("/v1/active-check/message", async (request) => recordActiveCheckMessage(request.body as any));
  app.post("/v1/active-check/respond", async (request) => recordActiveCheckResponse(request.body as any));
  app.post("/v1/active-check/status", async (request) => getActiveCheckStatus((request.body as any).eventId));
  app.post("/v1/active-check/close", async (request) => closeActiveCheck(request.body as any));
  app.post("/v1/active-check/open", async (request) => getOpenActiveChecks((request.body as any).guildId));
  app.post("/v1/streams/post", async (request) => recordStreamPost(request.body as any));
  app.post("/v1/streams/review", async (request) => reviewStreamPayout(request.body as any));
}
