insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Brett Favre','QB','offense',91,'6''2"',222,'Right',4,'superstar','Strong-arm improviser','Fearless vertical passer with rare arm strength, toughness and off-platform creation.','{"Press":19,"Speed":80,"Injury":96,"Agility":82,"Jumping":79,"Pursuit":38,"Release":24,"Stamina":97,"Carrying":86,"Catching":49,"Strength":76,"Tackling":32,"Trucking":59,"Awareness":94,"BC Vision":84,"Hit Power":28,"Juke Move":69,"Long Snap":44,"Spin Move":64,"Stiff Arm":64,"Toughness":99,"Break Sack":93,"Lead Block":24,"Play Action":93,"Power Moves":19,"Acceleration":82,"Break Tackle":86,"Man Coverage":24,"Run Blocking":29,"Deep Accuracy":94,"Finesse Moves":19,"Kicking Power":24,"Pass Blocking":34,"Zone Coverage":29,"Block Shedding":24,"Short Accuracy":92,"Throwing Power":99,"Impact Blocking":22,"Medium Accuracy":94,"Run Block Power":28,"Catch in Traffic":44,"Kick/Punt Return":17,"Kicking Accuracy":19,"Pass Block Power":32,"Play Recognition":32,"Throw on the Run":94,"Run Block Finesse":26,"Spectacular Catch":39,"Deep Route Running":19,"Pass Block Finesse":29,"Change of Direction":82,"Short Route Running":29,"Medium Route Running":24,"Throw Under Pressure":96}'::jsonb,'[{"name":"Gunslinger","description":"Faster throwing animations and elite velocity.","type":"superstar"},{"name":"Fearless","description":"Maintains accuracy against pressure.","type":"superstar"},{"name":"Long Range Deadeye","description":"Excels attacking deep zones.","type":"superstar"}]'::jsonb,'legend','Southern Miss','standard',null,'madden','notable_addition'),
  ('Drew Brees','QB','offense',87,'6''0"',209,'Right',9,'superstar','Precision field general','Anticipation-driven distributor with historic accuracy, pocket movement and pre-snap command.','{"Press":19,"Speed":60,"Injury":95,"Agility":62,"Jumping":79,"Pursuit":38,"Release":24,"Stamina":96,"Carrying":74,"Catching":49,"Strength":72,"Tackling":32,"Trucking":59,"Awareness":99,"BC Vision":72,"Hit Power":28,"Juke Move":69,"Long Snap":44,"Spin Move":64,"Stiff Arm":64,"Toughness":98,"Break Sack":64,"Lead Block":24,"Play Action":96,"Power Moves":19,"Acceleration":62,"Break Tackle":64,"Man Coverage":24,"Run Blocking":29,"Deep Accuracy":95,"Finesse Moves":19,"Kicking Power":24,"Pass Blocking":34,"Zone Coverage":29,"Block Shedding":24,"Short Accuracy":99,"Throwing Power":90,"Impact Blocking":22,"Medium Accuracy":99,"Run Block Power":28,"Catch in Traffic":44,"Kick/Punt Return":17,"Kicking Accuracy":19,"Pass Block Power":32,"Play Recognition":32,"Throw on the Run":76,"Run Block Finesse":26,"Spectacular Catch":39,"Deep Route Running":19,"Pass Block Finesse":29,"Change of Direction":62,"Short Route Running":29,"Medium Route Running":24,"Throw Under Pressure":97}'::jsonb,'[{"name":"Hot Route Master","description":"Expanded route adjustments before the snap.","type":"superstar"},{"name":"Pass Lead Elite","description":"Elite placement away from coverage.","type":"superstar"},{"name":"Pocket Deadeye","description":"Pinpoint accuracy from a clean pocket.","type":"superstar"}]'::jsonb,'legend','Purdue','standard',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
