insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Terry Bradshaw','QB','offense',89,'6''3"',215,'Right',12,'superstar','Vertical field general','Big-game downfield passer with a powerful arm, physical toughness and aggressive mentality.','{"Press":19,"Speed":80,"Injury":96,"Agility":82,"Jumping":79,"Pursuit":38,"Release":24,"Stamina":97,"Carrying":86,"Catching":49,"Strength":76,"Tackling":32,"Trucking":59,"Awareness":94,"BC Vision":84,"Hit Power":28,"Juke Move":69,"Long Snap":44,"Spin Move":64,"Stiff Arm":64,"Toughness":98,"Break Sack":93,"Lead Block":24,"Play Action":93,"Power Moves":19,"Acceleration":82,"Break Tackle":86,"Man Coverage":24,"Run Blocking":29,"Deep Accuracy":96,"Finesse Moves":19,"Kicking Power":24,"Pass Blocking":34,"Zone Coverage":29,"Block Shedding":24,"Short Accuracy":91,"Throwing Power":97,"Impact Blocking":22,"Medium Accuracy":92,"Run Block Power":28,"Catch in Traffic":44,"Kick/Punt Return":17,"Kicking Accuracy":19,"Pass Block Power":32,"Play Recognition":32,"Throw on the Run":94,"Run Block Finesse":26,"Spectacular Catch":39,"Deep Route Running":19,"Pass Block Finesse":29,"Change of Direction":82,"Short Route Running":29,"Medium Route Running":24,"Throw Under Pressure":96}'::jsonb,'[{"name":"Set Feet Lead","description":"Extra velocity on set-foot throws.","type":"superstar"},{"name":"Fearless","description":"Stands tall against interior pressure.","type":"superstar"},{"name":"Deep Range Deadeye","description":"Accurate on vertical throws.","type":"superstar"}]'::jsonb,'legend','Louisiana Tech','standard',null,'madden','notable_addition'),
  ('Jim Kelly','QB','offense',92,'6''3"',226,'Right',12,'superstar','No-huddle field general','Tough, decisive passer built around tempo, intermediate timing and aggressive downfield reads.','{"Press":19,"Speed":80,"Injury":96,"Agility":82,"Jumping":79,"Pursuit":38,"Release":24,"Stamina":97,"Carrying":86,"Catching":49,"Strength":76,"Tackling":32,"Trucking":59,"Awareness":96,"BC Vision":84,"Hit Power":28,"Juke Move":69,"Long Snap":44,"Spin Move":64,"Stiff Arm":64,"Toughness":98,"Break Sack":88,"Lead Block":24,"Play Action":93,"Power Moves":19,"Acceleration":82,"Break Tackle":86,"Man Coverage":24,"Run Blocking":29,"Deep Accuracy":94,"Finesse Moves":19,"Kicking Power":24,"Pass Blocking":34,"Zone Coverage":29,"Block Shedding":24,"Short Accuracy":95,"Throwing Power":96,"Impact Blocking":22,"Medium Accuracy":96,"Run Block Power":28,"Catch in Traffic":44,"Kick/Punt Return":17,"Kicking Accuracy":19,"Pass Block Power":32,"Play Recognition":32,"Throw on the Run":95,"Run Block Finesse":26,"Spectacular Catch":39,"Deep Route Running":19,"Pass Block Finesse":29,"Change of Direction":82,"Short Route Running":29,"Medium Route Running":24,"Throw Under Pressure":96}'::jsonb,'[{"name":"Hot Route Master","description":"Controls the offense before the snap.","type":"superstar"},{"name":"Gunslinger","description":"Quick release with high-end velocity.","type":"superstar"},{"name":"Fearless","description":"Resists pressure penalties.","type":"superstar"}]'::jsonb,'legend','Miami','standard',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
