insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Dan Fouts','QB','offense',87,'6''3"',204,'Right',14,'superstar','Vertical pocket passer','Air Coryell distributor with elite downfield anticipation, volume and pocket command.','{"Press":19,"Speed":59,"Injury":98,"Agility":62,"Jumping":79,"Pursuit":38,"Release":24,"Stamina":94,"Carrying":74,"Catching":49,"Strength":72,"Tackling":32,"Trucking":59,"Awareness":97,"BC Vision":72,"Hit Power":28,"Juke Move":69,"Long Snap":44,"Spin Move":64,"Stiff Arm":64,"Toughness":98,"Break Sack":70,"Lead Block":24,"Play Action":96,"Power Moves":19,"Acceleration":61,"Break Tackle":68,"Man Coverage":24,"Run Blocking":29,"Deep Accuracy":96,"Finesse Moves":19,"Kicking Power":24,"Pass Blocking":34,"Zone Coverage":29,"Block Shedding":24,"Short Accuracy":94,"Throwing Power":95,"Impact Blocking":22,"Medium Accuracy":97,"Run Block Power":28,"Catch in Traffic":44,"Kick/Punt Return":17,"Kicking Accuracy":19,"Pass Block Power":32,"Play Recognition":32,"Throw on the Run":80,"Run Block Finesse":26,"Spectacular Catch":39,"Deep Route Running":19,"Pass Block Finesse":29,"Change of Direction":62,"Short Route Running":29,"Medium Route Running":24,"Throw Under Pressure":95}'::jsonb,'[{"name":"Set Feet Lead","description":"Drives deep throws from the pocket.","type":"superstar"},{"name":"Long Range Deadeye","description":"Accurate on deep passes.","type":"superstar"},{"name":"Pocket Deadeye","description":"Elite clean-pocket placement.","type":"superstar"}]'::jsonb,'legend','Oregon','standard',null,'madden','notable_addition'),
  ('Franco Harris','HB','offense',91,'6''2"',230,'Right',32,'superstar','Power back','Patient, durable downhill runner with balance, receiving value and postseason reliability.','{"Press":19,"Speed":95,"Injury":99,"Agility":90,"Jumping":79,"Pursuit":49,"Release":66,"Stamina":99,"Carrying":96,"Catching":82,"Strength":99,"Tackling":44,"Trucking":93,"Awareness":96,"BC Vision":96,"Hit Power":42,"Juke Move":86,"Long Snap":44,"Spin Move":82,"Stiff Arm":94,"Toughness":99,"Break Sack":84,"Lead Block":49,"Play Action":34,"Power Moves":29,"Acceleration":94,"Break Tackle":95,"Man Coverage":24,"Run Blocking":39,"Deep Accuracy":19,"Finesse Moves":29,"Kicking Power":24,"Pass Blocking":76,"Zone Coverage":29,"Block Shedding":34,"Short Accuracy":29,"Throwing Power":44,"Impact Blocking":44,"Medium Accuracy":24,"Run Block Power":34,"Catch in Traffic":69,"Kick/Punt Return":29,"Kicking Accuracy":19,"Pass Block Power":70,"Play Recognition":34,"Throw on the Run":24,"Run Block Finesse":32,"Spectacular Catch":62,"Deep Route Running":54,"Pass Block Finesse":66,"Change of Direction":90,"Short Route Running":72,"Medium Route Running":64,"Throw Under Pressure":24}'::jsonb,'[{"name":"Bruiser","description":"Improved trucking and stiff arms.","type":"superstar"},{"name":"Balance Beam","description":"Resists stumbling through contact.","type":"superstar"},{"name":"Reach For It","description":"Fights for extra yardage.","type":"superstar"}]'::jsonb,'legend','Penn State','standard',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
