insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('John Riggins','HB','offense',89,'6''2"',235,'Right',44,'superstar','Power back','Large, relentless workhorse who wore defenses down and finished runs through contact.','{"Press":29,"Speed":94,"Injury":94,"Agility":86,"Jumping":79,"Pursuit":49,"Release":76,"Stamina":99,"Carrying":97,"Catching":80,"Strength":94,"Tackling":39,"Trucking":98,"Awareness":94,"BC Vision":95,"Hit Power":54,"Juke Move":82,"Long Snap":44,"Spin Move":78,"Stiff Arm":97,"Toughness":99,"Break Sack":54,"Lead Block":39,"Play Action":24,"Power Moves":34,"Acceleration":95,"Break Tackle":97,"Man Coverage":29,"Run Blocking":39,"Deep Accuracy":17,"Finesse Moves":34,"Kicking Power":24,"Pass Blocking":34,"Zone Coverage":29,"Block Shedding":44,"Short Accuracy":24,"Throwing Power":44,"Impact Blocking":59,"Medium Accuracy":19,"Run Block Power":39,"Catch in Traffic":76,"Kick/Punt Return":74,"Kicking Accuracy":19,"Pass Block Power":34,"Play Recognition":54,"Throw on the Run":17,"Run Block Finesse":39,"Spectacular Catch":78,"Deep Route Running":44,"Pass Block Finesse":34,"Change of Direction":86,"Short Route Running":76,"Medium Route Running":72,"Throw Under Pressure":17}'::jsonb,'[{"name":"Freight Train","description":"Builds momentum through repeated successful runs.","type":"superstar"},{"name":"Bruiser","description":"Dominant trucking and stiff-arm moves.","type":"superstar"},{"name":"Goal Line Back","description":"Excels in short-yardage situations.","type":"superstar"}]'::jsonb,'legend','Kansas','standard',null,'madden','notable_addition'),
  ('Terrell Davis','HB','offense',91,'5''11"',210,'Right',30,'superstar','One-cut zone runner','Decisive one-cut runner with elite vision, burst, balance and postseason production.','{"Press":19,"Speed":94,"Injury":98,"Agility":91,"Jumping":79,"Pursuit":49,"Release":66,"Stamina":99,"Carrying":97,"Catching":74,"Strength":94,"Tackling":44,"Trucking":96,"Awareness":94,"BC Vision":99,"Hit Power":42,"Juke Move":88,"Long Snap":44,"Spin Move":86,"Stiff Arm":94,"Toughness":98,"Break Sack":84,"Lead Block":49,"Play Action":34,"Power Moves":29,"Acceleration":96,"Break Tackle":94,"Man Coverage":24,"Run Blocking":39,"Deep Accuracy":19,"Finesse Moves":29,"Kicking Power":24,"Pass Blocking":74,"Zone Coverage":29,"Block Shedding":34,"Short Accuracy":29,"Throwing Power":44,"Impact Blocking":44,"Medium Accuracy":24,"Run Block Power":34,"Catch in Traffic":69,"Kick/Punt Return":29,"Kicking Accuracy":19,"Pass Block Power":70,"Play Recognition":34,"Throw on the Run":24,"Run Block Finesse":32,"Spectacular Catch":62,"Deep Route Running":54,"Pass Block Finesse":66,"Change of Direction":95,"Short Route Running":72,"Medium Route Running":64,"Throw Under Pressure":24}'::jsonb,'[{"name":"One Cut","description":"Explosive cuts on zone runs.","type":"superstar"},{"name":"Evasive","description":"Sharper jukes and spins.","type":"superstar"},{"name":"Clutch","description":"Raises performance in high-leverage moments.","type":"superstar"}]'::jsonb,'legend','Georgia','standard',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
