insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Jerome Bettis','HB','offense',89,'5''11"',252,'Right',36,'superstar','Power back','Massive, nimble interior runner who combined elite contact balance with surprising feet.','{"Press":29,"Speed":94,"Injury":94,"Agility":86,"Jumping":79,"Pursuit":49,"Release":76,"Stamina":99,"Carrying":96,"Catching":80,"Strength":97,"Tackling":39,"Trucking":99,"Awareness":94,"BC Vision":96,"Hit Power":54,"Juke Move":82,"Long Snap":44,"Spin Move":78,"Stiff Arm":97,"Toughness":99,"Break Sack":54,"Lead Block":39,"Play Action":24,"Power Moves":34,"Acceleration":95,"Break Tackle":98,"Man Coverage":29,"Run Blocking":39,"Deep Accuracy":17,"Finesse Moves":34,"Kicking Power":24,"Pass Blocking":34,"Zone Coverage":29,"Block Shedding":44,"Short Accuracy":24,"Throwing Power":44,"Impact Blocking":59,"Medium Accuracy":19,"Run Block Power":39,"Catch in Traffic":76,"Kick/Punt Return":74,"Kicking Accuracy":19,"Pass Block Power":34,"Play Recognition":54,"Throw on the Run":17,"Run Block Finesse":39,"Spectacular Catch":78,"Deep Route Running":44,"Pass Block Finesse":34,"Change of Direction":86,"Short Route Running":76,"Medium Route Running":72,"Throw Under Pressure":17}'::jsonb,'[{"name":"Freight Train","description":"Gains momentum through contact.","type":"superstar"},{"name":"Tank","description":"Breaks hit-stick tackle attempts.","type":"superstar"},{"name":"Goal Line Back","description":"Dominant near the goal line.","type":"superstar"}]'::jsonb,'legend','Notre Dame','standard',null,'madden','notable_addition'),
  ('Edgerrin James','HB','offense',94,'6''0"',219,'Right',32,'superstar','Complete back','Vision-driven workhorse with patience, lateral agility, receiving skill and pass protection.','{"Press":18,"Speed":95,"Injury":96,"Agility":97,"Jumping":78,"Pursuit":48,"Release":91,"Stamina":97,"Carrying":97,"Catching":88,"Strength":83,"Tackling":43,"Trucking":79,"Awareness":97,"BC Vision":98,"Hit Power":41,"Juke Move":94,"Long Snap":43,"Spin Move":92,"Stiff Arm":83,"Toughness":96,"Break Sack":83,"Lead Block":48,"Play Action":33,"Power Moves":28,"Acceleration":97,"Break Tackle":95,"Man Coverage":23,"Run Blocking":38,"Deep Accuracy":18,"Finesse Moves":28,"Kicking Power":23,"Pass Blocking":78,"Zone Coverage":28,"Block Shedding":33,"Short Accuracy":28,"Throwing Power":43,"Impact Blocking":43,"Medium Accuracy":23,"Run Block Power":33,"Catch in Traffic":89,"Kick/Punt Return":28,"Kicking Accuracy":18,"Pass Block Power":69,"Play Recognition":33,"Throw on the Run":23,"Run Block Finesse":31,"Spectacular Catch":61,"Deep Route Running":75,"Pass Block Finesse":65,"Change of Direction":96,"Short Route Running":94,"Medium Route Running":89,"Throw Under Pressure":23}'::jsonb,'[{"name":"Backfield Master","description":"Expanded receiving routes and improved catches.","type":"superstar"},{"name":"Evasive","description":"Elite open-field moves.","type":"superstar"},{"name":"First One Free","description":"Improved chance to beat the first defender.","type":"superstar"}]'::jsonb,'legend','Miami','standard',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
