insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Marion Motley','FB','offense',92,'6''1"',232,'Right',76,'superstar','Two-way power fullback','Foundational power runner and blocker with rare size, speed and defensive toughness.','{"Press":19,"Speed":91,"Injury":98,"Agility":80,"Jumping":79,"Pursuit":56,"Release":69,"Stamina":99,"Carrying":99,"Catching":72,"Strength":98,"Tackling":54,"Trucking":98,"Awareness":94,"BC Vision":94,"Hit Power":59,"Juke Move":72,"Long Snap":44,"Spin Move":69,"Stiff Arm":95,"Toughness":99,"Break Sack":84,"Lead Block":94,"Play Action":34,"Power Moves":39,"Acceleration":88,"Break Tackle":97,"Man Coverage":24,"Run Blocking":88,"Deep Accuracy":19,"Finesse Moves":29,"Kicking Power":24,"Pass Blocking":78,"Zone Coverage":29,"Block Shedding":44,"Short Accuracy":29,"Throwing Power":49,"Impact Blocking":95,"Medium Accuracy":24,"Run Block Power":90,"Catch in Traffic":72,"Kick/Punt Return":17,"Kicking Accuracy":19,"Pass Block Power":88,"Play Recognition":39,"Throw on the Run":24,"Run Block Finesse":92,"Spectacular Catch":64,"Deep Route Running":54,"Pass Block Finesse":84,"Change of Direction":79,"Short Route Running":69,"Medium Route Running":62,"Throw Under Pressure":24}'::jsonb,'[{"name":"Bruiser","description":"Powerful trucks and stiff arms.","type":"superstar"},{"name":"Honorary Lineman","description":"High-impact lead blocking.","type":"superstar"},{"name":"Tank","description":"Resists hit-stick tackles.","type":"superstar"}]'::jsonb,'legend','Nevada','muscular',null,'madden','notable_addition'),
  ('Marvin Harrison','WR','offense',94,'6''0"',185,'Right',88,'superstar','Route technician','Exceptionally precise separator with elite hands, boundary awareness and sustained production.','{"Press":17,"Speed":92,"Injury":97,"Agility":95,"Jumping":94,"Pursuit":44,"Release":97,"Stamina":99,"Carrying":88,"Catching":98,"Strength":78,"Tackling":42,"Trucking":72,"Awareness":98,"BC Vision":90,"Hit Power":42,"Juke Move":87,"Long Snap":42,"Spin Move":84,"Stiff Arm":80,"Toughness":99,"Break Sack":76,"Lead Block":44,"Play Action":32,"Power Moves":22,"Acceleration":94,"Break Tackle":86,"Man Coverage":22,"Run Blocking":84,"Deep Accuracy":17,"Finesse Moves":22,"Kicking Power":22,"Pass Blocking":38,"Zone Coverage":27,"Block Shedding":30,"Short Accuracy":27,"Throwing Power":47,"Impact Blocking":68,"Medium Accuracy":22,"Run Block Power":76,"Catch in Traffic":96,"Kick/Punt Return":32,"Kicking Accuracy":17,"Pass Block Power":34,"Play Recognition":34,"Throw on the Run":22,"Run Block Finesse":74,"Spectacular Catch":94,"Deep Route Running":98,"Pass Block Finesse":32,"Change of Direction":92,"Short Route Running":98,"Medium Route Running":99,"Throw Under Pressure":22}'::jsonb,'[{"name":"Route Technician","description":"Wins more consistently on route breaks.","type":"superstar"},{"name":"Outside Apprentice","description":"Expanded outside receiver route tree.","type":"superstar"},{"name":"Deep Out Elite","description":"Excels on deep outside catches.","type":"superstar"}]'::jsonb,'legend','Syracuse','lean',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
