insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Isaac Bruce','WR','offense',93,'6''0"',188,'Right',80,'superstar','Polished deep receiver','Smooth route runner with deceptive acceleration, sideline control and vertical tracking.','{"Press":17,"Speed":94,"Injury":97,"Agility":95,"Jumping":90,"Pursuit":44,"Release":95,"Stamina":98,"Carrying":88,"Catching":96,"Strength":74,"Tackling":42,"Trucking":72,"Awareness":96,"BC Vision":84,"Hit Power":42,"Juke Move":87,"Long Snap":42,"Spin Move":84,"Stiff Arm":80,"Toughness":96,"Break Sack":76,"Lead Block":44,"Play Action":32,"Power Moves":22,"Acceleration":92,"Break Tackle":74,"Man Coverage":22,"Run Blocking":78,"Deep Accuracy":17,"Finesse Moves":22,"Kicking Power":22,"Pass Blocking":38,"Zone Coverage":27,"Block Shedding":30,"Short Accuracy":27,"Throwing Power":47,"Impact Blocking":62,"Medium Accuracy":22,"Run Block Power":76,"Catch in Traffic":97,"Kick/Punt Return":32,"Kicking Accuracy":17,"Pass Block Power":34,"Play Recognition":34,"Throw on the Run":22,"Run Block Finesse":74,"Spectacular Catch":95,"Deep Route Running":97,"Pass Block Finesse":32,"Change of Direction":92,"Short Route Running":99,"Medium Route Running":97,"Throw Under Pressure":22}'::jsonb,'[{"name":"Route Technician","description":"Creates separation on breaks.","type":"superstar"},{"name":"Deep Out Elite","description":"Improved deep outside catching.","type":"superstar"},{"name":"Mid In Elite","description":"Excels between the numbers.","type":"superstar"}]'::jsonb,'legend','Memphis','lean',null,'madden','notable_addition'),
  ('Torry Holt','WR','offense',93,'6''0"',190,'Right',81,'superstar','Vertical route runner','Explosive, technically clean receiver with elite intermediate and deep-route pacing.','{"Press":18,"Speed":96,"Injury":96,"Agility":91,"Jumping":99,"Pursuit":45,"Release":95,"Stamina":99,"Carrying":89,"Catching":96,"Strength":96,"Tackling":43,"Trucking":85,"Awareness":93,"BC Vision":85,"Hit Power":43,"Juke Move":88,"Long Snap":43,"Spin Move":85,"Stiff Arm":91,"Toughness":98,"Break Sack":77,"Lead Block":45,"Play Action":33,"Power Moves":23,"Acceleration":97,"Break Tackle":89,"Man Coverage":23,"Run Blocking":83,"Deep Accuracy":18,"Finesse Moves":23,"Kicking Power":23,"Pass Blocking":39,"Zone Coverage":28,"Block Shedding":31,"Short Accuracy":28,"Throwing Power":48,"Impact Blocking":71,"Medium Accuracy":23,"Run Block Power":77,"Catch in Traffic":99,"Kick/Punt Return":33,"Kicking Accuracy":18,"Pass Block Power":35,"Play Recognition":35,"Throw on the Run":23,"Run Block Finesse":75,"Spectacular Catch":97,"Deep Route Running":98,"Pass Block Finesse":33,"Change of Direction":93,"Short Route Running":94,"Medium Route Running":98,"Throw Under Pressure":23}'::jsonb,'[{"name":"Route Technician","description":"Sharp separation at every level.","type":"superstar"},{"name":"Deep In Elite","description":"Excels on deep routes inside the numbers.","type":"superstar"},{"name":"Slot-O-Matic","description":"Improved slot separation and catching.","type":"superstar"}]'::jsonb,'legend','NC State','thin',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
