insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Kellen Winslow Sr.','TE','offense',92,'6''5"',250,'Right',80,'superstar','Move tight end','Era-defining receiving tight end with wide-receiver movement skills and contested-catch ability.','{"Press":17,"Speed":91,"Injury":94,"Agility":88,"Jumping":98,"Pursuit":44,"Release":94,"Stamina":96,"Carrying":88,"Catching":97,"Strength":86,"Tackling":44,"Trucking":84,"Awareness":96,"BC Vision":82,"Hit Power":46,"Juke Move":80,"Long Snap":42,"Spin Move":78,"Stiff Arm":86,"Toughness":96,"Break Sack":80,"Lead Block":72,"Play Action":37,"Power Moves":22,"Acceleration":88,"Break Tackle":84,"Man Coverage":22,"Run Blocking":74,"Deep Accuracy":17,"Finesse Moves":22,"Kicking Power":22,"Pass Blocking":72,"Zone Coverage":27,"Block Shedding":32,"Short Accuracy":27,"Throwing Power":47,"Impact Blocking":72,"Medium Accuracy":22,"Run Block Power":84,"Catch in Traffic":97,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":80,"Play Recognition":34,"Throw on the Run":22,"Run Block Finesse":82,"Spectacular Catch":95,"Deep Route Running":91,"Pass Block Finesse":76,"Change of Direction":85,"Short Route Running":96,"Medium Route Running":96,"Throw Under Pressure":22}'::jsonb,'[{"name":"Matchup Nightmare","description":"Wins against linebackers and safeties.","type":"superstar"},{"name":"TE Apprentice","description":"Expanded tight-end route tree.","type":"superstar"},{"name":"Deep Out Elite","description":"Threatens defenses vertically outside.","type":"superstar"}]'::jsonb,'legend','Missouri','muscular',null,'madden','notable_addition'),
  ('Willie Roaf','LT','offense',95,'6''5"',320,'Right',77,'superstar','Power tackle','Massive, athletic blind-side protector with elite anchor, balance and run-game power.','{"Press":17,"Speed":70,"Injury":97,"Agility":78,"Jumping":72,"Pursuit":48,"Release":32,"Stamina":99,"Carrying":57,"Catching":50,"Strength":98,"Tackling":50,"Trucking":58,"Awareness":98,"BC Vision":42,"Hit Power":60,"Juke Move":40,"Long Snap":42,"Spin Move":36,"Stiff Arm":54,"Toughness":98,"Break Sack":46,"Lead Block":97,"Play Action":22,"Power Moves":38,"Acceleration":80,"Break Tackle":56,"Man Coverage":22,"Run Blocking":97,"Deep Accuracy":15,"Finesse Moves":26,"Kicking Power":22,"Pass Blocking":97,"Zone Coverage":27,"Block Shedding":48,"Short Accuracy":22,"Throwing Power":37,"Impact Blocking":97,"Medium Accuracy":17,"Run Block Power":98,"Catch in Traffic":46,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":98,"Play Recognition":42,"Throw on the Run":15,"Run Block Finesse":96,"Spectacular Catch":42,"Deep Route Running":15,"Pass Block Finesse":98,"Change of Direction":72,"Short Route Running":22,"Medium Route Running":17,"Throw Under Pressure":15}'::jsonb,'[{"name":"Edge Protector","description":"Improved protection against elite edge rushers.","type":"superstar"},{"name":"Secure Protector","description":"Reduces quick block sheds.","type":"superstar"},{"name":"Nasty Streak","description":"Finishes blocks in space.","type":"superstar"}]'::jsonb,'legend','Louisiana Tech','muscular',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
