insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Art Shell','LT','offense',89,'6''5"',265,'Right',78,'superstar','Power tackle','Long, powerful cornerstone tackle with outstanding leverage and sustained-block strength.','{"Speed":68,"Acceleration":85,"Agility":83,"Strength":97,"Awareness":97,"Carrying":73,"BC Vision":73,"Break Tackle":73,"Trucking":68,"Stiff Arm":68,"Change of Direction":81,"Spin Move":68,"Juke Move":71,"Catching":63,"Catch in Traffic":58,"Spectacular Catch":58,"Short Route Running":53,"Medium Route Running":48,"Deep Route Running":43,"Release":48,"Jumping":83,"Throwing Power":43,"Short Accuracy":33,"Medium Accuracy":28,"Deep Accuracy":23,"Throw on the Run":28,"Throw Under Pressure":28,"Break Sack":43,"Play Action":33,"Pass Blocking":96,"Pass Block Power":97,"Pass Block Finesse":95,"Run Blocking":97,"Run Block Power":97,"Run Block Finesse":39,"Lead Block":38,"Impact Blocking":96,"Play Recognition":73,"Tackling":58,"Hit Power":58,"Block Shedding":53,"Finesse Moves":43,"Power Moves":43,"Pursuit":73,"Man Coverage":43,"Zone Coverage":48,"Press":38,"Kick/Punt Return":23,"Kicking Power":28,"Kicking Accuracy":23,"Stamina":93,"Toughness":93,"Injury":93,"Long Snap":43}'::jsonb,'[{"name":"Edge Protector","description":"Neutralizes edge pressure.","type":"superstar"},{"name":"Post Up","description":"Dominant on double teams.","type":"superstar"},{"name":"Nasty Streak","description":"Punishing blocker in space.","type":"superstar"}]'::jsonb,'legend','Maryland Eastern Shore',null,null,'madden','notable_addition'),
  ('Jackie Slater','RT','offense',94,'6''4"',277,'Right',78,'superstar','Technician tackle','Exceptionally durable technician with balanced pass sets, recovery skill and run blocking.','{"Press":17,"Speed":67,"Injury":96,"Agility":74,"Jumping":72,"Pursuit":48,"Release":32,"Stamina":98,"Carrying":57,"Catching":50,"Strength":96,"Tackling":50,"Trucking":58,"Awareness":99,"BC Vision":42,"Hit Power":60,"Juke Move":40,"Long Snap":42,"Spin Move":36,"Stiff Arm":54,"Toughness":99,"Break Sack":46,"Lead Block":97,"Play Action":22,"Power Moves":38,"Acceleration":78,"Break Tackle":56,"Man Coverage":22,"Run Blocking":95,"Deep Accuracy":15,"Finesse Moves":26,"Kicking Power":22,"Pass Blocking":97,"Zone Coverage":27,"Block Shedding":48,"Short Accuracy":22,"Throwing Power":37,"Impact Blocking":97,"Medium Accuracy":17,"Run Block Power":98,"Catch in Traffic":46,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":98,"Play Recognition":42,"Throw on the Run":15,"Run Block Finesse":96,"Spectacular Catch":42,"Deep Route Running":15,"Pass Block Finesse":97,"Change of Direction":72,"Short Route Running":22,"Medium Route Running":17,"Throw Under Pressure":15}'::jsonb,'[{"name":"Edge Protector","description":"Handles speed and power rushers.","type":"superstar"},{"name":"Secure Protector","description":"Maintains blocks longer.","type":"superstar"},{"name":"All Day","description":"Resists pass-rush fatigue.","type":"superstar"}]'::jsonb,'legend','Jackson State','heavy',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
