insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Bruce Matthews','LG','offense',93,'6''5"',305,'Right',74,'superstar','Complete interior lineman','Elite, durable multi-position blocker combining leverage, intelligence, mobility and power.','{"Press":17,"Speed":66,"Injury":96,"Agility":72,"Jumping":72,"Pursuit":48,"Release":32,"Stamina":98,"Carrying":57,"Catching":50,"Strength":96,"Tackling":50,"Trucking":58,"Awareness":99,"BC Vision":42,"Hit Power":60,"Juke Move":40,"Long Snap":42,"Spin Move":36,"Stiff Arm":54,"Toughness":99,"Break Sack":46,"Lead Block":99,"Play Action":22,"Power Moves":38,"Acceleration":76,"Break Tackle":56,"Man Coverage":22,"Run Blocking":98,"Deep Accuracy":15,"Finesse Moves":26,"Kicking Power":22,"Pass Blocking":98,"Zone Coverage":27,"Block Shedding":48,"Short Accuracy":22,"Throwing Power":37,"Impact Blocking":99,"Medium Accuracy":17,"Run Block Power":99,"Catch in Traffic":46,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":99,"Play Recognition":42,"Throw on the Run":15,"Run Block Finesse":97,"Spectacular Catch":42,"Deep Route Running":15,"Pass Block Finesse":97,"Change of Direction":72,"Short Route Running":22,"Medium Route Running":17,"Throw Under Pressure":15}'::jsonb,'[{"name":"Secure Protector","description":"Sustains interior pass protection.","type":"superstar"},{"name":"Puller Elite","description":"Excels as a pulling blocker.","type":"superstar"},{"name":"Post Up","description":"Dominant on double teams.","type":"superstar"}]'::jsonb,'legend','USC','heavy',null,'madden','notable_addition'),
  ('Steve Hutchinson','LG','offense',92,'6''5"',313,'Right',76,'superstar','Power guard','Explosive, technically sound left guard who displaced defenders and anchored elite rushing attacks.','{"Press":28,"Speed":71,"Injury":97,"Agility":75,"Jumping":73,"Pursuit":48,"Release":53,"Stamina":95,"Carrying":63,"Catching":58,"Strength":98,"Tackling":53,"Trucking":63,"Awareness":97,"BC Vision":58,"Hit Power":65,"Juke Move":63,"Long Snap":43,"Spin Move":63,"Stiff Arm":63,"Toughness":99,"Break Sack":53,"Lead Block":96,"Play Action":23,"Power Moves":33,"Acceleration":77,"Break Tackle":63,"Man Coverage":28,"Run Blocking":99,"Deep Accuracy":16,"Finesse Moves":33,"Kicking Power":23,"Pass Blocking":95,"Zone Coverage":28,"Block Shedding":61,"Short Accuracy":23,"Throwing Power":43,"Impact Blocking":98,"Medium Accuracy":18,"Run Block Power":99,"Catch in Traffic":53,"Kick/Punt Return":16,"Kicking Accuracy":18,"Pass Block Power":95,"Play Recognition":53,"Throw on the Run":16,"Run Block Finesse":94,"Spectacular Catch":53,"Deep Route Running":43,"Pass Block Finesse":91,"Change of Direction":67,"Short Route Running":53,"Medium Route Running":48,"Throw Under Pressure":16}'::jsonb,'[{"name":"Puller Elite","description":"Dominant on pulls and traps.","type":"superstar"},{"name":"Nasty Streak","description":"Finishes blocks in space.","type":"superstar"},{"name":"Post Up","description":"Excels on double teams.","type":"superstar"}]'::jsonb,'legend','Michigan','muscular',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
