insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Alan Faneca','LG','offense',92,'6''5"',316,'Right',66,'superstar','Athletic power guard','Mobile, physical guard with elite pulling ability, consistency and second-level range.','{"Speed":67,"Acceleration":84,"Agility":82,"Strength":96,"Awareness":97,"Carrying":72,"BC Vision":72,"Break Tackle":72,"Trucking":67,"Stiff Arm":67,"Change of Direction":80,"Spin Move":67,"Juke Move":70,"Catching":62,"Catch in Traffic":57,"Spectacular Catch":57,"Short Route Running":52,"Medium Route Running":47,"Deep Route Running":42,"Release":47,"Jumping":82,"Throwing Power":42,"Short Accuracy":32,"Medium Accuracy":27,"Deep Accuracy":22,"Throw on the Run":27,"Throw Under Pressure":27,"Break Sack":42,"Play Action":32,"Pass Blocking":95,"Pass Block Power":95,"Pass Block Finesse":94,"Run Blocking":98,"Run Block Power":96,"Run Block Finesse":98,"Lead Block":96,"Impact Blocking":95,"Play Recognition":72,"Tackling":57,"Hit Power":57,"Block Shedding":52,"Finesse Moves":42,"Power Moves":42,"Pursuit":72,"Man Coverage":42,"Zone Coverage":47,"Press":37,"Kick/Punt Return":22,"Kicking Power":27,"Kicking Accuracy":22,"Stamina":92,"Toughness":92,"Injury":92,"Long Snap":42}'::jsonb,'[{"name":"Puller Elite","description":"Elite lead blocker in space.","type":"superstar"},{"name":"Secure Protector","description":"Reliable interior protection.","type":"superstar"},{"name":"Nasty Streak","description":"Physical finishing blocker.","type":"superstar"}]'::jsonb,'legend','LSU',null,null,'madden','notable_addition'),
  ('Kevin Mawae','C','offense',94,'6''4"',289,'Right',68,'superstar','Athletic center','Intelligent, mobile pivot with elite reach-blocking, toughness and protection calls.','{"Press":17,"Speed":72,"Injury":97,"Agility":78,"Jumping":72,"Pursuit":48,"Release":32,"Stamina":99,"Carrying":57,"Catching":50,"Strength":93,"Tackling":50,"Trucking":58,"Awareness":99,"BC Vision":42,"Hit Power":60,"Juke Move":40,"Long Snap":57,"Spin Move":36,"Stiff Arm":54,"Toughness":98,"Break Sack":46,"Lead Block":96,"Play Action":22,"Power Moves":38,"Acceleration":82,"Break Tackle":56,"Man Coverage":22,"Run Blocking":97,"Deep Accuracy":15,"Finesse Moves":26,"Kicking Power":22,"Pass Blocking":96,"Zone Coverage":27,"Block Shedding":48,"Short Accuracy":22,"Throwing Power":37,"Impact Blocking":99,"Medium Accuracy":17,"Run Block Power":98,"Catch in Traffic":46,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":96,"Play Recognition":42,"Throw on the Run":15,"Run Block Finesse":98,"Spectacular Catch":42,"Deep Route Running":15,"Pass Block Finesse":97,"Change of Direction":72,"Short Route Running":22,"Medium Route Running":17,"Throw Under Pressure":15}'::jsonb,'[{"name":"Identifier","description":"Recognizes pressure threats before the snap.","type":"superstar"},{"name":"All Day","description":"Resists pass-rush fatigue.","type":"superstar"},{"name":"Puller Elite","description":"Excels blocking in space.","type":"superstar"}]'::jsonb,'legend','LSU','muscular',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
