insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Jim Ringo','C','offense',94,'6''1"',232,'Right',51,'superstar','Technician center','Undersized but exceptionally quick and durable center who mastered leverage and positioning.','{"Press":17,"Speed":71,"Injury":96,"Agility":88,"Jumping":72,"Pursuit":48,"Release":32,"Stamina":99,"Carrying":57,"Catching":50,"Strength":90,"Tackling":50,"Trucking":58,"Awareness":99,"BC Vision":42,"Hit Power":60,"Juke Move":40,"Long Snap":62,"Spin Move":36,"Stiff Arm":54,"Toughness":99,"Break Sack":46,"Lead Block":99,"Play Action":22,"Power Moves":38,"Acceleration":81,"Break Tackle":56,"Man Coverage":22,"Run Blocking":96,"Deep Accuracy":15,"Finesse Moves":26,"Kicking Power":22,"Pass Blocking":95,"Zone Coverage":27,"Block Shedding":48,"Short Accuracy":22,"Throwing Power":37,"Impact Blocking":99,"Medium Accuracy":17,"Run Block Power":98,"Catch in Traffic":46,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":97,"Play Recognition":42,"Throw on the Run":15,"Run Block Finesse":98,"Spectacular Catch":42,"Deep Route Running":15,"Pass Block Finesse":96,"Change of Direction":72,"Short Route Running":22,"Medium Route Running":17,"Throw Under Pressure":15}'::jsonb,'[{"name":"Identifier","description":"Directs protection adjustments.","type":"superstar"},{"name":"Secure Protector","description":"Sustains interior blocks.","type":"superstar"},{"name":"Post Up","description":"Excels with combo blocks.","type":"superstar"}]'::jsonb,'legend','Syracuse','muscular',null,'madden','notable_addition'),
  ('Michael Strahan','LE','defense',94,'6''5"',255,'Right',92,'superstar','Power edge','Relentless left-end technician with leverage, hand power and elite run defense.','{"Press":17,"Speed":86,"Injury":96,"Agility":84,"Jumping":90,"Pursuit":98,"Release":32,"Stamina":98,"Carrying":84,"Catching":70,"Strength":95,"Tackling":97,"Trucking":92,"Awareness":97,"BC Vision":76,"Hit Power":99,"Juke Move":78,"Long Snap":42,"Spin Move":80,"Stiff Arm":88,"Toughness":99,"Break Sack":57,"Lead Block":38,"Play Action":22,"Power Moves":98,"Acceleration":88,"Break Tackle":90,"Man Coverage":22,"Run Blocking":44,"Deep Accuracy":15,"Finesse Moves":94,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":27,"Block Shedding":97,"Short Accuracy":22,"Throwing Power":42,"Impact Blocking":80,"Medium Accuracy":17,"Run Block Power":46,"Catch in Traffic":72,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":30,"Play Recognition":97,"Throw on the Run":15,"Run Block Finesse":42,"Spectacular Catch":74,"Deep Route Running":15,"Pass Block Finesse":27,"Change of Direction":84,"Short Route Running":22,"Medium Route Running":17,"Throw Under Pressure":15}'::jsonb,'[{"name":"Edge Threat","description":"Improved edge pressure.","type":"superstar"},{"name":"Power Specialist","description":"Dominant power-rush moves.","type":"superstar"},{"name":"No Outsiders","description":"Shuts down outside runs.","type":"superstar"}]'::jsonb,'legend','Texas Southern','heavy',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
