insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Howie Long','LE','defense',90,'6''5"',265,'Right',75,'superstar','Power edge','Explosive, versatile front-line defender with power, technique and inside-out flexibility.','{"Speed":82,"Acceleration":84,"Agility":82,"Strength":96,"Awareness":90,"Carrying":72,"BC Vision":72,"Break Tackle":72,"Trucking":67,"Stiff Arm":67,"Change of Direction":80,"Spin Move":67,"Juke Move":70,"Catching":62,"Catch in Traffic":57,"Spectacular Catch":57,"Short Route Running":52,"Medium Route Running":47,"Deep Route Running":42,"Release":47,"Jumping":82,"Throwing Power":42,"Short Accuracy":32,"Medium Accuracy":27,"Deep Accuracy":22,"Throw on the Run":27,"Throw Under Pressure":27,"Break Sack":42,"Play Action":32,"Pass Blocking":42,"Pass Block Power":40,"Pass Block Finesse":38,"Run Blocking":42,"Run Block Power":40,"Run Block Finesse":38,"Lead Block":37,"Impact Blocking":42,"Play Recognition":92,"Tackling":95,"Hit Power":90,"Block Shedding":95,"Finesse Moves":91,"Power Moves":97,"Pursuit":95,"Man Coverage":42,"Zone Coverage":47,"Press":37,"Kick/Punt Return":22,"Kicking Power":27,"Kicking Accuracy":22,"Stamina":92,"Toughness":92,"Injury":92,"Long Snap":42}'::jsonb,'[{"name":"Edge Threat","description":"Fast edge get-off.","type":"superstar"},{"name":"El Toro","description":"Converts speed to power.","type":"superstar"},{"name":"Run Stopper","description":"Disrupts rushing lanes.","type":"superstar"}]'::jsonb,'legend','Villanova',null,null,'madden','notable_addition'),
  ('Charles Haley','RE','defense',95,'6''5"',252,'Right',94,'superstar','Speed-power edge','Long, intense championship pass rusher with burst, bend and inside counter power.','{"Press":17,"Speed":90,"Injury":95,"Agility":89,"Jumping":90,"Pursuit":96,"Release":32,"Stamina":98,"Carrying":84,"Catching":70,"Strength":97,"Tackling":96,"Trucking":92,"Awareness":97,"BC Vision":76,"Hit Power":97,"Juke Move":78,"Long Snap":42,"Spin Move":80,"Stiff Arm":88,"Toughness":99,"Break Sack":57,"Lead Block":38,"Play Action":22,"Power Moves":95,"Acceleration":95,"Break Tackle":90,"Man Coverage":22,"Run Blocking":44,"Deep Accuracy":15,"Finesse Moves":97,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":27,"Block Shedding":94,"Short Accuracy":22,"Throwing Power":42,"Impact Blocking":80,"Medium Accuracy":17,"Run Block Power":46,"Catch in Traffic":72,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":30,"Play Recognition":98,"Throw on the Run":15,"Run Block Finesse":42,"Spectacular Catch":74,"Deep Route Running":15,"Pass Block Finesse":27,"Change of Direction":88,"Short Route Running":22,"Medium Route Running":17,"Throw Under Pressure":15}'::jsonb,'[{"name":"Edge Threat Elite","description":"Elite pressure from the edge.","type":"superstar"},{"name":"Strip Specialist","description":"Creates fumbles on sacks.","type":"superstar"},{"name":"Speedster","description":"Wins with speed rushes.","type":"superstar"}]'::jsonb,'legend','James Madison','muscular',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
