insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Jason Taylor','LE','defense',94,'6''6"',244,'Right',99,'superstar','Speed edge','Long, fluid edge defender with elite burst, bend, pursuit and turnover production.','{"Press":27,"Speed":91,"Injury":96,"Agility":90,"Jumping":98,"Pursuit":98,"Release":52,"Stamina":96,"Carrying":67,"Catching":57,"Strength":95,"Tackling":94,"Trucking":84,"Awareness":94,"BC Vision":62,"Hit Power":95,"Juke Move":62,"Long Snap":42,"Spin Move":62,"Stiff Arm":82,"Toughness":98,"Break Sack":52,"Lead Block":37,"Play Action":22,"Power Moves":95,"Acceleration":96,"Break Tackle":82,"Man Coverage":27,"Run Blocking":37,"Deep Accuracy":15,"Finesse Moves":98,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":27,"Block Shedding":94,"Short Accuracy":22,"Throwing Power":42,"Impact Blocking":80,"Medium Accuracy":17,"Run Block Power":37,"Catch in Traffic":52,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":32,"Play Recognition":96,"Throw on the Run":15,"Run Block Finesse":37,"Spectacular Catch":52,"Deep Route Running":42,"Pass Block Finesse":32,"Change of Direction":88,"Short Route Running":52,"Medium Route Running":47,"Throw Under Pressure":15}'::jsonb,'[{"name":"Edge Threat Elite","description":"Elite edge pressure.","type":"superstar"},{"name":"Speedster","description":"Wins quickly with speed.","type":"superstar"},{"name":"Strip Specialist","description":"Attacks the football on sacks.","type":"superstar"}]'::jsonb,'legend','Akron','heavy',null,'madden','notable_addition'),
  ('John Randle','DT','defense',95,'6''1"',290,'Right',93,'superstar','Penetrating three-technique','Explosive interior pass rusher with leverage, violent hands and relentless effort.','{"Press":18,"Speed":89,"Injury":97,"Agility":93,"Jumping":91,"Pursuit":98,"Release":33,"Stamina":99,"Carrying":85,"Catching":71,"Strength":92,"Tackling":95,"Trucking":93,"Awareness":97,"BC Vision":77,"Hit Power":97,"Juke Move":79,"Long Snap":43,"Spin Move":81,"Stiff Arm":89,"Toughness":99,"Break Sack":58,"Lead Block":39,"Play Action":23,"Power Moves":95,"Acceleration":94,"Break Tackle":91,"Man Coverage":23,"Run Blocking":45,"Deep Accuracy":16,"Finesse Moves":99,"Kicking Power":23,"Pass Blocking":33,"Zone Coverage":28,"Block Shedding":96,"Short Accuracy":23,"Throwing Power":43,"Impact Blocking":81,"Medium Accuracy":18,"Run Block Power":47,"Catch in Traffic":73,"Kick/Punt Return":16,"Kicking Accuracy":18,"Pass Block Power":31,"Play Recognition":99,"Throw on the Run":16,"Run Block Finesse":43,"Spectacular Catch":75,"Deep Route Running":16,"Pass Block Finesse":28,"Change of Direction":93,"Short Route Running":23,"Medium Route Running":18,"Throw Under Pressure":16}'::jsonb,'[{"name":"Inside Stuff","description":"Disrupts inside runs.","type":"superstar"},{"name":"El Toro","description":"Converts burst into power.","type":"superstar"},{"name":"Unpredictable","description":"Varied pass-rush plan limits resistance.","type":"superstar"}]'::jsonb,'legend','Texas A&I','heavy',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
