insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Warren Sapp','DT','defense',95,'6''2"',303,'Right',99,'superstar','Penetrating three-technique','Rare first-step interior disruptor with power, agility and backfield production.','{"Press":17,"Speed":80,"Injury":96,"Agility":80,"Jumping":90,"Pursuit":95,"Release":32,"Stamina":98,"Carrying":84,"Catching":70,"Strength":96,"Tackling":97,"Trucking":92,"Awareness":97,"BC Vision":76,"Hit Power":97,"Juke Move":78,"Long Snap":42,"Spin Move":80,"Stiff Arm":88,"Toughness":99,"Break Sack":57,"Lead Block":38,"Play Action":22,"Power Moves":98,"Acceleration":93,"Break Tackle":90,"Man Coverage":22,"Run Blocking":44,"Deep Accuracy":15,"Finesse Moves":96,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":27,"Block Shedding":97,"Short Accuracy":22,"Throwing Power":42,"Impact Blocking":80,"Medium Accuracy":17,"Run Block Power":46,"Catch in Traffic":72,"Kick/Punt Return":15,"Kicking Accuracy":17,"Pass Block Power":30,"Play Recognition":97,"Throw on the Run":15,"Run Block Finesse":42,"Spectacular Catch":74,"Deep Route Running":15,"Pass Block Finesse":27,"Change of Direction":80,"Short Route Running":22,"Medium Route Running":17,"Throw Under Pressure":15}'::jsonb,'[{"name":"Inside Stuff","description":"Dominates interior run fits.","type":"superstar"},{"name":"Under Pressure","description":"Disrupts nearby quarterback accuracy.","type":"superstar"},{"name":"El Toro","description":"Elite bull-rush conversion.","type":"superstar"}]'::jsonb,'legend','Miami','muscular',null,'madden','notable_addition'),
  ('Junior Seau','LOLB','defense',93,'6''3"',250,'Right',55,'superstar','Sideline-to-sideline linebacker','Explosive, instinctive playmaker with rare pursuit range, intensity and blitz timing.','{"Press":87,"Speed":92,"Injury":97,"Agility":89,"Jumping":97,"Pursuit":99,"Release":53,"Stamina":99,"Carrying":87,"Catching":81,"Strength":91,"Tackling":98,"Trucking":89,"Awareness":98,"BC Vision":83,"Hit Power":97,"Juke Move":79,"Long Snap":43,"Spin Move":78,"Stiff Arm":87,"Toughness":99,"Break Sack":81,"Lead Block":43,"Play Action":28,"Power Moves":89,"Acceleration":95,"Break Tackle":87,"Man Coverage":85,"Run Blocking":48,"Deep Accuracy":18,"Finesse Moves":91,"Kicking Power":23,"Pass Blocking":33,"Zone Coverage":93,"Block Shedding":94,"Short Accuracy":28,"Throwing Power":53,"Impact Blocking":89,"Medium Accuracy":23,"Run Block Power":51,"Catch in Traffic":79,"Kick/Punt Return":23,"Kicking Accuracy":18,"Pass Block Power":31,"Play Recognition":97,"Throw on the Run":23,"Run Block Finesse":45,"Spectacular Catch":81,"Deep Route Running":48,"Pass Block Finesse":28,"Change of Direction":89,"Short Route Running":58,"Medium Route Running":53,"Throw Under Pressure":23}'::jsonb,'[{"name":"Enforcer","description":"Creates stronger contact outcomes.","type":"superstar"},{"name":"Lurker","description":"Improved jumping interceptions.","type":"superstar"},{"name":"Secure Tackler","description":"Finishes tackles reliably.","type":"superstar"}]'::jsonb,'legend','USC','muscular',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
