insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Derrick Brooks','ROLB','defense',93,'6''0"',235,'Right',55,'superstar','Coverage linebacker','Fast, instinctive space defender with elite zone awareness, tackling and turnover production.','{"Press":87,"Speed":93,"Injury":97,"Agility":93,"Jumping":93,"Pursuit":98,"Release":53,"Stamina":99,"Carrying":87,"Catching":81,"Strength":89,"Tackling":97,"Trucking":89,"Awareness":99,"BC Vision":83,"Hit Power":91,"Juke Move":79,"Long Snap":43,"Spin Move":78,"Stiff Arm":87,"Toughness":98,"Break Sack":81,"Lead Block":43,"Play Action":28,"Power Moves":85,"Acceleration":95,"Break Tackle":87,"Man Coverage":87,"Run Blocking":48,"Deep Accuracy":18,"Finesse Moves":87,"Kicking Power":23,"Pass Blocking":33,"Zone Coverage":98,"Block Shedding":93,"Short Accuracy":28,"Throwing Power":53,"Impact Blocking":89,"Medium Accuracy":23,"Run Block Power":51,"Catch in Traffic":79,"Kick/Punt Return":23,"Kicking Accuracy":18,"Pass Block Power":31,"Play Recognition":99,"Throw on the Run":23,"Run Block Finesse":45,"Spectacular Catch":81,"Deep Route Running":48,"Pass Block Finesse":28,"Change of Direction":89,"Short Route Running":58,"Medium Route Running":53,"Throw Under Pressure":23}'::jsonb,'[{"name":"Flat Zone KO","description":"Improved reactions in underneath zones.","type":"superstar"},{"name":"Lurker","description":"Attacks passing lanes.","type":"superstar"},{"name":"Secure Tackler","description":"Consistent open-field tackling.","type":"superstar"}]'::jsonb,'legend','Florida State','muscular',null,'madden','notable_addition'),
  ('Brian Urlacher','MLB','defense',92,'6''4"',258,'Right',54,'superstar','Coverage middle linebacker','Rare size-speed field general with elite range, zone instincts and downhill closing ability.','{"Press":78,"Speed":93,"Injury":90,"Agility":91,"Jumping":88,"Pursuit":98,"Release":54,"Stamina":98,"Carrying":84,"Catching":82,"Strength":88,"Tackling":97,"Trucking":80,"Awareness":99,"BC Vision":80,"Hit Power":92,"Juke Move":76,"Long Snap":42,"Spin Move":72,"Stiff Arm":80,"Toughness":94,"Break Sack":76,"Lead Block":40,"Play Action":27,"Power Moves":76,"Acceleration":94,"Break Tackle":82,"Man Coverage":90,"Run Blocking":44,"Deep Accuracy":17,"Finesse Moves":80,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":96,"Block Shedding":90,"Short Accuracy":27,"Throwing Power":52,"Impact Blocking":86,"Medium Accuracy":22,"Run Block Power":42,"Catch in Traffic":80,"Kick/Punt Return":22,"Kicking Accuracy":17,"Pass Block Power":30,"Play Recognition":98,"Throw on the Run":22,"Run Block Finesse":40,"Spectacular Catch":78,"Deep Route Running":50,"Pass Block Finesse":27,"Change of Direction":91,"Short Route Running":60,"Medium Route Running":56,"Throw Under Pressure":22}'::jsonb,'[{"name":"Lurker","description":"Elite passing-lane range.","type":"superstar"},{"name":"Mid Zone KO","description":"Improved middle-zone reactions.","type":"superstar"},{"name":"Secure Tackler","description":"Reliable tackling in space.","type":"superstar"}]'::jsonb,'legend','New Mexico','muscular',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
