insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Mel Blount','CB','defense',94,'6''3"',205,'Right',47,'superstar','Physical press corner','Prototype big press corner whose length, strength and ball skills reshaped coverage rules.','{"Press":99,"Speed":94,"Injury":96,"Agility":90,"Jumping":94,"Pursuit":94,"Release":57,"Stamina":97,"Carrying":86,"Catching":88,"Strength":94,"Tackling":94,"Trucking":72,"Awareness":95,"BC Vision":84,"Hit Power":98,"Juke Move":86,"Long Snap":42,"Spin Move":82,"Stiff Arm":76,"Toughness":99,"Break Sack":72,"Lead Block":37,"Play Action":27,"Power Moves":42,"Acceleration":93,"Break Tackle":80,"Man Coverage":98,"Run Blocking":42,"Deep Accuracy":17,"Finesse Moves":37,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":94,"Block Shedding":80,"Short Accuracy":27,"Throwing Power":52,"Impact Blocking":67,"Medium Accuracy":22,"Run Block Power":40,"Catch in Traffic":92,"Kick/Punt Return":57,"Kicking Accuracy":17,"Pass Block Power":30,"Play Recognition":97,"Throw on the Run":22,"Run Block Finesse":38,"Spectacular Catch":94,"Deep Route Running":52,"Pass Block Finesse":27,"Change of Direction":94,"Short Route Running":62,"Medium Route Running":57,"Throw Under Pressure":22}'::jsonb,'[{"name":"One Step Ahead","description":"React quickly in man coverage.","type":"superstar"},{"name":"Bench Press","description":"Disrupts releases with physical jams.","type":"superstar"},{"name":"Pick Artist","description":"Improved interception success.","type":"superstar"}]'::jsonb,'legend','Southern','lean',null,'madden','notable_addition'),
  ('Herb Adderley','CB','defense',95,'6''0"',206,'Right',26,'superstar','Complete corner','Smooth, physical coverage defender with elite recovery speed, ball skills and return value.','{"Press":93,"Speed":95,"Injury":96,"Agility":94,"Jumping":96,"Pursuit":94,"Release":57,"Stamina":97,"Carrying":86,"Catching":91,"Strength":85,"Tackling":90,"Trucking":72,"Awareness":97,"BC Vision":84,"Hit Power":86,"Juke Move":86,"Long Snap":42,"Spin Move":82,"Stiff Arm":76,"Toughness":97,"Break Sack":72,"Lead Block":37,"Play Action":27,"Power Moves":42,"Acceleration":96,"Break Tackle":80,"Man Coverage":96,"Run Blocking":42,"Deep Accuracy":17,"Finesse Moves":37,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":97,"Block Shedding":67,"Short Accuracy":27,"Throwing Power":52,"Impact Blocking":67,"Medium Accuracy":22,"Run Block Power":40,"Catch in Traffic":90,"Kick/Punt Return":82,"Kicking Accuracy":17,"Pass Block Power":30,"Play Recognition":97,"Throw on the Run":22,"Run Block Finesse":38,"Spectacular Catch":94,"Deep Route Running":52,"Pass Block Finesse":27,"Change of Direction":94,"Short Route Running":62,"Medium Route Running":57,"Throw Under Pressure":22}'::jsonb,'[{"name":"Acrobat","description":"Improved diving plays on the ball.","type":"superstar"},{"name":"Pick Artist","description":"Finishes interception opportunities.","type":"superstar"},{"name":"Deep Route KO","description":"Disrupts vertical catches.","type":"superstar"}]'::jsonb,'legend','Michigan State','lean',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
