insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('Ty Law','CB','defense',94,'5''11"',200,'Right',24,'superstar','Press-man corner','Physical, intelligent matchup corner with route recognition and postseason ball production.','{"Press":97,"Speed":93,"Injury":94,"Agility":96,"Jumping":94,"Pursuit":90,"Release":57,"Stamina":97,"Carrying":86,"Catching":88,"Strength":80,"Tackling":80,"Trucking":72,"Awareness":97,"BC Vision":84,"Hit Power":68,"Juke Move":86,"Long Snap":42,"Spin Move":82,"Stiff Arm":76,"Toughness":98,"Break Sack":72,"Lead Block":37,"Play Action":27,"Power Moves":42,"Acceleration":96,"Break Tackle":80,"Man Coverage":98,"Run Blocking":42,"Deep Accuracy":17,"Finesse Moves":37,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":94,"Block Shedding":67,"Short Accuracy":27,"Throwing Power":52,"Impact Blocking":67,"Medium Accuracy":22,"Run Block Power":40,"Catch in Traffic":78,"Kick/Punt Return":42,"Kicking Accuracy":17,"Pass Block Power":30,"Play Recognition":98,"Throw on the Run":22,"Run Block Finesse":38,"Spectacular Catch":66,"Deep Route Running":52,"Pass Block Finesse":27,"Change of Direction":94,"Short Route Running":62,"Medium Route Running":57,"Throw Under Pressure":22}'::jsonb,'[{"name":"One Step Ahead","description":"Elite man-coverage reactions.","type":"superstar"},{"name":"Bench Press","description":"Controls receivers at the line.","type":"superstar"},{"name":"Pick Artist","description":"Capitalizes on turnover chances.","type":"superstar"}]'::jsonb,'legend','Michigan','lean',null,'madden','notable_addition'),
  ('Yale Lary','FS','defense',92,'5''11"',185,'Right',28,'superstar','Center-field safety','Range-based ball hawk and elite punter who combined anticipation with open-field reliability.','{"Press":84,"Speed":92,"Injury":96,"Agility":90,"Jumping":96,"Pursuit":94,"Release":57,"Stamina":97,"Carrying":86,"Catching":93,"Strength":80,"Tackling":86,"Trucking":72,"Awareness":97,"BC Vision":84,"Hit Power":80,"Juke Move":86,"Long Snap":42,"Spin Move":82,"Stiff Arm":76,"Toughness":96,"Break Sack":72,"Lead Block":37,"Play Action":27,"Power Moves":42,"Acceleration":94,"Break Tackle":80,"Man Coverage":91,"Run Blocking":42,"Deep Accuracy":17,"Finesse Moves":37,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":97,"Block Shedding":67,"Short Accuracy":27,"Throwing Power":52,"Impact Blocking":67,"Medium Accuracy":22,"Run Block Power":40,"Catch in Traffic":94,"Kick/Punt Return":37,"Kicking Accuracy":17,"Pass Block Power":30,"Play Recognition":98,"Throw on the Run":22,"Run Block Finesse":38,"Spectacular Catch":96,"Deep Route Running":52,"Pass Block Finesse":27,"Change of Direction":94,"Short Route Running":62,"Medium Route Running":57,"Throw Under Pressure":22}'::jsonb,'[{"name":"Deep Zone KO","description":"Improved reactions in deep zones.","type":"superstar"},{"name":"Pick Artist","description":"Finishes interceptions.","type":"superstar"},{"name":"Secure Tackler","description":"Reliable last-line tackling.","type":"superstar"}]'::jsonb,'legend','Texas A&M','lean',null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
