insert into public.rec_legend_catalog (
  name,position,position_group,est_ovr,height,weight,hand,jersey_number,dev_trait,archetype,build_note,
  attributes,abilities,legend_tier,college,body_type,photo_url,game_scope,catalog_group
) values
  ('John Lynch','SS','defense',93,'6''2"',220,'Right',47,'superstar','Box safety','Physical, intelligent safety with downhill force, leadership and dependable zone awareness.','{"Press":86,"Speed":92,"Injury":96,"Agility":88,"Jumping":92,"Pursuit":97,"Release":57,"Stamina":97,"Carrying":86,"Catching":82,"Strength":91,"Tackling":97,"Trucking":72,"Awareness":94,"BC Vision":84,"Hit Power":98,"Juke Move":86,"Long Snap":42,"Spin Move":82,"Stiff Arm":76,"Toughness":99,"Break Sack":72,"Lead Block":37,"Play Action":27,"Power Moves":42,"Acceleration":92,"Break Tackle":80,"Man Coverage":84,"Run Blocking":42,"Deep Accuracy":17,"Finesse Moves":37,"Kicking Power":22,"Pass Blocking":32,"Zone Coverage":94,"Block Shedding":80,"Short Accuracy":27,"Throwing Power":52,"Impact Blocking":67,"Medium Accuracy":22,"Run Block Power":40,"Catch in Traffic":84,"Kick/Punt Return":57,"Kicking Accuracy":17,"Pass Block Power":30,"Play Recognition":98,"Throw on the Run":22,"Run Block Finesse":38,"Spectacular Catch":82,"Deep Route Running":52,"Pass Block Finesse":27,"Change of Direction":94,"Short Route Running":62,"Medium Route Running":57,"Throw Under Pressure":22}'::jsonb,'[{"name":"Enforcer","description":"Delivers impactful contact.","type":"superstar"},{"name":"Secure Tackler","description":"Finishes open-field tackles.","type":"superstar"},{"name":"Flat Zone KO","description":"Disrupts underneath throws.","type":"superstar"}]'::jsonb,'legend','Stanford','standard',null,'madden','notable_addition'),
  ('Adam Vinatieri','K','offense',98,'6''0"',202,'Right',4,'superstar','Clutch placekicker','Historic pressure kicker with repeatable mechanics, cold-weather reliability and longevity.','{"Speed":82,"Acceleration":84,"Agility":82,"Strength":80,"Awareness":99,"Carrying":72,"BC Vision":72,"Break Tackle":72,"Trucking":67,"Stiff Arm":67,"Change of Direction":80,"Spin Move":67,"Juke Move":70,"Catching":62,"Catch in Traffic":57,"Spectacular Catch":57,"Short Route Running":52,"Medium Route Running":47,"Deep Route Running":42,"Release":47,"Jumping":82,"Throwing Power":42,"Short Accuracy":32,"Medium Accuracy":27,"Deep Accuracy":22,"Throw on the Run":27,"Throw Under Pressure":27,"Break Sack":42,"Play Action":32,"Pass Blocking":42,"Pass Block Power":40,"Pass Block Finesse":38,"Run Blocking":42,"Run Block Power":40,"Run Block Finesse":38,"Lead Block":37,"Impact Blocking":42,"Play Recognition":72,"Tackling":57,"Hit Power":57,"Block Shedding":52,"Finesse Moves":42,"Power Moves":42,"Pursuit":72,"Man Coverage":42,"Zone Coverage":47,"Press":37,"Kick/Punt Return":22,"Kicking Power":95,"Kicking Accuracy":99,"Stamina":92,"Toughness":99,"Injury":92,"Long Snap":42}'::jsonb,'[{"name":"Clutch Kicker","description":"Resists pressure effects on late kicks.","type":"superstar"},{"name":"Focused Kicker","description":"Slower kick-meter movement.","type":"superstar"},{"name":"Zen Kicker","description":"Improved kick-meter stability.","type":"superstar"}]'::jsonb,'legend','South Dakota State',null,null,'madden','notable_addition')
on conflict (name,position) do update set
  position_group=excluded.position_group,est_ovr=excluded.est_ovr,height=excluded.height,weight=excluded.weight,
  hand=excluded.hand,jersey_number=excluded.jersey_number,dev_trait=excluded.dev_trait,archetype=excluded.archetype,
  build_note=excluded.build_note,attributes=excluded.attributes,abilities=excluded.abilities,legend_tier=excluded.legend_tier,
  college=excluded.college,body_type=excluded.body_type,photo_url=excluded.photo_url,game_scope=excluded.game_scope,
  catalog_group=excluded.catalog_group;
