// User Rating (0-100): individual skill, blending win/performance signals, per-game
// production efficiency, and consistency of that production. Madden displays the raw
// number; CFB converts the same 0-100 scale to a letter grade (this feature's original
// ask was "numeric for Madden, letter grade for CFB"). Cumulative across every season
// the league has played — the number carries forward over season turnover instead of
// resetting to baseline, so a coach's body of work in Season 1 still shows up when
// Season 2 starts.
import { isCfb } from "@rec/shared";
import { ApiError } from "../../lib/errors.js";
import { supabase } from "../../lib/supabase.js";
import { withComputeCache } from "../../lib/compute-cache.js";
import { getCurrentLeagueContext } from "../league-context/league-context.service.js";

const RATINGS_CACHE_TTL_MS = 60_000;

const clamp = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n));
const round = (n: number, p = 1) => { const f = 10 ** p; return Math.round(n * f) / f; };

export function letterGradeForRating(rating: number): string {
  if (rating >= 97) return "A+";
  if (rating >= 93) return "A";
  if (rating >= 90) return "A-";
  if (rating >= 87) return "B+";
  if (rating >= 83) return "B";
  if (rating >= 80) return "B-";
  if (rating >= 77) return "C+";
  if (rating >= 73) return "C";
  if (rating >= 70) return "C-";
  if (rating >= 67) return "D+";
  if (rating >= 63) return "D";
  if (rating >= 60) return "D-";
  return "F";
}

function teamDisplayName(t: any): string {
  const name = (t?.name ?? "").trim();
  const nick = (t?.display_nick ?? "").trim();
  if (t?.is_relocated) {
    if (name && (!nick || name.toLowerCase() !== nick.toLowerCase())) return name;
    const combined = `${t?.display_city ?? ""} ${nick}`.trim();
    if (combined) return combined;
  }
  return name || nick || "Team";
}

export type UserRatingRow = {
  userId: string;
  displayName: string;
  teamId: string | null;
  teamName: string | null;
  rank: number;
  rating: number;
  grade: string;
  winScore: number;
  statScore: number;
  consistencyScore: number;
};

/**
 * statScore rewards production (yards/game), finishing drives (red-zone %), ball
 * security (turnovers/game), opportunism (takeaways/game — includes interceptions
 * generated by the user's defense), and moving the chains (first downs/game) — the
 * fields both Madden and CFB track identically, same cross-game-compatible approach
 * as the Most Heart EOS award formula.
 * winScore is the user's career win percentage (win/performance signal).
 * consistencyScore rewards steady per-game production: the lower the game-to-game
 * variance in total yards relative to the mean, the higher the score.
 * Final rating blends 30% win / 50% production / 20% consistency.
 */
async function computeUserRatingsBase(guildId: string) {
  const context = await getCurrentLeagueContext(guildId);
  const leagueId = context.leagueId;
  const game = context.rec_leagues.game;

  const assignmentsRes = await supabase
    .from("rec_team_assignments")
    .select("user_id,team_id,team:rec_teams(name,abbreviation,display_abbr,display_city,display_nick,is_relocated),user:rec_users(display_name)")
    .eq("league_id", leagueId)
    .eq("assignment_status", "active")
    .is("ended_at", null);
  if (assignmentsRes.error) throw new ApiError(500, "We couldn't load assignments for user rating. Please try again.", assignmentsRes.error);

  const userIds = [...new Set((assignmentsRes.data ?? []).map((a: any) => a.user_id).filter(Boolean))] as string[];
  if (!userIds.length) return { displayAsGrade: isCfb(game), users: [] };

  // Aggregated server-side (rec_user_rating_stat_totals, see supabase/migrations) instead
  // of pulling every rec_team_game_stats row for the league over the wire — this returns
  // one row per user with the exact totals computeUserRatings needs, computed by
  // replicating rowToGameStats' quarantine checks directly in SQL. Cuts a
  // hundreds-of-wide-rows fetch down to ~10-30 small rows.
  // Career scope: the RPC aggregates ALL seasons (p_season_number <= 0), so the rating
  // carries every season's production forward instead of resetting on season turnover.
  const statTotalsRes = await supabase.rpc("rec_user_rating_stat_totals", {
    p_league_id: leagueId,
    p_season_number: 0,
    p_user_ids: userIds,
    p_is_cfb: isCfb(game),
  });
  if (statTotalsRes.error) throw new ApiError(500, "We couldn't load stats for user rating. Please try again.", statTotalsRes.error);

  type StatTotalsRow = {
    user_id: string;
    games_played: number;
    wins: number;
    losses: number;
    ties: number;
    passing_yards: number;
    rushing_yards: number;
    first_downs: number;
    turnovers_committed: number;
    opponent_turnovers: number;
    red_zone_off_pct_avg: number;
    total_yards_stddev: number;
  };
  const statTotalsByUser = new Map<string, StatTotalsRow>(
    ((statTotalsRes.data ?? []) as StatTotalsRow[]).map((row) => [row.user_id, row]),
  );

  const rows: UserRatingRow[] = (assignmentsRes.data ?? []).map((a: any) => {
    const team = Array.isArray(a.team) ? a.team[0] : a.team;
    const user = Array.isArray(a.user) ? a.user[0] : a.user;
    const totals = statTotalsByUser.get(a.user_id);
    const gamesPlayed = Number(totals?.games_played ?? 0);
    const gp = gamesPlayed || 1;

    const wins = Number(totals?.wins ?? 0);
    const losses = Number(totals?.losses ?? 0);
    const ties = Number(totals?.ties ?? 0);
    const played = wins + losses + ties;
    const winPct = played > 0 ? (wins + 0.5 * ties) / played : 0.5;
    const winScore = clamp(winPct * 100, 0, 100);

    const passingYards = Number(totals?.passing_yards ?? 0);
    const rushingYards = Number(totals?.rushing_yards ?? 0);
    const yardsPerGame = (passingYards + rushingYards) / gp;
    const normYards = clamp(yardsPerGame / 400, 0, 1.2);
    const normRedZone = clamp(Number(totals?.red_zone_off_pct_avg ?? 0) / 100, 0, 1);
    const normTurnovers = clamp(1 - (Number(totals?.turnovers_committed ?? 0) / gp) / 3, 0, 1);
    const normTakeaways = clamp((Number(totals?.opponent_turnovers ?? 0) / gp) / 2, 0, 1);
    const normFirstDowns = clamp((Number(totals?.first_downs ?? 0) / gp) / 22, 0, 1);
    const statScore = clamp(30 * normYards + 20 * normRedZone + 20 * normTurnovers + 15 * normTakeaways + 15 * normFirstDowns, 0, 100);

    // Consistency: coefficient of variation of total yards/game (stddev / mean). A
    // single game (or no production) can't demonstrate consistency, so it lands at a
    // neutral midpoint rather than a false "perfectly consistent" 100.
    const yardsStddev = Number(totals?.total_yards_stddev ?? 0);
    const consistencyScore = gamesPlayed >= 2 && yardsPerGame > 0
      ? clamp(100 * (1 - clamp(yardsStddev / yardsPerGame, 0, 1)), 0, 100)
      : 50;

    const rating = clamp(0.30 * winScore + 0.50 * statScore + 0.20 * consistencyScore, 0, 100);
    return {
      userId: a.user_id,
      displayName: user?.display_name ?? "REC Member",
      teamId: a.team_id ?? null,
      teamName: team ? teamDisplayName(team) : null,
      rank: 0,
      rating: round(rating, 1),
      grade: letterGradeForRating(rating),
      winScore: round(winScore, 1),
      statScore: round(statScore, 1),
      consistencyScore: round(consistencyScore, 1),
    };
  });

  rows.sort((x, y) => y.rating - x.rating || x.displayName.localeCompare(y.displayName));
  rows.forEach((r, i) => { r.rank = i + 1; });

  return { displayAsGrade: isCfb(game), users: rows };
}

export async function computeUserRatings(guildId: string, viewerDiscordId?: string | null) {
  const base = await withComputeCache(`user-ratings:${guildId}`, RATINGS_CACHE_TTL_MS, () => computeUserRatingsBase(guildId));

  let viewerUserId: string | null = null;
  if (viewerDiscordId) {
    const acct = await supabase.from("rec_discord_accounts").select("user_id").eq("discord_id", viewerDiscordId).maybeSingle();
    viewerUserId = acct.data?.user_id ?? null;
  }

  return { ...base, viewerUserId };
}
