UPDATE rec_legend_catalog AS c
SET abilities = v.abilities
FROM (VALUES
  ('Ickey Woods', '[{"name":"Tank","description":"Mapped from 2K8 skill ''Power''.","type":"superstar"}]'::jsonb),
  ('Jay Berwanger', '[{"name":"Lead The Way","description":"Superstar: lead blocking.","type":"superstar"},{"name":"Tank","description":"Superstar: power.","type":"superstar"},{"name":"Natural Talent","description":"Superstar: block resistance.","type":"superstar"}]'::jsonb),
  ('John Kimbrough', '[{"name":"Lead The Way","description":"Superstar: lead blocking.","type":"superstar"},{"name":"Tank","description":"Superstar: power.","type":"superstar"},{"name":"Natural Talent","description":"Superstar: block resistance.","type":"superstar"}]'::jsonb),
  ('Larry Centers', '[{"name":"Lead The Way","description":"Superstar: lead blocking.","type":"superstar"},{"name":"Tank","description":"Superstar: power.","type":"superstar"},{"name":"Natural Talent","description":"Superstar: block resistance.","type":"superstar"}]'::jsonb),
  ('Merril Hoge', '[{"name":"Possession Catch","description":"Mapped from 2K8 skill ''Soft Hands''.","type":"superstar"}]'::jsonb),
  ('Steve Owens', '[{"name":"Lead The Way","description":"Superstar: lead blocking.","type":"superstar"},{"name":"Tank","description":"Superstar: power.","type":"superstar"},{"name":"Natural Talent","description":"Superstar: block resistance.","type":"superstar"}]'::jsonb),
  ('Tom Rathman', '[{"name":"Lead The Way","description":"Mapped from 2K8 skill ''Brick Wall''.","type":"superstar"},{"name":"Possession Catch","description":"Mapped from 2K8 skill ''Soft Hands''.","type":"superstar"}]'::jsonb),
  ('Minkah Fitzpatrick', '[{"name":"Man to Man","description":"Superstar: man coverage.","type":"superstar"},{"name":"Pick Artist","description":"Superstar: ball skills.","type":"superstar"},{"name":"Zone KO","description":"Superstar: zone.","type":"superstar"}]'::jsonb),
  ('Tyrann Mathieu', '[{"name":"Man to Man","description":"Superstar: man coverage.","type":"superstar"},{"name":"Pick Artist","description":"Superstar: ball skills.","type":"superstar"},{"name":"Zone KO","description":"Superstar: zone.","type":"superstar"}]'::jsonb),
  ('Abner Haynes', '[{"name":"Grab-N-Go","description":"Mapped from 2K8 skill ''Soft Hands''.","type":"superstar"}]'::jsonb),
  ('Archie Griffin', '[{"name":"Balance Beam","description":"Superstar: contact balance.","type":"superstar"},{"name":"Juke Box","description":"Superstar: elusiveness.","type":"superstar"},{"name":"Bulletproof","description":"Superstar: secure ball.","type":"superstar"}]'::jsonb),
  ('Barry Foster', '[{"name":"Truck","description":"Mapped from 2K8 skill ''Battering Ram''.","type":"superstar"}]'::jsonb),
  ('Billy Sims', '[{"name":"Home Run","description":"Mapped from 2K8 skill ''Break Away Burst''.","type":"superstar"},{"name":"Evasive","description":"Mapped from 2K8 skill ''Finesse''.","type":"superstar"}]'::jsonb),
  ('Charley Trippi', '[{"name":"Juke Box","description":"Mapped from 2K8 skill ''Quick Feet''.","type":"superstar"}]'::jsonb),
  ('Chris Warren', '[{"name":"Backfield Mismatch","description":"Mapped from 2K8 skill ''Workhorse''.","type":"superstar"}]'::jsonb),
  ('Christian McCaffrey', '[{"name":"Balance Beam","description":"Superstar: contact balance.","type":"superstar"},{"name":"Juke Box","description":"Superstar: elusiveness.","type":"superstar"},{"name":"Bulletproof","description":"Superstar: secure ball.","type":"superstar"}]'::jsonb),
  ('Christian Okoye', '[{"name":"Truck","description":"Mapped from 2K8 skill ''Battering Ram''.","type":"superstar"},{"name":"Balance Beam","description":"Mapped from 2K8 skill ''Branching Tackles''.","type":"superstar"},{"name":"Backfield Mismatch","description":"Mapped from 2K8 skill ''Workhorse''.","type":"superstar"}]'::jsonb),
  ('Chuck Foreman', '[{"name":"Ankle Breaker","description":"Mapped from 2K8 skill ''Ankle Breaker''.","type":"superstar"},{"name":"Grab-N-Go","description":"Mapped from 2K8 skill ''Soft Hands''.","type":"superstar"}]'::jsonb),
  ('Chuck Muncie', '[{"name":"Stiff Arm","description":"Mapped from 2K8 skill ''Arm of Steel''.","type":"superstar"},{"name":"Balance Beam","description":"Mapped from 2K8 skill ''Branching Tackles''.","type":"superstar"}]'::jsonb),
  ('Curt Warner', '[{"name":"Truck","description":"Mapped from 2K8 skill ''Battering Ram''.","type":"superstar"},{"name":"Human Joystick","description":"Mapped from 2K8 skill ''Stop on a Dime''.","type":"superstar"},{"name":"Backfield Mismatch","description":"Mapped from 2K8 skill ''Workhorse''.","type":"superstar"}]'::jsonb),
  ('Dalton Hilliard', '[{"name":"Spin Cycle","description":"Mapped from 2K8 skill ''Cyclone''.","type":"superstar"}]'::jsonb),
  ('Dave Meggett', '[{"name":"Return Man","description":"Mapped from 2K8 skill ''Return Spec''.","type":"superstar"},{"name":"Ankle Breaker","description":"Mapped from 2K8 skill ''Ankle Breaker''.","type":"superstar"},{"name":"Human Joystick","description":"Mapped from 2K8 skill ''Stop on a Dime''.","type":"superstar"}]'::jsonb),
  ('Derrick Henry', '[{"name":"Balance Beam","description":"Superstar: contact balance.","type":"superstar"},{"name":"Juke Box","description":"Superstar: elusiveness.","type":"superstar"},{"name":"Bulletproof","description":"Superstar: secure ball.","type":"superstar"}]'::jsonb),
  ('Eric Bieniemy', '[{"name":"Return Man","description":"Mapped from 2K8 skill ''Return Spec''.","type":"superstar"},{"name":"Spin Cycle","description":"Mapped from 2K8 skill ''Cyclone''.","type":"superstar"},{"name":"Grab-N-Go","description":"Mapped from 2K8 skill ''Soft Hands''.","type":"superstar"}]'::jsonb),
  ('Floyd Little', '[{"name":"Return Man","description":"Mapped from 2K8 skill ''Return Spec''.","type":"superstar"},{"name":"Juke Box","description":"Mapped from 2K8 skill ''Cutback''.","type":"superstar"}]'::jsonb),
  ('Freeman McNeil', '[{"name":"Ankle Breaker","description":"Mapped from 2K8 skill ''Ankle Breaker''.","type":"superstar"},{"name":"Juke Box","description":"Mapped from 2K8 skill ''Cutback''.","type":"superstar"}]'::jsonb),
  ('Greg Bell', '[{"name":"Stiff Arm","description":"Mapped from 2K8 skill ''Arm of Steel''.","type":"superstar"}]'::jsonb),
  ('Matt Snell', '[{"name":"Truck","description":"Mapped from 2K8 skill ''Battering Ram''.","type":"superstar"}]'::jsonb),
  ('Mike Rozier', '[{"name":"Stiff Arm","description":"Mapped from 2K8 skill ''Arm of Steel''.","type":"superstar"}]'::jsonb),
  ('Natrone Means', '[{"name":"Truck","description":"Mapped from 2K8 skill ''Battering Ram''.","type":"superstar"},{"name":"Backfield Mismatch","description":"Mapped from 2K8 skill ''Workhorse''.","type":"superstar"}]'::jsonb),
  ('Reggie Bush', '[{"name":"Balance Beam","description":"Superstar: contact balance.","type":"superstar"},{"name":"Juke Box","description":"Superstar: elusiveness.","type":"superstar"},{"name":"Bulletproof","description":"Superstar: secure ball.","type":"superstar"}]'::jsonb),
  ('Reggie Cobb', '[{"name":"Balance Beam","description":"Superstar: contact balance.","type":"superstar"},{"name":"Juke Box","description":"Superstar: elusiveness.","type":"superstar"},{"name":"Bulletproof","description":"Superstar: secure ball.","type":"superstar"}]'::jsonb),
  ('Ricky Williams', '[{"name":"Balance Beam","description":"Superstar: contact balance.","type":"superstar"},{"name":"Juke Box","description":"Superstar: elusiveness.","type":"superstar"},{"name":"Bulletproof","description":"Superstar: secure ball.","type":"superstar"}]'::jsonb),
  ('Ronnie Bull', '[{"name":"Grab-N-Go","description":"Mapped from 2K8 skill ''Soft Hands''.","type":"superstar"}]'::jsonb),
  ('Tony Canadeo', '[{"name":"Return Man","description":"Mapped from 2K8 skill ''Return Specialist''.","type":"superstar"}]'::jsonb),
  ('Tony Nathan', '[{"name":"Grab-N-Go","description":"Mapped from 2K8 skill ''Soft Hands''.","type":"superstar"}]'::jsonb),
  ('Al Del Greco', '[{"name":"Accurate","description":"Mapped from 2K8 skill ''Kick Accuracy''.","type":"superstar"},{"name":"Power Kick","description":"Mapped from 2K8 skill ''Kick Power''.","type":"superstar"}]'::jsonb),
  ('Eddie Murray', '[{"name":"Accurate","description":"Mapped from 2K8 skill ''Kick Accuracy''.","type":"superstar"}]'::jsonb),
  ('Garo Yepremian', '[{"name":"Accurate","description":"Mapped from 2K8 skill ''Kick Accuracy''.","type":"superstar"}]'::jsonb),
  ('Jeff Jaeger', '[{"name":"Accurate","description":"Mapped from 2K8 skill ''Kick Accuracy''.","type":"superstar"},{"name":"Power Kick","description":"Mapped from 2K8 skill ''Kick Power''.","type":"superstar"}]'::jsonb)
) AS v(name, abilities)
WHERE c.name = v.name;