// Rise to Immortality tweet bank — wave 2. Concatenate onto PLAYER_CHATTER_TEMPLATES /
// TWEET_TEMPLATES in tweet-bank.ts. Same placeholders and voices; new sentences only.
import type { PlayerChatterTemplate, TweetTemplate } from "./tweet-bank.js";

export const PLAYER_CHATTER_TEMPLATES_WAVE2: PlayerChatterTemplate[] = [
  // ================= self / praise (16) =================
  { mode: "self", tone: "praise", text: "Clocked in. {value} {statLabel}. That's the standard, not the ceiling." },
  { mode: "self", tone: "praise", text: "They can keep the narrative. I'll keep the {value} {statLabel}." },
  { mode: "self", tone: "praise", text: "Film don't lie and neither do {value} {statLabel}. Next." },
  { mode: "self", tone: "praise", text: "Built for {opponent} weeks. {value} {statLabel}. Write it down." },
  { mode: "self", tone: "praise", text: "I'm not surprised. Y'all shouldn't be either. {value} {statLabel}." },
  { mode: "self", tone: "praise", text: "Put the work in Thursday, cashed it Sunday. {value} {statLabel}." },
  { mode: "self", tone: "praise", text: "Don't need a speech. {value} {statLabel} vs {opponent} talks for me." },
  { mode: "self", tone: "praise", text: "Same process, same result. {value} {statLabel}. We good." },
  { mode: "self", tone: "praise", text: "I play for the guys in the huddle. {value} {statLabel} is just the receipt." },
  { mode: "self", tone: "praise", text: "Body feeling right. {value} {statLabel} today. More coming." },
  { mode: "self", tone: "praise", text: "They game-planned for everybody but the work. {value} {statLabel}." },
  { mode: "self", tone: "praise", text: "I heard the noise. Then I went for {value} {statLabel}. Funny how that works." },
  { mode: "self", tone: "praise", text: "Not a moment, a habit. {value} {statLabel} against {opponent}." },
  { mode: "self", tone: "praise", text: "Grateful. Hungry. {value} {statLabel}. Keep it pushing." },
  { mode: "self", tone: "praise", text: "If you blinked you missed it. {value} {statLabel} and I'm already on the next one." },
  { mode: "self", tone: "praise", text: "My guys ate. I ate. {value} {statLabel}. That's {team} football." },

  // ================= teammate / praise (14) =================
  { mode: "teammate", tone: "praise", text: "{targetPlayer} been that guy in the building all week. Today everybody else found out." },
  { mode: "teammate", tone: "praise", text: "Unreal from {targetPlayer}. I just try to stay out the way and let him cook." },
  { mode: "teammate", tone: "praise", text: "{targetPlayer} made my job easy today. That's a dog." },
  { mode: "teammate", tone: "praise", text: "Y'all better start putting {targetPlayer} in the conversation. {team} already knows." },
  { mode: "teammate", tone: "praise", text: "{targetPlayer} don't need a cape. He just shows up every Sunday." },
  { mode: "teammate", tone: "praise", text: "Love how {targetPlayer} competes. That's the standard in this locker room." },
  { mode: "teammate", tone: "praise", text: "{targetPlayer} went nuclear and still asked who we got next. That's my guy." },
  { mode: "teammate", tone: "praise", text: "Blocking for {targetPlayer} hits different when he's in that mode. Respect." },
  { mode: "teammate", tone: "praise", text: "{targetPlayer} been telling us in walkthroughs it was coming. Believe him next time." },
  { mode: "teammate", tone: "praise", text: "Special teams, sideline, huddle — {targetPlayer} raises the room. Today was the proof." },
  { mode: "teammate", tone: "praise", text: "I don't throw best-in-the-league around. {targetPlayer} making it hard not to." },
  { mode: "teammate", tone: "praise", text: "{targetPlayer} on {team} is a cheat code and I'm not even mad I'm on the same sideline." },
  { mode: "teammate", tone: "praise", text: "Give {targetPlayer} his flowers while he's still playing. Dude is HIM." },
  { mode: "teammate", tone: "praise", text: "{targetPlayer} made a statement today. Proud of my brother." },

  // ================= teammate / instigate (10) =================
  { mode: "teammate", tone: "instigate", text: "{targetPlayer} hit me with the I-told-you look after that play. sit down bro 😂" },
  { mode: "teammate", tone: "instigate", text: "{targetPlayer} really celebrated like the O-line wasn't sweating for him. we see you." },
  { mode: "teammate", tone: "instigate", text: "tell {targetPlayer} the group chat roasting starts at 9. he knows why." },
  { mode: "teammate", tone: "instigate", text: "{targetPlayer} said he was only 80 percent. 80 percent of what, a video game?" },
  { mode: "teammate", tone: "instigate", text: "not {targetPlayer} asking for the ball again after I just fed him. greedy and I love it." },
  { mode: "teammate", tone: "instigate", text: "{targetPlayer} still hasn't paid the fines from last week. production don't cover that 💀" },
  { mode: "teammate", tone: "instigate", text: "{targetPlayer} thinks that dance is original. it's not. still funny though." },
  { mode: "teammate", tone: "instigate", text: "somebody hide {targetPlayer}'s phone, he's about to tweet the score like he coached it." },
  { mode: "teammate", tone: "instigate", text: "{targetPlayer} talking extra in walkthroughs then actually backed it up. annoying." },
  { mode: "teammate", tone: "instigate", text: "I blocked three dudes and {targetPlayer} still took the credit in the huddle. noted." },

  // ================= rival / instigate (16) =================
  { mode: "rival", tone: "instigate", text: "{targetPlayer} can keep the quotes. we'll keep the tape." },
  { mode: "rival", tone: "instigate", text: "{targetTeam} talking like we forgot last time. {targetPlayer}, refresh their memory." },
  { mode: "rival", tone: "instigate", text: "I like {targetPlayer}. still lining up across from him with bad intentions." },
  { mode: "rival", tone: "instigate", text: "{targetTeam} better bring more than pressers. {targetPlayer} knows what's coming." },
  { mode: "rival", tone: "instigate", text: "Circle that date. {targetPlayer} already in my notes." },
  { mode: "rival", tone: "instigate", text: "{targetPlayer} had his moment. now it's our turn to ruin the vibe." },
  { mode: "rival", tone: "instigate", text: "Respect the name, not the comfort. {targetPlayer} getting tested soon." },
  { mode: "rival", tone: "instigate", text: "{targetTeam} fans tweeting like it's over. {targetPlayer} tell 'em it ain't." },
  { mode: "rival", tone: "instigate", text: "I don't do socials much. making an exception for {targetPlayer}. see you." },
  { mode: "rival", tone: "instigate", text: "{targetPlayer} ducking the mention but he sees this. lock in." },
  { mode: "rival", tone: "instigate", text: "Soft coverage, softer talk. {targetTeam} and {targetPlayer} both on notice." },
  { mode: "rival", tone: "instigate", text: "They can put {targetPlayer} on the poster. posters don't tackle." },
  { mode: "rival", tone: "instigate", text: "{targetTeam} got one good week and started a podcast. {targetPlayer} chill your guys out." },
  { mode: "rival", tone: "instigate", text: "I'm not sleeping. {targetPlayer} shouldn't either." },
  { mode: "rival", tone: "instigate", text: "Next time {targetPlayer} checks the stat sheet, look for my number next to the bruise." },
  { mode: "rival", tone: "instigate", text: "{targetTeam} wants smoke, {targetPlayer} already smelled it. we're coming." },

  // ================= rival / praise (14) =================
  { mode: "rival", tone: "praise", text: "Hate to say it: {targetPlayer} is a problem. {targetTeam} knew it, now I do too." },
  { mode: "rival", tone: "praise", text: "{targetPlayer} earned every bit of that. We'll still line up and compete." },
  { mode: "rival", tone: "praise", text: "You don't have to like {targetTeam} to respect {targetPlayer}. I do." },
  { mode: "rival", tone: "praise", text: "{targetPlayer} plays the right way. That's harder to admit than it should be." },
  { mode: "rival", tone: "praise", text: "I'll give {targetPlayer} his due. Then I'm studying that tape all night." },
  { mode: "rival", tone: "praise", text: "{targetTeam} riding {targetPlayer} for a reason. Dude's legit." },
  { mode: "rival", tone: "praise", text: "{targetPlayer} made plays I wish I had back. credit where it's due." },
  { mode: "rival", tone: "praise", text: "Not friends. Still respect. {targetPlayer} is that dude for {targetTeam}." },
  { mode: "rival", tone: "praise", text: "{targetPlayer} doesn't take plays off. I noticed. I didn't enjoy noticing." },
  { mode: "rival", tone: "praise", text: "Hardest matchup I had in a minute was {targetPlayer}. that's a compliment." },
  { mode: "rival", tone: "praise", text: "{targetTeam} should pay {targetPlayer} whatever he wants. I'm tired of chasing him." },
  { mode: "rival", tone: "praise", text: "Grudging flowers for {targetPlayer}. Now run it back so I can get even." },
  { mode: "rival", tone: "praise", text: "{targetPlayer} is the reason {targetTeam} is a different team. I said it." },
  { mode: "rival", tone: "praise", text: "You love competing against {targetPlayer} even when he ruins your afternoon." },
];

export const TWEET_TEMPLATES_WAVE2: TweetTemplate[] = [
  // ================= big_pass (10) =================
  { category: "big_pass", voice: "marcus", text: "{player} stacked completions against {opponent} on his way to {value} {statLabel}. That's rhythm, not a random explosion." },
  { category: "big_pass", voice: "marcus", text: "I charted {player}'s dropbacks this week. The {value} {statLabel} came from staying on schedule, not from hero throws." },
  { category: "big_pass", voice: "jalen", text: "{player} sliced {opponent} up for {value} {statLabel} and I still see people calling it a good matchup. Be serious." },
  { category: "big_pass", voice: "jalen", text: "If {opponent} has a plan for {player}, they left it in the hotel. {value} {statLabel}. Ridiculous." },
  { category: "big_pass", voice: "elliot", text: "{player} at {value} {statLabel} and {secondValue} {secondStatLabel} is an efficiency week, not just a volume week. Logging it." },
  { category: "big_pass", voice: "elliot", text: "Week {week}: {player} clears {value} {statLabel}. I'll check the air-yards versus YAC split before I overfit this." },
  { category: "big_pass", voice: "darius", text: "{player} was throwing guys open against {opponent}. {value} {statLabel} is what happens when the ball comes out on time." },
  { category: "big_pass", voice: "darius", text: "Watch the eyes — {player} wasn't staring down one side. {value} {statLabel} with full-field processing." },
  { category: "big_pass", voice: "generic", text: "{player} went {value} {statLabel} on {opponent} and tweeted like he still had another half. demon behavior." },
  { category: "big_pass", voice: "generic", text: "the {opponent} pass rush never got home and {player} made them pay. {value} yards. that's on them." },

  // ================= big_rush (10) =================
  { category: "big_rush", voice: "marcus", text: "{player} earned {value} yards the hard way — inside, downhill, no dancing. That's a runner I can trust in November." },
  { category: "big_rush", voice: "marcus", text: "The {value}-yard day from {player} vs {opponent} was gap discipline plus a second effort. Both showed up." },
  { category: "big_rush", voice: "jalen", text: "{opponent} stacked the box and {player} still walked out with {value} yards. That's bullying." },
  { category: "big_rush", voice: "jalen", text: "I don't want to hear about {opponent}'s run defense until they actually tackle {player}. {value} yards. Come on." },
  { category: "big_rush", voice: "elliot", text: "{player}'s {value} rushing yards this week is a workload-and-efficiency combo. I'll have the success-rate next." },
  { category: "big_rush", voice: "elliot", text: "Logging {value} yards for {player} against {opponent}. Explosive-run rate is the next number I want." },
  { category: "big_rush", voice: "darius", text: "{player} pressed the line, then hit it. {value} yards is vision showing up in the box score." },
  { category: "big_rush", voice: "darius", text: "You could see {opponent}'s linebackers a step late all afternoon. {player} punished that for {value}." },
  { category: "big_rush", voice: "generic", text: "{player} left {opponent} grabbing air. {value} rush yards. put some respect on the legs." },
  { category: "big_rush", voice: "generic", text: "not {player} trucking people for {value} like it's still Friday night. I fear no man except that." },

  // ================= big_receiving (10) =================
  { category: "big_receiving", voice: "marcus", text: "{player} won at the line of scrimmage all day. {value} {statLabel} vs {opponent} is a release win, not a coverage gift." },
  { category: "big_receiving", voice: "marcus", text: "I'd buy {player}'s {value}-{statLabel} week more if the target share holds next time out. Promising tape though." },
  { category: "big_receiving", voice: "jalen", text: "{opponent} put a safety over the top and {player} still cooked for {value} {statLabel}. Coverage is broken." },
  { category: "big_receiving", voice: "jalen", text: "{player} is uncovered in this league. {value} {statLabel}. Stop putting corners on islands." },
  { category: "big_receiving", voice: "elliot", text: "{player}: {value} {statLabel} in Week {week}. I'll want yards per route before I call this a role change." },
  { category: "big_receiving", voice: "elliot", text: "The {value}-{statLabel} output for {player} is a usage spike. Tracking whether it's sticky." },
  { category: "big_receiving", voice: "darius", text: "{player} stemmed those routes into the hip pocket of the coverage. {value} {statLabel} is route craft." },
  { category: "big_receiving", voice: "darius", text: "{opponent} played off and {player} ate the cushions. {value} {statLabel} — that's on the leverage." },
  { category: "big_receiving", voice: "generic", text: "{player} moved chains like it was a side quest. {value} {statLabel} vs {opponent}." },
  { category: "big_receiving", voice: "generic", text: "get {player} the ball. {value} {statLabel} and he still had another gear. I'm begging." },

  // ================= multi_td (13) =================
  { category: "multi_td", voice: "marcus", text: "{player} finished in the red zone more than once against {opponent}. That's situational football, not just skill." },
  { category: "multi_td", voice: "marcus", text: "Multiple scores from {player} this week. I liked the patience more than the celebrations." },
  { category: "multi_td", voice: "marcus", text: "A multi-TD week for {player} is useful data. I'll believe the role when the looks keep showing up." },
  { category: "multi_td", voice: "jalen", text: "{player} took {opponent} to the crib more than once and never asked for permission. That's a statement." },
  { category: "multi_td", voice: "jalen", text: "Stop letting {player} sniff the paint. Multiple TDs. {opponent} has to live with that tape." },
  { category: "multi_td", voice: "jalen", text: "{player} is collecting touchdowns like they're layover miles. {opponent} got fleeced." },
  { category: "multi_td", voice: "elliot", text: "Multi-score game for {player} vs {opponent}. I'll check red-zone target/carry share before calling it sustainable." },
  { category: "multi_td", voice: "elliot", text: "Logging another 2+ TD week for {player}. Frequency is starting to look structural." },
  { category: "multi_td", voice: "darius", text: "{player} stacked the pads and still scored. Multiple trips weren't scheme gifts — they were finishes." },
  { category: "multi_td", voice: "darius", text: "Watch the last two yards. {player} wanted those scores against {opponent}. That's the tell." },
  { category: "multi_td", voice: "generic", text: "{player} at the goal line is a jump-scare. {opponent} found that out twice." },
  { category: "multi_td", voice: "generic", text: "how is {player} allowed to score this many times in one afternoon. asking the league office." },
  { category: "multi_td", voice: "generic", text: "{player} said and another one without saying it. {opponent} heard it anyway." },

  // ================= turnover_heavy (13) =================
  { category: "turnover_heavy", voice: "marcus", text: "{player} lost the ball {value} times against {opponent}. Fixable technique, not a talent verdict." },
  { category: "turnover_heavy", voice: "marcus", text: "I'd rather {player} live to play the next series. {value} turnovers is the opposite of that lesson." },
  { category: "turnover_heavy", voice: "marcus", text: "One sloppy week with the football doesn't erase {player}'s body of work. It does go in the notes." },
  { category: "turnover_heavy", voice: "jalen", text: "{player} donated {value} possessions to {opponent}. That's not competing, that's charity." },
  { category: "turnover_heavy", voice: "jalen", text: "Film session for {player} is going to be a horror movie. {value} turnovers. Lights on, nobody talking." },
  { category: "turnover_heavy", voice: "jalen", text: "I can live with aggressive. I cannot live with {value} turnovers from {player}. Pick a lane." },
  { category: "turnover_heavy", voice: "elliot", text: "{value} turnovers for {player} this week is a massive expected-points swing. I'll have the EPA hit next report." },
  { category: "turnover_heavy", voice: "elliot", text: "Logging {player}'s {value}-turnover outing. Regression to his mean is likely — unless pressure rate says otherwise." },
  { category: "turnover_heavy", voice: "darius", text: "{player} held the ball a tick too long on at least one of those. {opponent} didn't steal all {value}." },
  { category: "turnover_heavy", voice: "darius", text: "The answer on a couple of those was the sideline. {player} tried to thread a window that had already closed." },
  { category: "turnover_heavy", voice: "generic", text: "{player} out here playing hot potato with {opponent}. {value} turnovers. I can't watch." },
  { category: "turnover_heavy", voice: "generic", text: "put the ball on a string, {player}. {value} giveaways is a cry for help." },
  { category: "turnover_heavy", voice: "generic", text: "we don't log into the box score this week. {player} vs {opponent} never happened. {value} turnovers. goodbye." },

  // ================= def_takeover (13) =================
  { category: "def_takeover", voice: "marcus", text: "{player} wrecked protection all afternoon. {value} {statLabel} vs {opponent} is a tone-setter." },
  { category: "def_takeover", voice: "marcus", text: "That's a defensive captain's week from {player}. {value} {statLabel} and the rest of the front fed off it." },
  { category: "def_takeover", voice: "marcus", text: "I'll bump {player} up my notes after {value} {statLabel}, with the usual caveat: do it again." },
  { category: "def_takeover", voice: "jalen", text: "{player} was a walk-in closet in {opponent}'s backfield. {value} {statLabel}. Unplayable." },
  { category: "def_takeover", voice: "jalen", text: "{opponent}'s OL has to request a new identity after {player} dropped {value} {statLabel} on them." },
  { category: "def_takeover", voice: "jalen", text: "Don't check the score, check {player}'s {value} {statLabel}. That's the story." },
  { category: "def_takeover", voice: "elliot", text: "{player} at {value} {statLabel} is a pressure-to-production week. I'll pull win-rate next." },
  { category: "def_takeover", voice: "elliot", text: "Outlier defensive week for {player} vs {opponent}: {value} {statLabel}. Tracking snap-adjusted rate." },
  { category: "def_takeover", voice: "darius", text: "{player} timed the snap better than {opponent}'s center did. {value} {statLabel} is get-off." },
  { category: "def_takeover", voice: "darius", text: "You can see {player} diagnosing motion pre-snap. {value} {statLabel} is the box-score version of that." },
  { category: "def_takeover", voice: "generic", text: "{player} hunting. {value} {statLabel}. {opponent} was the food." },
  { category: "def_takeover", voice: "generic", text: "give {player} a nickname already. {value} {statLabel} is video-game numbers." },
  { category: "def_takeover", voice: "generic", text: "{opponent} running a two-minute drill in the first quarter because of {player}. {value} {statLabel}." },

  // ================= playmaker (13) =================
  { category: "playmaker", voice: "marcus", text: "{player} stole a possession from {opponent} when the game needed a spark. Winning players do that." },
  { category: "playmaker", voice: "marcus", text: "That takeaway from {player} was earned leverage, not a bounce. I'll remember it in December." },
  { category: "playmaker", voice: "marcus", text: "Situationally, {player} was the smartest guy on the field on that play. {opponent} paid for the mistake." },
  { category: "playmaker", voice: "jalen", text: "{player} snatched the ball and the air out of {opponent}'s stadium. That's a vibe shift." },
  { category: "playmaker", voice: "jalen", text: "One play from {player} and {opponent} started looking at each other. I love a panic takeaway." },
  { category: "playmaker", voice: "jalen", text: "{player} said mine and the football listened. {opponent} can file a complaint." },
  { category: "playmaker", voice: "elliot", text: "Takeaway credited to {player}. I'll estimate the win-probability added — it's bigger than the highlight." },
  { category: "playmaker", voice: "elliot", text: "Logging {player}'s forced turnover vs {opponent}. Playmaking rate is a real skill curve, not luck." },
  { category: "playmaker", voice: "darius", text: "{player} jumped the route because he had the answer pre-snap. That's not gambling, that's studying." },
  { category: "playmaker", voice: "darius", text: "Hands, eyes, finish. {player} completed the takeaway. Most guys just get close." },
  { category: "playmaker", voice: "generic", text: "{player} with the dagger takeaway. {opponent} still loading the clip." },
  { category: "playmaker", voice: "generic", text: "the way {player} ripped that ball should be illegal. I'm obsessed." },
  { category: "playmaker", voice: "generic", text: "{opponent} had a drive, then {player} said nah. play of the week on my ballot." },

  // ================= quiet_game (13) =================
  { category: "quiet_game", voice: "marcus", text: "{player} was a non-factor in the box score vs {opponent}. I'll check usage before I check panic." },
  { category: "quiet_game", voice: "marcus", text: "Quiet nights happen. If {player}'s next three look like this, then we talk." },
  { category: "quiet_game", voice: "marcus", text: "{opponent} took {player} away and nobody else stepped up. That's a scheme win, not a talent fade — yet." },
  { category: "quiet_game", voice: "jalen", text: "{player} left no fingerprints on that game. {opponent} will take it. I have questions." },
  { category: "quiet_game", voice: "jalen", text: "Did {player} dress today? Because {opponent} played like he didn't." },
  { category: "quiet_game", voice: "jalen", text: "I'm filing {player}'s disappearing act under we'll-see-next-week — but I noticed." },
  { category: "quiet_game", voice: "elliot", text: "Low output week for {player}. Routes, carries, dropbacks will tell me if this was a game plan or a fade." },
  { category: "quiet_game", voice: "elliot", text: "Quiet week logged. {player}'s season-long per-game still holds unless Week {week} repeats." },
  { category: "quiet_game", voice: "darius", text: "{opponent} bracketed {player} and he stayed in scheme. That's professional. It's also quiet." },
  { category: "quiet_game", voice: "darius", text: "Sometimes the win is not forcing a bad look. {player} chose that. The stat sheet looks empty anyway." },
  { category: "quiet_game", voice: "generic", text: "{player} was on a milk carton today vs {opponent}." },
  { category: "quiet_game", voice: "generic", text: "quiet {player} game has the timeline in shambles. y'all were so loud last week." },
  { category: "quiet_game", voice: "generic", text: "if {player} is dealing with something, hope he's good. that was a ghost stat line." },

  // ================= milestone (13) =================
  { category: "milestone", voice: "marcus", text: "{player} just crossed {value} {statLabel}. Availability plus production. That's the whole job." },
  { category: "milestone", voice: "marcus", text: "Season mark: {player} at {value} {statLabel} through Week {week}. Quiet compounding." },
  { category: "milestone", voice: "marcus", text: "Milestones like {value} {statLabel} are what you get when a player never comes off the script." },
  { category: "milestone", voice: "jalen", text: "Put {player}'s {value} {statLabel} on a billboard. The league is still whispering." },
  { category: "milestone", voice: "jalen", text: "{value} {statLabel} for {player} and folks still doing is-he-elite debates. I'm tired." },
  { category: "milestone", voice: "jalen", text: "Through Week {week} {player} is at {value} {statLabel}. That's not a hot streak, that's a body of work." },
  { category: "milestone", voice: "elliot", text: "Checkpoint: {player} = {value} {statLabel} after Week {week}. Pace still projects to a career-year band." },
  { category: "milestone", voice: "elliot", text: "Crossing {value} {statLabel} is arbitrary, but {player}'s underlying rate that got him there is not." },
  { category: "milestone", voice: "darius", text: "{value} {statLabel} means coaches kept trusting {player} when it was 2nd-and-long, not just when it was easy." },
  { category: "milestone", voice: "darius", text: "That number — {value} {statLabel} — is snap after snap of doing the little things right." },
  { category: "milestone", voice: "generic", text: "{player} hit {value} {statLabel} and acted like it was a Tuesday. immortality loading." },
  { category: "milestone", voice: "generic", text: "update the graphics. {player} {value} {statLabel}. do it now." },
  { category: "milestone", voice: "generic", text: "remember when people said {player} wasn't a volume guy? {value} {statLabel}. anyway." },

  // ================= blowout_win (13) =================
  { category: "blowout_win", voice: "marcus", text: "{team} never let {opponent} into the script. {score}. Complementary football for four quarters." },
  { category: "blowout_win", voice: "marcus", text: "A {margin}-point margin is usually about failed third downs on one side and answers on the other. {team} had the answers." },
  { category: "blowout_win", voice: "marcus", text: "{score} is the kind of result {team} should file as a standard, not a party." },
  { category: "blowout_win", voice: "jalen", text: "{team} threw {opponent} in the blender. {score}. Next." },
  { category: "blowout_win", voice: "jalen", text: "That wasn't a game, that was a statement. {team} {score}. {opponent} can skip ahead mentally, they're already on next week." },
  { category: "blowout_win", voice: "jalen", text: "{margin} points. {team} was playing a different sport by the third quarter." },
  { category: "blowout_win", voice: "elliot", text: "{team} over {opponent} {score}. Expected-points gap likely even wider than {margin}. I'll confirm." },
  { category: "blowout_win", voice: "elliot", text: "Logging a {margin}-point win for {team}. Blowouts are high-signal for true team strength." },
  { category: "blowout_win", voice: "darius", text: "{team} won the first-down battle and {opponent} started guessing. {score} was inevitable after that." },
  { category: "blowout_win", voice: "darius", text: "By the two-minute warning of the first half, {opponent} looked solved. {team} {score}." },
  { category: "blowout_win", voice: "generic", text: "{team} {score}. {opponent} should've stayed at the hotel." },
  { category: "blowout_win", voice: "generic", text: "screenshot the {score} and send it to every {opponent} group chat. you're welcome." },
  { category: "blowout_win", voice: "generic", text: "mercy rule when. {team} hanging {score} on {opponent} is nasty work." },

  // ================= close_game (13) =================
  { category: "close_game", voice: "marcus", text: "{team} won the ugly one, {score}. Those stick with you more than the easy nights." },
  { category: "close_game", voice: "marcus", text: "A {margin}-point squeeze over {opponent} still counts in the standings. Composure showed." },
  { category: "close_game", voice: "marcus", text: "{team} made one more correct play in crunch time. {score}. That's December football in September." },
  { category: "close_game", voice: "jalen", text: "I aged watching {team} vs {opponent}. {score}. Never again. There will be an again." },
  { category: "close_game", voice: "jalen", text: "{team} cannot keep living like this. {score}. A win, yes. My blood pressure, no." },
  { category: "close_game", voice: "jalen", text: "{opponent} had the door open and {team} slammed it late. {score}. Cruel." },
  { category: "close_game", voice: "elliot", text: "{score}, margin {margin}. I'm treating {team}'s win as high-variance until the next sample." },
  { category: "close_game", voice: "elliot", text: "Close games invert narratives. {team} over {opponent} {score} is a coin-flip dressed as destiny." },
  { category: "close_game", voice: "darius", text: "Fourth quarter, {team} finally trusted the answers they'd seen all night. {score}." },
  { category: "close_game", voice: "darius", text: "{opponent} loaded a look they'd saved, and {team} still had a counter. That's why it's {score}." },
  { category: "close_game", voice: "generic", text: "I can't keep doing {team} one-score games. {score}. I am not built for this." },
  { category: "close_game", voice: "generic", text: "{team} vs {opponent} {score} should come with a warning label." },
  { category: "close_game", voice: "generic", text: "we got the W. {score}. I'm going to lie down. {margin} points is still too many for my health." },

  // ================= bad_loss (13) =================
  { category: "bad_loss", voice: "marcus", text: "{team} came out flat against {opponent}, {score}. The response week will tell us more than this one." },
  { category: "bad_loss", voice: "marcus", text: "Losing by {margin} to {opponent} is a tape problem, not a press-conference problem. {team} knows it." },
  { category: "bad_loss", voice: "marcus", text: "{score} is a result {team} has to metabolize, not explain away." },
  { category: "bad_loss", voice: "jalen", text: "{team} just handed {opponent} a {score} souvenir. I have no defense for that." },
  { category: "bad_loss", voice: "jalen", text: "Rankings go in the shredder. {team} lost {score} to {opponent}. Goodnight." },
  { category: "bad_loss", voice: "jalen", text: "The {team} hype package needs a recall. {score}. That's not a hiccup, that's a crater." },
  { category: "bad_loss", voice: "elliot", text: "{team} {score} vs {opponent}. I'll wait on the leftover efficiency before I rewrite the season prior." },
  { category: "bad_loss", voice: "elliot", text: "A {margin}-point loss is a fat left tail. Logging it for {team}; one week still isn't a prior." },
  { category: "bad_loss", voice: "darius", text: "{team} lost the adjustment game. {opponent} changed, nobody answered. {score}." },
  { category: "bad_loss", voice: "darius", text: "Want-to showed up on {opponent}'s sideline and went missing on {team}'s. {score} followed." },
  { category: "bad_loss", voice: "generic", text: "{team} {score} loss. the timeline is unusable. {opponent} eating good tonight." },
  { category: "bad_loss", voice: "generic", text: "who had {team} laying an egg vs {opponent} {score} on their bingo card. because wow." },
  { category: "bad_loss", voice: "generic", text: "{team} fans mute your mentions. {score} is going to be a long scroll." },

  // ================= hype (13) =================
  { category: "hype", voice: "marcus", text: "Week {week} is a full slate of evidence. I'll sort signal from noise once the tape is in." },
  { category: "hype", voice: "marcus", text: "Good, messy, real football this week. My board gets a pencil, not a Sharpie, until I rewatch." },
  { category: "hype", voice: "marcus", text: "If you only watched the highlights from Week {week}, you missed the games that actually matter." },
  { category: "hype", voice: "jalen", text: "Week {week} was chaos with a capital C. I need a podium and a headset." },
  { category: "hype", voice: "jalen", text: "Some of y'all were so confident on Saturday. Week {week} happened. How we feeling?" },
  { category: "hype", voice: "jalen", text: "I told you Week {week} would humble somebody. I did not expect it to humble this many somebodies." },
  { category: "hype", voice: "elliot", text: "Week {week} dump is loaded. Efficiency tables first, narratives second." },
  { category: "hype", voice: "elliot", text: "Box scores from Week {week} are the trailer. The model cut is the movie." },
  { category: "hype", voice: "darius", text: "I already know which Week {week} snaps I'm clipping. A few guys grew up on tape." },
  { category: "hype", voice: "darius", text: "Week {week} separated processors from athletes. We'll name names after I rewind." },
  { category: "hype", voice: "generic", text: "Week {week} in this league is why I don't make plans on Sundays." },
  { category: "hype", voice: "generic", text: "the group chat after Week {week} should be studied by scientists." },
  { category: "hype", voice: "generic", text: "don't sleep. open the app. Week {week} was unhinged." },

  // ================= taunt (13) =================
  { category: "taunt", voice: "jalen", text: "{team} talking like the tape is optional. It isn't." },
  { category: "taunt", voice: "jalen", text: "I've seen enough of {team} this season. The aura is rented." },
  { category: "taunt", voice: "jalen", text: "{team} needs a schedule strength intervention. Beating ghosts isn't a personality." },
  { category: "taunt", voice: "jalen", text: "Every week I wait for {team} to look like the poster. Every week I get the disclaimer." },
  { category: "taunt", voice: "jalen", text: "{opponent} just handed {team} a blueprint and I know they won't read it. Classic." },
  { category: "taunt", voice: "generic", text: "{team} is a vibes team in a results league. noted." },
  { category: "taunt", voice: "generic", text: "the {team} highlight package still hitting harder than the actual games. curious." },
  { category: "taunt", voice: "generic", text: "{team} fans posting we're so back on a weekly subscription. cancel it." },
  { category: "taunt", voice: "generic", text: "if {team} was a stock I'd be selling the rip. Week {week} didn't help." },
  { category: "taunt", voice: "generic", text: "{team} always looks good in the preview graphic. then the whistle blows." },
  { category: "taunt", voice: "generic", text: "not {team} asking for respect with that film. sit down." },
  { category: "taunt", voice: "marcus", text: "{team} still has to prove it against teams that can punch back. The resume has gaps." },
  { category: "taunt", voice: "elliot", text: "{team}'s record is outrunning the efficiency. That gap usually closes, and not in the fun direction." },

  // ================= praise (13) =================
  { category: "praise", voice: "marcus", text: "{team} keeps winning the unglamorous downs. That's a December club if I've ever evaluated one." },
  { category: "praise", voice: "marcus", text: "{player} has stacked good weeks without the associated circus. That's my kind of evaluation." },
  { category: "praise", voice: "jalen", text: "I'm on the {player} train and I'm not getting off. Put some respect on him." },
  { category: "praise", voice: "jalen", text: "{team} has been that squad and I'm tired of pretending it's a hot take." },
  { category: "praise", voice: "elliot", text: "{player}'s per-play numbers have been quietly screaming all year. The counting stats are catching up." },
  { category: "praise", voice: "elliot", text: "{team}'s efficiency profile is contender-shaped even when the discourse isn't." },
  { category: "praise", voice: "darius", text: "{player} plays on time whether it's a national window or a quiet afternoon. That's the standard." },
  { category: "praise", voice: "darius", text: "Fundamentally, {team} is cleaner than half the teams getting airtime. That matters." },
  { category: "praise", voice: "generic", text: "flowers for {player}. that's the post." },
  { category: "praise", voice: "generic", text: "{team} been nice. say it." },
  { category: "praise", voice: "generic", text: "if you still sleeping on {player} that's a you problem." },
  { category: "praise", voice: "generic", text: "{player} consistency should be taught in school." },
  { category: "praise", voice: "generic", text: "respect thread for {team} because the refs of public opinion keep missing calls." },

  // ================= camp_buzz (14) — no opponent/score/week/margin, no game result =================
  { category: "camp_buzz", voice: "marcus", text: "{player} keeps showing up on the {team} practice reports I trust. That's a camp story I'll actually track." },
  { category: "camp_buzz", voice: "marcus", text: "I don't grade pads, but {player} has {team}'s coaches using a different tone already." },
  { category: "camp_buzz", voice: "marcus", text: "Too soon for rankings. Not too soon to say {player} is earning first-team reps in {team} camp." },
  { category: "camp_buzz", voice: "jalen", text: "{player} in {team} camp is already a main-character arc and we haven't kicked a real ball." },
  { category: "camp_buzz", voice: "jalen", text: "I'm buying {player} stock in August. {team} better buckle up." },
  { category: "camp_buzz", voice: "elliot", text: "Zero official stats, full spreadsheet ready. {player} is on the {team} watchlist the second games count." },
  { category: "camp_buzz", voice: "elliot", text: "Camp noise is noisy. I'm still tagging {player} in the {team} preseason tracker because the buzz is persistent." },
  { category: "camp_buzz", voice: "elliot", text: "I'll wait for real snaps, but the {team} camp notes on {player} are unusually consistent across sources." },
  { category: "camp_buzz", voice: "darius", text: "{player}'s dropback cadence in camp already looks like a starter's. {team} is going to have a decision." },
  { category: "camp_buzz", voice: "darius", text: "You can tell {player} spent the offseason in the playbook. The {team} install isn't slowing him down." },
  { category: "camp_buzz", voice: "darius", text: "Footwork looks cleaner on {player} this summer. That's the kind of camp detail I actually care about." },
  { category: "camp_buzz", voice: "generic", text: "{team} camp videos of {player} got me doing too much and I'm not sorry." },
  { category: "camp_buzz", voice: "generic", text: "not a snap that counts and {player} already living rent-free in the {team} fanbase." },
  { category: "camp_buzz", voice: "generic", text: "{player} allegedly cooked in shorts. {team} fans are insufferable already. I get it though." },
];
