import type { FastifyInstance } from "fastify";
import { requireInternalApiKey } from "../../lib/auth.js";
import { requireBotOrUserSession } from "../../lib/user-auth.js";
import { sendError } from "../../lib/errors.js";
import { CreateDefaultTeamsSchema, CustomTeamReplacementSchema, LinkUserToTeamSchema, ResetDefaultTeamsSchema, UnlinkAllTeamsSchema, UnlinkTeamSchema } from "./team-ownership.schemas.js";
import { createCustomTeamReplacement, createDefaultTeamsForGuild, getTeamDataConflicts, linkUserToTeam, listLinkedUsersTeams, listOpenTeams, resetDefaultTeamsForGuild, unlinkAllTeamsForGuild, unlinkTeamForGuild } from "./team-ownership.service.js";
export async function teamOwnershipRoutes(app: FastifyInstance) {
 app.post("/v1/team-ownership/default-teams", async (request, reply) => { try { requireInternalApiKey(request); return reply.send(await createDefaultTeamsForGuild(CreateDefaultTeamsSchema.parse(request.body))); } catch (error) { return sendError(reply, error); } });
 app.post("/v1/team-ownership/reset-default-teams", async (request, reply) => { try { requireInternalApiKey(request); return reply.send(await resetDefaultTeamsForGuild(ResetDefaultTeamsSchema.parse(request.body))); } catch (error) { return sendError(reply, error); } });
 app.post("/v1/team-ownership/custom-team-replacement", async (request, reply) => { try { requireInternalApiKey(request); return reply.send(await createCustomTeamReplacement(CustomTeamReplacementSchema.parse(request.body))); } catch (error) { return sendError(reply, error); } });
 app.post("/v1/team-ownership/team-conflicts", async (request, reply) => { try { requireInternalApiKey(request); return reply.send(await getTeamDataConflicts((request.body as { guildId: string }).guildId)); } catch (error) { return sendError(reply, error); } });
 app.post("/v1/team-ownership/link-user-team", async (request, reply) => { try { const auth = await requireBotOrUserSession(request, { resolveGuildId: (r: any) => r.body?.guildId, permission: "co_commissioner" }); const input = LinkUserToTeamSchema.parse(request.body); if (auth.mode === "user" && !input.requestedByDiscordId) input.requestedByDiscordId = auth.discordId; return reply.send(await linkUserToTeam(input)); } catch (error) { return sendError(reply, error); } });
 app.get("/v1/team-ownership/:guildId/linked", async (request, reply) => { try { await requireBotOrUserSession(request, { resolveGuildId: (r: any) => (r.params as { guildId: string }).guildId, permission: "member" }); const { guildId } = request.params as { guildId: string }; return reply.send(await listLinkedUsersTeams(guildId)); } catch (error) { return sendError(reply, error); } });
 app.get("/v1/team-ownership/:guildId/open-teams", async (request, reply) => { try { await requireBotOrUserSession(request, { resolveGuildId: (r: any) => (r.params as { guildId: string }).guildId, permission: "member" }); const { guildId } = request.params as { guildId: string }; return reply.send(await listOpenTeams(guildId)); } catch (error) { return sendError(reply, error); } });
 app.post("/v1/team-ownership/unlink-all", async (request, reply) => { try { requireInternalApiKey(request); return reply.send(await unlinkAllTeamsForGuild(UnlinkAllTeamsSchema.parse(request.body))); } catch (error) { return sendError(reply, error); } });
 app.post("/v1/team-ownership/unlink-team", async (request, reply) => { try { const auth = await requireBotOrUserSession(request, { resolveGuildId: (r: any) => r.body?.guildId, permission: "co_commissioner" }); const input = UnlinkTeamSchema.parse(request.body); if (auth.mode === "user" && !input.requestedByDiscordId) input.requestedByDiscordId = auth.discordId; return reply.send(await unlinkTeamForGuild(input)); } catch (error) { return sendError(reply, error); } });
}
