export type CfbTeamOption = {
  name: string;
  mascot: string;
  abbreviation: string;
  conference: string;
  division: string;
};

function team(name: string, mascot: string, abbreviation: string, conference: string): CfbTeamOption {
  return { name, mascot, abbreviation, conference, division: "Teams" };
}

export const CFB_27_TEAMS: CfbTeamOption[] = [
  team("Boston College", "Eagles", "BC", "ACC"),
  team("California", "Golden Bears", "CAL", "ACC"),
  team("Clemson", "Tigers", "CLEM", "ACC"),
  team("Duke", "Blue Devils", "DUKE", "ACC"),
  team("Florida State", "Seminoles", "FSU", "ACC"),
  team("Georgia Tech", "Yellow Jackets", "GT", "ACC"),
  team("Louisville", "Cardinals", "LOU", "ACC"),
  team("Miami", "Hurricanes", "MIA", "ACC"),
  team("North Carolina", "Tar Heels", "UNC", "ACC"),
  team("NC State", "Wolfpack", "NCST", "ACC"),
  team("Pitt", "Panthers", "PITT", "ACC"),
  team("SMU", "Mustangs", "SMU", "ACC"),
  team("Stanford", "Cardinal", "STAN", "ACC"),
  team("Syracuse", "Orange", "SYR", "ACC"),
  team("Virginia", "Cavaliers", "UVA", "ACC"),
  team("Virginia Tech", "Hokies", "VT", "ACC"),
  team("Wake Forest", "Demon Deacons", "WAKE", "ACC"),

  team("Army", "Black Knights", "ARMY", "American"),
  team("Charlotte", "49ers", "CLT", "American"),
  team("East Carolina", "Pirates", "ECU", "American"),
  team("Florida Atlantic", "Owls", "FAU", "American"),
  team("Memphis", "Tigers", "MEM", "American"),
  team("Navy", "Midshipmen", "NAVY", "American"),
  team("North Texas", "Mean Green", "UNT", "American"),
  team("Rice", "Owls", "RICE", "American"),
  team("South Florida", "Bulls", "USF", "American"),
  team("Temple", "Owls", "TEMP", "American"),
  team("Tulane", "Green Wave", "TULN", "American"),
  team("Tulsa", "Golden Hurricane", "TLSA", "American"),
  team("UAB", "Blazers", "UAB", "American"),
  team("UTSA", "Roadrunners", "UTSA", "American"),

  team("Illinois", "Fighting Illini", "ILL", "Big Ten"),
  team("Indiana", "Hoosiers", "IND", "Big Ten"),
  team("Iowa", "Hawkeyes", "IOWA", "Big Ten"),
  team("Maryland", "Terrapins", "MD", "Big Ten"),
  team("Michigan", "Wolverines", "MICH", "Big Ten"),
  team("Michigan State", "Spartans", "MSU", "Big Ten"),
  team("Minnesota", "Golden Gophers", "MINN", "Big Ten"),
  team("Nebraska", "Cornhuskers", "NEB", "Big Ten"),
  team("Northwestern", "Wildcats", "NW", "Big Ten"),
  team("Ohio State", "Buckeyes", "OSU", "Big Ten"),
  team("Oregon", "Ducks", "ORE", "Big Ten"),
  team("Penn State", "Nittany Lions", "PSU", "Big Ten"),
  team("Purdue", "Boilermakers", "PUR", "Big Ten"),
  team("Rutgers", "Scarlet Knights", "RUT", "Big Ten"),
  team("UCLA", "Bruins", "UCLA", "Big Ten"),
  team("USC", "Trojans", "USC", "Big Ten"),
  team("Washington", "Huskies", "WASH", "Big Ten"),
  team("Wisconsin", "Badgers", "WIS", "Big Ten"),

  team("Arizona", "Wildcats", "ARIZ", "Big 12"),
  team("Arizona State", "Sun Devils", "ASU", "Big 12"),
  team("Baylor", "Bears", "BAY", "Big 12"),
  team("BYU", "Cougars", "BYU", "Big 12"),
  team("Cincinnati", "Bearcats", "CIN", "Big 12"),
  team("Colorado", "Buffaloes", "COLO", "Big 12"),
  team("Houston", "Cougars", "HOU", "Big 12"),
  team("Iowa State", "Cyclones", "ISU", "Big 12"),
  team("Kansas", "Jayhawks", "KU", "Big 12"),
  team("Kansas State", "Wildcats", "KSU", "Big 12"),
  team("Oklahoma State", "Cowboys", "OKST", "Big 12"),
  team("TCU", "Horned Frogs", "TCU", "Big 12"),
  team("Texas Tech", "Red Raiders", "TTU", "Big 12"),
  team("UCF", "Knights", "UCF", "Big 12"),
  team("Utah", "Utes", "UTAH", "Big 12"),
  team("West Virginia", "Mountaineers", "WVU", "Big 12"),

  team("Delaware", "Blue Hens", "DEL", "C-USA"),
  team("FIU", "Panthers", "FIU", "C-USA"),
  team("Jacksonville State", "Gamecocks", "JVST", "C-USA"),
  team("Kennesaw State", "Owls", "KENN", "C-USA"),
  team("Liberty", "Flames", "LIB", "C-USA"),
  team("Louisiana Tech", "Bulldogs", "LT", "C-USA"),
  team("Middle Tennessee", "Blue Raiders", "MTSU", "C-USA"),
  team("Missouri State", "Bears", "MOST", "C-USA"),
  team("New Mexico State", "Aggies", "NMSU", "C-USA"),
  team("Sam Houston", "Bearkats", "SHSU", "C-USA"),
  team("UTEP", "Miners", "UTEP", "C-USA"),
  team("Western Kentucky", "Hilltoppers", "WKU", "C-USA"),

  team("Akron", "Zips", "AKR", "MAC"),
  team("Ball State", "Cardinals", "BALL", "MAC"),
  team("Bowling Green", "Falcons", "BGSU", "MAC"),
  team("Buffalo", "Bulls", "BUFF", "MAC"),
  team("Central Michigan", "Chippewas", "CMU", "MAC"),
  team("Eastern Michigan", "Eagles", "EMU", "MAC"),
  team("Kent State", "Golden Flashes", "KENT", "MAC"),
  team("Miami (OH)", "RedHawks", "MOH", "MAC"),
  team("Northern Illinois", "Huskies", "NIU", "MAC"),
  team("Ohio", "Bobcats", "OHIO", "MAC"),
  team("Toledo", "Rockets", "TOL", "MAC"),
  team("UMass", "Minutemen", "UMASS", "MAC"),
  team("Western Michigan", "Broncos", "WMU", "MAC"),

  team("Air Force", "Falcons", "AFA", "Mountain West"),
  team("Boise State", "Broncos", "BOIS", "Mountain West"),
  team("Colorado State", "Rams", "CSU", "Mountain West"),
  team("Fresno State", "Bulldogs", "FRES", "Mountain West"),
  team("Hawai'i", "Rainbow Warriors", "HAW", "Mountain West"),
  team("Nevada", "Wolf Pack", "NEV", "Mountain West"),
  team("New Mexico", "Lobos", "UNM", "Mountain West"),
  team("San Diego State", "Aztecs", "SDSU", "Mountain West"),
  team("San Jose State", "Spartans", "SJSU", "Mountain West"),
  team("UNLV", "Rebels", "UNLV", "Mountain West"),
  team("Utah State", "Aggies", "USU", "Mountain West"),
  team("Wyoming", "Cowboys", "WYO", "Mountain West"),

  team("Oregon State", "Beavers", "ORST", "Pac-12"),
  team("Washington State", "Cougars", "WSU", "Pac-12"),

  team("Alabama", "Crimson Tide", "ALA", "SEC"),
  team("Arkansas", "Razorbacks", "ARK", "SEC"),
  team("Auburn", "Tigers", "AUB", "SEC"),
  team("Florida", "Gators", "FLA", "SEC"),
  team("Georgia", "Bulldogs", "UGA", "SEC"),
  team("Kentucky", "Wildcats", "UK", "SEC"),
  team("LSU", "Tigers", "LSU", "SEC"),
  team("Mississippi State", "Bulldogs", "MSST", "SEC"),
  team("Missouri", "Tigers", "MIZZ", "SEC"),
  team("Oklahoma", "Sooners", "OU", "SEC"),
  team("Ole Miss", "Rebels", "MISS", "SEC"),
  team("South Carolina", "Gamecocks", "SC", "SEC"),
  team("Tennessee", "Volunteers", "TENN", "SEC"),
  team("Texas", "Longhorns", "TEX", "SEC"),
  team("Texas A&M", "Aggies", "TAMU", "SEC"),
  team("Vanderbilt", "Commodores", "VAN", "SEC"),

  team("Appalachian State", "Mountaineers", "APP", "Sun Belt"),
  team("Arkansas State", "Red Wolves", "ARST", "Sun Belt"),
  team("Coastal Carolina", "Chanticleers", "CCU", "Sun Belt"),
  team("Georgia Southern", "Eagles", "GASO", "Sun Belt"),
  team("Georgia State", "Panthers", "GAST", "Sun Belt"),
  team("James Madison", "Dukes", "JMU", "Sun Belt"),
  team("Louisiana", "Ragin' Cajuns", "ULL", "Sun Belt"),
  team("Marshall", "Thundering Herd", "MRSH", "Sun Belt"),
  team("Old Dominion", "Monarchs", "ODU", "Sun Belt"),
  team("South Alabama", "Jaguars", "USA", "Sun Belt"),
  team("Southern Miss", "Golden Eagles", "USM", "Sun Belt"),
  team("Texas State", "Bobcats", "TXST", "Sun Belt"),
  team("Troy", "Trojans", "TROY", "Sun Belt"),
  team("ULM", "Warhawks", "ULM", "Sun Belt"),

  team("Notre Dame", "Fighting Irish", "ND", "Independents"),
  team("UConn", "Huskies", "UCONN", "Independents"),
];
