export type CfbTeamOption = {
  name: string;
  abbreviation: string;
  conference: string;
  division: string;
};

function team(name: string, abbreviation: string, conference: string): CfbTeamOption {
  return { name, abbreviation, conference, division: "Teams" };
}

export const CFB_27_TEAMS: CfbTeamOption[] = [
  team("Illinois", "ILL", "Big Ten"),
  team("Indiana", "IND", "Big Ten"),
  team("Iowa", "IOWA", "Big Ten"),
  team("Maryland", "MD", "Big Ten"),
  team("Michigan", "MICH", "Big Ten"),
  team("Michigan State", "MSU", "Big Ten"),
  team("Minnesota", "MINN", "Big Ten"),
  team("Nebraska", "NEB", "Big Ten"),
  team("Northwestern", "NW", "Big Ten"),
  team("Ohio State", "OSU", "Big Ten"),
  team("Penn State", "PSU", "Big Ten"),
  team("Purdue", "PUR", "Big Ten"),
  team("Rutgers", "RUT", "Big Ten"),
  team("UCLA", "UCLA", "Big Ten"),
  team("USC", "USC", "Big Ten"),
  team("Washington", "WASH", "Big Ten"),
  team("Wisconsin", "WIS", "Big Ten"),
  team("Oregon", "ORE", "Big Ten"),

  team("Alabama", "ALA", "SEC"),
  team("Arkansas", "ARK", "SEC"),
  team("Auburn", "AUB", "SEC"),
  team("Florida", "FLA", "SEC"),
  team("Georgia", "UGA", "SEC"),
  team("Kentucky", "UK", "SEC"),
  team("LSU", "LSU", "SEC"),
  team("Mississippi State", "MSST", "SEC"),
  team("Missouri", "MIZZ", "SEC"),
  team("Oklahoma", "OU", "SEC"),
  team("South Carolina", "SC", "SEC"),
  team("Tennessee", "TENN", "SEC"),
  team("Texas", "TEX", "SEC"),
  team("Texas A&M", "TAMU", "SEC"),
  team("Vanderbilt", "VAN", "SEC"),
  team("Ole Miss", "MISS", "SEC"),

  team("Arizona", "ARIZ", "Big 12"),
  team("Arizona State", "ASU", "Big 12"),
  team("Baylor", "BAY", "Big 12"),
  team("BYU", "BYU", "Big 12"),
  team("UCF", "UCF", "Big 12"),
  team("Cincinnati", "CIN", "Big 12"),
  team("Colorado", "COLO", "Big 12"),
  team("Houston", "HOU", "Big 12"),
  team("Iowa State", "ISU", "Big 12"),
  team("Kansas", "KU", "Big 12"),
  team("Kansas State", "KSU", "Big 12"),
  team("Oklahoma State", "OKST", "Big 12"),
  team("TCU", "TCU", "Big 12"),
  team("Texas Tech", "TTU", "Big 12"),
  team("Utah", "UTAH", "Big 12"),
  team("West Virginia", "WVU", "Big 12"),

  team("Boston College", "BC", "ACC"),
  team("California", "CAL", "ACC"),
  team("Clemson", "CLEM", "ACC"),
  team("Duke", "DUKE", "ACC"),
  team("Florida State", "FSU", "ACC"),
  team("Georgia Tech", "GT", "ACC"),
  team("Louisville", "LOU", "ACC"),
  team("Miami", "MIA", "ACC"),
  team("North Carolina", "UNC", "ACC"),
  team("NC State", "NCST", "ACC"),
  team("Pitt", "PITT", "ACC"),
  team("SMU", "SMU", "ACC"),
  team("Stanford", "STAN", "ACC"),
  team("Syracuse", "SYR", "ACC"),
  team("Virginia", "UVA", "ACC"),
  team("Virginia Tech", "VT", "ACC"),
  team("Wake Forest", "WAKE", "ACC"),

  team("Oregon State", "ORST", "Pac-12"),
  team("Washington State", "WSU", "Pac-12"),

  team("Boise State", "BOIS", "Mountain West"),
  team("Colorado State", "CSU", "Mountain West"),
  team("Fresno State", "FRES", "Mountain West"),
  team("Hawai'i", "HAW", "Mountain West"),
  team("Nevada", "NEV", "Mountain West"),
  team("New Mexico", "UNM", "Mountain West"),
  team("San Diego State", "SDSU", "Mountain West"),
  team("UNLV", "UNLV", "Mountain West"),
  team("Utah State", "USU", "Mountain West"),
  team("Air Force", "AFA", "Mountain West"),
  team("Wyoming", "WYO", "Mountain West"),
  team("San Jose State", "SJSU", "Mountain West"),

  team("Appalachian State", "APP", "Sun Belt"),
  team("Coastal Carolina", "CCU", "Sun Belt"),
  team("Georgia Southern", "GASO", "Sun Belt"),
  team("James Madison", "JMU", "Sun Belt"),
  team("Louisiana", "ULL", "Sun Belt"),
  team("Marshall", "MRSH", "Sun Belt"),
  team("Old Dominion", "ODU", "Sun Belt"),
  team("Southern Miss", "USM", "Sun Belt"),
  team("Texas State", "TXST", "Sun Belt"),
  team("Troy", "TROY", "Sun Belt"),
  team("UL Monroe", "ULM", "Sun Belt"),
  team("South Alabama", "USA", "Sun Belt"),
  team("Arkansas State", "ARST", "Sun Belt"),
  team("Georgia State", "GAST", "Sun Belt"),

  team("Ball State", "BALL", "MAC"),
  team("Bowling Green", "BGSU", "MAC"),
  team("Buffalo", "BUFF", "MAC"),
  team("Central Michigan", "CMU", "MAC"),
  team("Eastern Michigan", "EMU", "MAC"),
  team("Kent State", "KENT", "MAC"),
  team("Miami (OH)", "MOH", "MAC"),
  team("Northern Illinois", "NIU", "MAC"),
  team("Ohio", "OHIO", "MAC"),
  team("Toledo", "TOL", "MAC"),
  team("Western Michigan", "WMU", "MAC"),
  team("Akron", "AKR", "MAC"),

  team("Liberty", "LIB", "Conference USA"),
  team("Middle Tennessee", "MTSU", "Conference USA"),
  team("New Mexico State", "NMSU", "Conference USA"),
  team("Sam Houston", "SHSU", "Conference USA"),
  team("UTEP", "UTEP", "Conference USA"),
  team("Western Kentucky", "WKU", "Conference USA"),
  team("FIU", "FIU", "Conference USA"),
  team("Kennesaw State", "KENN", "Conference USA"),
  team("Louisiana Tech", "LT", "Conference USA"),
  team("Missouri State", "MOST", "Conference USA"),
  team("Jacksonville State", "JVST", "Conference USA"),
  team("Delaware", "DEL", "Conference USA"),

  team("Charlotte", "CLT", "American"),
  team("East Carolina", "ECU", "American"),
  team("Memphis", "MEM", "American"),
  team("Navy", "NAVY", "American"),
  team("North Texas", "UNT", "American"),
  team("Rice", "RICE", "American"),
  team("South Florida", "USF", "American"),
  team("Temple", "TEMP", "American"),
  team("Tulane", "TULN", "American"),
  team("UAB", "UAB", "American"),
  team("Tulsa", "TLSA", "American"),

  team("Alcorn State", "ALCN", "FCS (Non-D1)"),
  team("Eastern Kentucky", "EKU", "FCS (Non-D1)"),
  team("Idaho", "IDHO", "FCS (Non-D1)"),
  team("Indiana State", "INST", "FCS (Non-D1)"),
  team("Lamar", "LAM", "FCS (Non-D1)"),
  team("Maine", "ME", "FCS (Non-D1)"),
  team("Merrimack", "MRCK", "FCS (Non-D1)"),
  team("Montana", "MONT", "FCS (Non-D1)"),
  team("Northern Arizona", "NAU", "FCS (Non-D1)"),
  team("North Dakota", "UND", "FCS (Non-D1)"),
  team("Prairie View A&M", "PVAM", "FCS (Non-D1)"),
  team("Richmond", "RICH", "FCS (Non-D1)"),
  team("Sacramento State", "SAC", "FCS (Non-D1)"),
  team("South Dakota", "SDAK", "FCS (Non-D1)"),
  team("South Dakota State", "SDAKST", "FCS (Non-D1)"),
  team("Stephen F. Austin", "SFA", "FCS (Non-D1)"),
  team("Tarleton State", "TARL", "FCS (Non-D1)"),
  team("UC Davis", "UCD", "FCS (Non-D1)"),
  team("Weber State", "WEB", "FCS (Non-D1)"),
  team("Villanova", "NOVA", "FCS (Non-D1)"),
  team("Wofford", "WOF", "FCS (Non-D1)"),
  team("Youngstown State", "YSU", "FCS (Non-D1)"),
];
