export type NflConference = "AFC" | "NFC";
export type NflTeamOption = { name: string; abbreviation: string; conference: NflConference; division: string };
export const AFC_TEAMS: NflTeamOption[] = [
 {name:"Baltimore Ravens",abbreviation:"BAL",conference:"AFC",division:"North"},{name:"Buffalo Bills",abbreviation:"BUF",conference:"AFC",division:"East"},{name:"Cincinnati Bengals",abbreviation:"CIN",conference:"AFC",division:"North"},{name:"Cleveland Browns",abbreviation:"CLE",conference:"AFC",division:"North"},{name:"Denver Broncos",abbreviation:"DEN",conference:"AFC",division:"West"},{name:"Houston Texans",abbreviation:"HOU",conference:"AFC",division:"South"},{name:"Indianapolis Colts",abbreviation:"IND",conference:"AFC",division:"South"},{name:"Jacksonville Jaguars",abbreviation:"JAX",conference:"AFC",division:"South"},{name:"Kansas City Chiefs",abbreviation:"KC",conference:"AFC",division:"West"},{name:"Las Vegas Raiders",abbreviation:"LV",conference:"AFC",division:"West"},{name:"Los Angeles Chargers",abbreviation:"LAC",conference:"AFC",division:"West"},{name:"Miami Dolphins",abbreviation:"MIA",conference:"AFC",division:"East"},{name:"New England Patriots",abbreviation:"NE",conference:"AFC",division:"East"},{name:"New York Jets",abbreviation:"NYJ",conference:"AFC",division:"East"},{name:"Pittsburgh Steelers",abbreviation:"PIT",conference:"AFC",division:"North"},{name:"Tennessee Titans",abbreviation:"TEN",conference:"AFC",division:"South"}
];
export const NFC_TEAMS: NflTeamOption[] = [
 {name:"Arizona Cardinals",abbreviation:"ARI",conference:"NFC",division:"West"},{name:"Atlanta Falcons",abbreviation:"ATL",conference:"NFC",division:"South"},{name:"Carolina Panthers",abbreviation:"CAR",conference:"NFC",division:"South"},{name:"Chicago Bears",abbreviation:"CHI",conference:"NFC",division:"North"},{name:"Dallas Cowboys",abbreviation:"DAL",conference:"NFC",division:"East"},{name:"Detroit Lions",abbreviation:"DET",conference:"NFC",division:"North"},{name:"Green Bay Packers",abbreviation:"GB",conference:"NFC",division:"North"},{name:"Los Angeles Rams",abbreviation:"LAR",conference:"NFC",division:"West"},{name:"Minnesota Vikings",abbreviation:"MIN",conference:"NFC",division:"North"},{name:"New Orleans Saints",abbreviation:"NO",conference:"NFC",division:"South"},{name:"New York Giants",abbreviation:"NYG",conference:"NFC",division:"East"},{name:"Philadelphia Eagles",abbreviation:"PHI",conference:"NFC",division:"East"},{name:"San Francisco 49ers",abbreviation:"SF",conference:"NFC",division:"West"},{name:"Seattle Seahawks",abbreviation:"SEA",conference:"NFC",division:"West"},{name:"Tampa Bay Buccaneers",abbreviation:"TB",conference:"NFC",division:"South"},{name:"Washington Commanders",abbreviation:"WAS",conference:"NFC",division:"East"}
];
export const NFL_TEAMS = [...AFC_TEAMS, ...NFC_TEAMS];
export function getTeamByAbbreviation(abbreviation: string) { return NFL_TEAMS.find(t => t.abbreviation === abbreviation); }
