import type { FastifyInstance } from "fastify";
import { webSessionRoutes } from "./modules/web-session/web-session.routes.js";
import { adminEconomyRoutes } from "./modules/admin-economy/admin-economy.routes.js";
import { activeCheckRoutes } from "./modules/active-checks/active-checks.routes.js";
import { boxScoreRoutes } from "./modules/box-score/box-score.routes.js";
import { commissionerChatRoutes } from "./modules/commissioner-chat/commissioner-chat.routes.js";
import { gameChannelRoutes } from "./modules/game-channels/game-channels.routes.js";
import { highlightRoutes } from "./modules/highlights/highlights.routes.js";
import { gotwRoutes } from "./modules/gotw/gotw.routes.js";
import { legendRoutes } from "./modules/legends/legends.routes.js";
import { leagueContextRoutes } from "./modules/league-context/league-context.routes.js";
import { notificationsRoutes } from "./modules/notifications/notifications.routes.js";
import { purchaseRoutes } from "./modules/purchases/purchases.routes.js";
import { leagueWeekRoutes } from "./modules/league-week/league-week.routes.js";
import { rolesRoutes } from "./modules/roles/roles.routes.js";
import { rosterRoutes } from "./modules/rosters/rosters.routes.js";
import { scheduleRoutes } from "./modules/schedule/schedule.routes.js";
import { serverConfigRoutes } from "./modules/server-config/server-config.routes.js";
import { setupRoutes } from "./modules/setup/setup.routes.js";
import { streamRoutes } from "./modules/streams/streams.routes.js";
import { teamOwnershipRoutes } from "./modules/team-ownership/team-ownership.routes.js";
import { teamRequestRoutes } from "./modules/team-requests/team-requests.routes.js";
import { userRoutes } from "./modules/users/user.routes.js";
import { wagerRoutes } from "./modules/wagers/wagers.routes.js";
import { hubRoutes } from "./modules/hub/hub.routes.js";
import { watchedPlayersRoutes } from "./modules/watched-players/watched-players.routes.js";
import { recruitingRoutes } from "./modules/recruiting/recruiting.routes.js";
import { transferPortalRoutes } from "./modules/transfer-portal/transfer-portal.routes.js";
import { submissionStateRoutes } from "./modules/submission-state/submission-state.routes.js";
import { siteAuthRoutes } from "./modules/site-auth/site-auth.routes.js";
import { siteFriendsRoutes } from "./modules/site-friends/site-friends.routes.js";
import { siteInboxRoutes } from "./modules/site-inbox/site-inbox.routes.js";
import { siteLeaguesRoutes } from "./modules/site-leagues/site-leagues.routes.js";
import { siteNotificationsRoutes } from "./modules/site-notifications/site-notifications.routes.js";

export async function registerRoutes(app: FastifyInstance) {
  app.get("/health", async () => ({ ok: true, service: "rec-core-api" }));

  await webSessionRoutes(app);
  await userRoutes(app);
  await adminEconomyRoutes(app);
  await activeCheckRoutes(app);
  await setupRoutes(app);
  await teamOwnershipRoutes(app);
  await teamRequestRoutes(app);
  await rosterRoutes(app);
  await leagueContextRoutes(app);
  await scheduleRoutes(app);
  await gameChannelRoutes(app);
  await serverConfigRoutes(app);
  await leagueWeekRoutes(app);
  await streamRoutes(app);
  await boxScoreRoutes(app);
  await commissionerChatRoutes(app);
  await highlightRoutes(app);
  await gotwRoutes(app);
  await legendRoutes(app);
  await notificationsRoutes(app);
  await purchaseRoutes(app);
  await rolesRoutes(app);
  await wagerRoutes(app);
  await hubRoutes(app);
  await watchedPlayersRoutes(app);
  await recruitingRoutes(app);
  await transferPortalRoutes(app);
  await submissionStateRoutes(app);
  await siteAuthRoutes(app);
  await siteFriendsRoutes(app);
  await siteInboxRoutes(app);
  await siteLeaguesRoutes(app);
  await siteNotificationsRoutes(app);
}
