import type { FastifyInstance } from "fastify";
import { webSessionRoutes } from "./modules/web-session/web-session.routes.js";
import { adminEconomyRoutes } from "./modules/admin-economy/admin-economy.routes.js";
import { adminRoutes } from "./modules/admin/admin.routes.js";
import { promoCodeRoutes } from "./modules/promo-codes/promo-codes.routes.js";
import { rankingsRoutes } from "./modules/rankings/rankings.routes.js";
import { compRoutes } from "./modules/comp/comp.routes.js";
import { moderationRoutes } from "./modules/moderation/moderation.routes.js";
import { activeCheckRoutes } from "./modules/active-checks/active-checks.routes.js";
import { boxScoreRoutes } from "./modules/box-score/box-score.routes.js";
import { commissionerChatRoutes } from "./modules/commissioner-chat/commissioner-chat.routes.js";
import { leagueChatRoutes } from "./modules/league-chat/league-chat.routes.js";
import { gameChatRoutes } from "./modules/game-chat/game-chat.routes.js";
import { chatRoutes } from "./modules/chat/chat.routes.js";
import { chatRealtimeRoutes } from "./modules/chat/chat-realtime.routes.js";
import { devAuthRoutes } from "./modules/dev/dev-auth.routes.js";
import { matchupHelpRoutes } from "./modules/matchup-help/matchup-help.routes.js";
import { gameChannelRoutes } from "./modules/game-channels/game-channels.routes.js";
import { heismanRoutes } from "./modules/heisman/heisman.routes.js";
import { highlightRoutes } from "./modules/highlights/highlights.routes.js";
import { gotwRoutes } from "./modules/gotw/gotw.routes.js";
import { legendRoutes } from "./modules/legends/legends.routes.js";
import { leagueContextRoutes } from "./modules/league-context/league-context.routes.js";
import { notificationsRoutes } from "./modules/notifications/notifications.routes.js";
import { purchaseRoutes } from "./modules/purchases/purchases.routes.js";
import { customPlayerRoutes } from "./modules/custom-players/custom-players.routes.js";
import { leagueWeekRoutes } from "./modules/league-week/league-week.routes.js";
import { rolesRoutes } from "./modules/roles/roles.routes.js";
import { leagueConferenceRoutes } from "./modules/league-conferences/league-conferences.routes.js";
import { scheduleRoutes } from "./modules/schedule/schedule.routes.js";
import { serverConfigRoutes } from "./modules/server-config/server-config.routes.js";
import { setupRoutes } from "./modules/setup/setup.routes.js";
import { streamRoutes } from "./modules/streams/streams.routes.js";
import { teamOwnershipRoutes } from "./modules/team-ownership/team-ownership.routes.js";
import { teamRequestRoutes } from "./modules/team-requests/team-requests.routes.js";
import { recruitingBoardRoutes } from "./modules/recruiting-board/recruiting-board.routes.js";
import { demoLeagueRoutes } from "./modules/demo-league/demo-league.routes.js";
import { userRoutes } from "./modules/users/user.routes.js";
import { wagerRoutes } from "./modules/wagers/wagers.routes.js";
import { teamRosterRoutes } from "./modules/roster/roster.routes.js";
import { hubRoutes } from "./modules/hub/hub.routes.js";
import { watchedPlayersRoutes } from "./modules/watched-players/watched-players.routes.js";
import { recruitingRoutes } from "./modules/recruiting/recruiting.routes.js";
import { transferPortalRoutes } from "./modules/transfer-portal/transfer-portal.routes.js";
import { cfbBaselineRoutes } from "./modules/cfb-baseline/cfb-baseline.routes.js";
import { maddenCompanionRoutes } from "./modules/madden-companion/madden-companion.routes.js";
import { maddenEaRoutes } from "./modules/madden-ea/madden-ea.routes.js";
import { leagueStatsRoutes } from "./modules/league-stats/league-stats.routes.js";
import { submissionStateRoutes } from "./modules/submission-state/submission-state.routes.js";
import { siteAuthRoutes } from "./modules/site-auth/site-auth.routes.js";
import { subscriptionRoutes } from "./modules/subscriptions/subscriptions.routes.js";
import { siteFriendsRoutes } from "./modules/site-friends/site-friends.routes.js";
import { siteInboxRoutes } from "./modules/site-inbox/site-inbox.routes.js";
import { siteLeaguesRoutes } from "./modules/site-leagues/site-leagues.routes.js";
import { siteLeagueInvitesRoutes } from "./modules/site-league-invites/site-league-invites.routes.js";
import { siteNotificationsRoutes } from "./modules/site-notifications/site-notifications.routes.js";
import { mediaRoutes } from "./modules/media/media.routes.js";
import { siteHighlightsRoutes } from "./modules/site-highlights/site-highlights.routes.js";
import { siteHomeRoutes } from "./modules/site-home/site-home.routes.js";
import { pushRoutes } from "./modules/push/push.routes.js";
import { pollsRoutes } from "./modules/polls/polls.routes.js";
import { draftPicksRoutes } from "./modules/draft-picks/draft-picks.routes.js";
import { tradesRoutes } from "./modules/trades/trades.routes.js";
import { fantasyDraftRoutes } from "./modules/fantasy-draft/fantasy-draft.routes.js";
import { publicLeagueRoutes } from "./modules/public-league/public-league.routes.js";

export async function registerRoutes(app: FastifyInstance) {
  app.get("/health", async () => ({ ok: true, service: "rec-core-api" }));

  await webSessionRoutes(app);
  await userRoutes(app);
  await adminEconomyRoutes(app);
  await activeCheckRoutes(app);
  await setupRoutes(app);
  await teamOwnershipRoutes(app);
  await teamRequestRoutes(app);
  await recruitingBoardRoutes(app);
  await demoLeagueRoutes(app);
  await leagueConferenceRoutes(app);
  await leagueContextRoutes(app);
  await scheduleRoutes(app);
  await gameChannelRoutes(app);
  await heismanRoutes(app);
  await serverConfigRoutes(app);
  await leagueWeekRoutes(app);
  await streamRoutes(app);
  await boxScoreRoutes(app);
  await commissionerChatRoutes(app);
  await leagueChatRoutes(app);
  await gameChatRoutes(app);
  await chatRoutes(app);
  await chatRealtimeRoutes(app);
  await devAuthRoutes(app);
  await matchupHelpRoutes(app);
  await highlightRoutes(app);
  await mediaRoutes(app);
  await gotwRoutes(app);
  await legendRoutes(app);
  await notificationsRoutes(app);
  await purchaseRoutes(app);
  await customPlayerRoutes(app);
  await rolesRoutes(app);
  await wagerRoutes(app);
  await teamRosterRoutes(app);
  await hubRoutes(app);
  await watchedPlayersRoutes(app);
  await recruitingRoutes(app);
  await transferPortalRoutes(app);
  await cfbBaselineRoutes(app);
  await maddenCompanionRoutes(app);
  await maddenEaRoutes(app);
  await leagueStatsRoutes(app);
  await submissionStateRoutes(app);
  await siteAuthRoutes(app);
  await subscriptionRoutes(app);
  await siteFriendsRoutes(app);
  await siteInboxRoutes(app);
  await siteLeaguesRoutes(app);
  await siteLeagueInvitesRoutes(app);
  await siteNotificationsRoutes(app);
  await siteHighlightsRoutes(app);
  await siteHomeRoutes(app);
  await pushRoutes(app);
  await pollsRoutes(app);
  await draftPicksRoutes(app);
  await tradesRoutes(app);
  await fantasyDraftRoutes(app);
  await publicLeagueRoutes(app);
  await adminRoutes(app);
  await promoCodeRoutes(app);
  await rankingsRoutes(app);
  await compRoutes(app);
  await moderationRoutes(app);
}
