// Non-RTI Media Day question bank. Replaces the old free-text "Submit an Interview" flow
// (10 topics x 6 questions, commissioner-approved) with a structured, auto-paid weekly
// interview modeled on RTI's Media Day / Owner Interview systems -- see selection.ts for how
// a team's 3 weekly questions are picked from here based on season stage and recent context.
//
// Every question here is answered by the USER as the coach/owner of their TEAM (non-RTI leagues
// have no player-prospect entities), so the whole bank is inherently "team-level" -- the
// team_identity/roster_construction/coaching_philosophy categories below are the always-available
// evergreen core, and every other category layers season-stage or recent-result context on top.

export type NonRtiMediaDayCategory =
  | "team_identity"
  | "roster_construction"
  | "coaching_philosophy"
  | "preseason"
  | "regular_season_early"
  | "regular_season_mid"
  | "regular_season_late"
  | "postgame_win"
  | "postgame_loss"
  | "game_of_the_week"
  | "postseason"
  | "championship"
  | "offseason_madden"
  | "offseason_cfb";

const RAW_QUESTIONS: Record<NonRtiMediaDayCategory, string[]> = {
  team_identity: [
    "How would you describe your program's identity in one sentence?",
    "What's the one word your team's ownership meeting would use to describe this roster?",
    "What does this team do better than anyone else in the league right now?",
    "If a new fan watched one game of yours, what would you want them to see first?",
    "What's the identity trait you've had to build into this roster the hard way?",
    "Is this team built to win now, or built for what's coming next?",
    "What part of your team's reputation around the league do you actually agree with?",
    "What's the biggest misconception other coaches have about your program?",
    "When this team is at its best, what does that look like on tape?",
    "What's a strength of your program that doesn't show up in the box score?",
    "How has your program's identity changed since you took over?",
    "What's non-negotiable about how your team plays, no matter the opponent?",
    "If your team had a slogan this season, what would it be?",
    "What does your locker room believe about this team that outsiders don't?",
    "Where does your program's toughness actually come from?",
    "What's the standard you've set that this roster is chasing?",
    "How do you want this era of your program to be remembered?",
    "What's one habit this team has built that you're proud of?",
    "Does this roster reflect who you are as a coach, or who you're trying to become?",
    "What part of your team's identity took the longest to build?",
    "What separates a good week for this program from a great one?",
    "How do you keep your team's identity consistent through a long season?",
    "What's the trait this roster has that you can't coach — it just is what it is?",
    "If your team disappeared tomorrow, what would the league miss most about how you play?",
    "What does accountability look like inside your program?",
    "How much of your team's identity is your doing versus the players in that locker room?",
    "What's a game from this season that captured exactly who your team is?",
    "How do you want opposing coaches to describe your program after they play you?",
    "What part of your program's culture would you never change, even to win more?",
    "What's the difference between how your team sees itself and how the league sees it?",
  ],
  roster_construction: [
    "What's the biggest strength of the roster you've built?",
    "Which position group are you proudest of building?",
    "What's a roster gap you're still trying to solve?",
    "How do you balance building for this season versus building for the future?",
    "What's the most underrated piece of your roster right now?",
    "If you could add one more piece to this roster, what would it be?",
    "What's a roster decision that's paid off bigger than you expected?",
    "How do you evaluate whether a player fits your program, beyond the raw talent?",
    "What's harder — finding talent or finding the right fit for your system?",
    "Which unit on your roster has grown the most this season?",
    "What's a roster need you're prioritizing heading into the next window?",
    "How do you decide when it's time to move on from a player?",
    "What's the deepest position group on your roster right now?",
    "How much do you value experience versus upside when building this roster?",
    "What's a roster philosophy you've stuck with even when it was questioned?",
    "Which young player on your roster is closest to a breakout?",
    "What's the hardest roster decision you've had to make this year?",
    "How do you build competition at a position without disrupting chemistry?",
    "What's a trait you look for in every player you bring into this program?",
    "How close is this roster to being exactly what you want it to be?",
    "What's one thing about roster building that fans underestimate?",
    "How do you build depth at a position that's historically been thin for you?",
    "What's the clearest example of your team identity showing up in a personnel decision?",
    "How do you handle a roster spot that isn't performing the way you hoped?",
    "What's the biggest roster swing you've made and how did it play out?",
    "How do you decide which positions to invest the most resources into?",
    "What's a roster weakness you're not hiding from right now?",
    "How do you keep your roster's culture intact when the roster keeps changing?",
    "What's the timeline for this roster to be a true contender?",
    "If you had to rebuild one position group from scratch, which would it be?",
  ],
  coaching_philosophy: [
    "What's the coaching philosophy you lean on more than anything else?",
    "How do you build a locker room culture that outlasts any single season?",
    "What's the toughest coaching adjustment you've made this year?",
    "How do you personally handle the pressure of the job week to week?",
    "What's a coaching lesson this season has taught you?",
    "How do you keep a team accountable without losing them?",
    "What's the coaching principle you'd never compromise on?",
    "How do you adjust your approach for a team that's struggling to buy in?",
    "What's the difference between coaching talent and coaching a team?",
    "How do you handle a locker room after a tough loss?",
    "What's a piece of coaching advice that's stuck with you?",
    "How do you balance discipline with keeping the room loose?",
    "What's the hardest part of leading this program right now?",
    "How do you get buy-in from players who came up in a different system?",
    "What's a coaching decision you'd make differently if you could?",
    "How do you measure success beyond just wins and losses?",
    "What's the biggest challenge in keeping a team's edge over a long season?",
    "How do you coach a team through adversity without losing the room?",
    "What's something about leading this program you didn't expect coming in?",
    "How do you want your players to describe you once they've moved on?",
    "What's the coaching trait that's mattered most this season?",
    "How do you keep yourself sharp as a coach week to week?",
    "What's the version of success that would actually satisfy you this year?",
    "How much of coaching is scheme, and how much is just people?",
    "What's a mistake you've learned the most from as a coach this season?",
    "How do you keep perspective when the results aren't going your way?",
    "What's the legacy you want this coaching stint to leave behind?",
    "How do you handle a team that's dealing with outside noise?",
    "What's the one thing you'd want every player in this program to carry with them?",
    "How has this season changed the kind of coach you are?",
  ],
  preseason: [
    "What's the biggest question your team has to answer before the season opener?",
    "What's the most encouraging thing you've seen from this roster so far?",
    "Which position battle are you watching closest right now?",
    "What's the one thing this team has to fix before Week 1?",
    "How do you want this team to be playing by the time the season actually matters?",
    "What's the expectation you're setting for this roster this year?",
    "Which new addition do you expect to make the biggest impact right away?",
    "What's the identity you're trying to establish before the games start counting?",
    "How different does this roster look compared to a year ago?",
    "What's the biggest strength you're building camp around?",
    "Which unit needs the most work heading into the season?",
    "What would you consider a successful start to this season?",
    "How do you evaluate a roster that hasn't played a real game yet?",
    "What's the standard you're setting in camp for how hard this team competes?",
    "Which returning player are you counting on to take a leap this year?",
    "What's the depth chart battle you're most curious to see resolved?",
    "How do you build chemistry with a roster that's still coming together?",
    "What's the message you're sending your team heading into the opener?",
    "How much of this roster's ceiling is still unknown to you?",
    "What's the biggest change you made to this program in the offseason?",
    "How do you want your team to be talked about once the season kicks off?",
    "What's the trait you need most from your leaders heading into Week 1?",
    "Which matchup on your early schedule worries you most?",
    "What's one thing you learned about this roster that surprised you?",
    "How do you set realistic expectations without capping this team's ceiling?",
    "What's the biggest thing standing between this team and a fast start?",
    "How do you want your team to respond to adversity before it's even happened?",
    "What's the one number — wins, stats, anything — you're chasing this season?",
    "How do you know when a young player is actually ready for real minutes?",
    "What are you most excited for the league to see from this program this year?",
  ],
  regular_season_early: [
    "What has the start of this season told you about your team that camp didn't?",
    "What's the biggest surprise, good or bad, from these opening weeks?",
    "How accurate did your preseason expectations turn out to be so far?",
    "What's the identity this team has shown in these first few games?",
    "Which player has separated themselves early that you didn't expect?",
    "What's the first thing you'd fix if you could rewind these opening weeks?",
    "How is your team handling adversity this early in the season?",
    "What's the biggest difference between this team's start and last year's?",
    "Which part of your gameplan has translated best to real games so far?",
    "What's a trend from these first few weeks that concerns you?",
    "How settled does your starting lineup feel at this point in the season?",
    "What's the toughest opponent you've faced so far, and what did it teach you?",
    "How do you keep the locker room even-keeled through an early hot or cold stretch?",
    "What's a strength that's shown up more than you expected early on?",
    "Which position group has grown the most since Week 1?",
    "What's the standard you're holding this team to as the schedule ramps up?",
    "How much stock do you put in these early results?",
    "What's the biggest adjustment you've made to the gameplan already this season?",
    "Which game from these opening weeks says the most about who your team is?",
    "What's a weakness these early games have exposed?",
    "How do you want your team to build off this start?",
    "What's the mindset heading into the next stretch of the schedule?",
    "How is your team's health looking after these opening weeks?",
    "What's the biggest thing you need to see improve going forward?",
    "Which young player has earned more trust than they had entering the season?",
    "What's a moment from these first few weeks that changed how you see this roster?",
    "How do you evaluate whether your gameplan is actually working this early?",
    "What's the biggest challenge on the schedule still ahead of you?",
    "How do you keep a fast start from going to your team's head?",
    "How do you keep a slow start from breaking your team's confidence?",
    "What's the tone you're setting in the building right now?",
    "Which unit needs to take the next step for this team to be dangerous?",
    "What does this team need to prove over its next few games?",
    "What's a rotation change that's already changed how your team plays?",
    "How do you handle a fanbase reacting to a hot or cold start?",
  ],
  regular_season_mid: [
    "Where does this team's record match — or not match — how you feel about it?",
    "What's the biggest thing that's changed about your team since the season began?",
    "How has your role as a coach shifted as the season has gone on?",
    "What's the identity this team has settled into by the midpoint?",
    "Which player has taken the biggest step forward since the opener?",
    "What's a midseason adjustment you've made that's paying off?",
    "How healthy is this roster right now, and how much does that worry you?",
    "What's the biggest thing separating your team from the top of the standings?",
    "How do you keep a team locked in through the middle stretch of a long season?",
    "What's a trend the numbers are showing that you actually agree with?",
    "Which game from this stretch will you point back to later in the season?",
    "What's the biggest thing your team has to fix before the stretch run?",
    "How much has your gameplan evolved since Week 1?",
    "What's a strength that's carried this team through the middle of the season?",
    "Which opponent coming up worries you the most right now?",
    "What's the tone in the locker room at the midpoint of this season?",
    "How do you manage a roster that's dealing with midseason fatigue?",
    "What's a position battle that's still unresolved this deep into the season?",
    "How close is this team to playing its best football?",
    "What's the biggest lesson this season has taught you so far?",
    "How do you keep young players developing once the grind sets in?",
    "What's a matchup you're circling on the schedule ahead?",
    "How does this version of your team compare to where you expected to be?",
    "What's the standard you're demanding from your team down the stretch?",
    "Which unit has quietly become one of your best?",
    "What's the biggest thing your team needs to clean up on tape?",
    "How do you keep belief in the room if results haven't matched effort?",
    "What's a strength you want to lean on more in the second half?",
    "How do you handle a locker room that's dealing with outside noise at the midpoint?",
    "What's the one stat that best tells the story of your season so far?",
    "How much does the schedule ahead shape how you're coaching right now?",
    "What's a decision you made early in the season that you'd stand by again?",
    "How do you want this team playing by the time the stakes get real?",
    "What's the biggest challenge to staying consistent through a long season?",
    "Which player's midseason form has changed how you use them?",
  ],
  regular_season_late: [
    "How much does every game left on the schedule matter right now?",
    "What's the biggest thing standing between this team and the postseason?",
    "How do you keep your team from feeling the weight of a playoff race?",
    "What's the identity this team needs to lean on down the stretch?",
    "Which game left on the schedule feels the most like a must-win?",
    "How do you manage a roster that's banged up this late in the season?",
    "What's the standard you're holding your team to with the season on the line?",
    "How has the pressure of these final weeks changed how you're coaching?",
    "What's the biggest strength you're counting on to close the season strong?",
    "How do you keep a team from pressing too hard when the stakes rise?",
    "What's a weakness you have to hide or fix before the games matter most?",
    "How much do the standings around the league affect how you're preparing?",
    "What's the toughest team left on your schedule, and why?",
    "How do you want your team playing when it matters most?",
    "What's the biggest lesson from this season that's showing up right now?",
    "How do you handle a locker room that knows its season could end soon?",
    "What's a trait this team has shown that gives you confidence down the stretch?",
    "How close is your team to playing playoff-caliber football?",
    "What's the mindset heading into a game that could decide your season?",
    "How do you keep veterans and young players locked in at the same level right now?",
    "What's the biggest thing you need from your best players over these final weeks?",
    "How do you manage a team fighting for a spot versus a team that's locked in?",
    "What's changed about your gameplan as the stakes have gotten higher?",
    "How do you want the league to view your program if this stretch run defines the season?",
    "What's the one thing that has to go right for your team to make the postseason?",
    "How do you keep your team from looking past a game it should win?",
    "What's the biggest thing you've learned about this roster under pressure?",
    "How do you handle a team clinging to playoff hopes on a short leash?",
    "What's the standard for effort you're demanding with the season on the line?",
    "How do you prepare a team for a win-and-in scenario?",
    "What's the difference between this team in Week 1 and this team right now?",
    "How much does health factor into your outlook for these final weeks?",
    "What's a moment from this stretch that will define how this season is remembered?",
    "How do you keep belief alive in a room that's fighting for its season?",
    "What's the one thing you want people to know about how hard this team has fought?",
  ],
  postgame_win: [
    "What did your gameplan get right today?",
    "What was said in the locker room right after the final whistle?",
    "Which player stepped up the most in that win?",
    "What does this result say about the team you just beat?",
    "How much does this win change the way you see your team?",
    "What's the first thing you point to on film that made the difference?",
    "How did your team respond in the moments that mattered most?",
    "What's the story of this game that doesn't show up in the score?",
    "How do you want your team to build on this performance?",
    "What surprised you most about how your team played today?",
    "Which unit deserves the most credit for this win?",
    "What does this win say about your program's identity right now?",
    "How different did this team look compared to earlier in the season?",
    "What's the challenge in keeping this level of play consistent?",
    "How much of this win was gameplan versus your players just executing?",
    "What's the next step for a team that just played like that?",
    "How do you keep this win from feeling bigger than it actually was?",
    "What's a moment from that game you'll remember the longest?",
    "How did your team handle adversity during the game, if any came up?",
    "What's the message to the locker room after a performance like that?",
    "How does this result change your outlook on the rest of the schedule?",
    "What's something your team did today that it hadn't shown before?",
    "How do you evaluate a win like this — was it your best football, or just enough?",
    "What's the biggest thing you'll carry forward from this performance?",
    "How proud are you of how your team prepared for this one?",
    "What's the difference between a good win and a statement win, and which was this?",
    "How did your quarterback, or your best player, impact the outcome today?",
    "What's the mood in the building after a win like that?",
    "How do you make sure this win doesn't create complacency?",
    "What did this game confirm that you already believed about this team?",
  ],
  postgame_loss: [
    "What did your gameplan get wrong today?",
    "What was said in the locker room right after the final whistle?",
    "What's the first thing you fix on film this week?",
    "How much does this loss change the way you see your team?",
    "What did this result reveal about the team you just played?",
    "How did your team respond when things started going wrong?",
    "What's the story of this game that doesn't show up in the score?",
    "How do you keep this loss from turning into a bigger problem?",
    "What surprised you most about how your team played today?",
    "Which moment in that game do you keep coming back to?",
    "What does this loss say about where your program actually stands?",
    "How different did this team look compared to its best version this season?",
    "What's the challenge in bouncing back the right way from this?",
    "How much of this loss was gameplan versus your players not executing?",
    "What's the next step for a team that just played like that?",
    "How do you keep this loss from feeling bigger than it actually is?",
    "What's a moment from that game you wish you could take back?",
    "How did your team handle adversity during the game?",
    "What's the message to the locker room after a performance like that?",
    "How does this result change your outlook on the rest of the schedule?",
    "What's something your team showed today that concerns you going forward?",
    "How do you evaluate a loss like this — was effort the issue, or execution?",
    "What's the biggest thing you have to correct before the next game?",
    "How do you keep belief in the room after a result like that?",
    "What's the difference between a bad loss and one you can learn from, and which was this?",
    "How did injuries or missed opportunities factor into today's result?",
    "What's the mood in the building after a loss like that?",
    "How do you make sure one loss doesn't turn into a losing streak?",
    "What did this game reveal that you didn't already know about this team?",
    "How do you get your team refocused heading into next week?",
  ],
  game_of_the_week: [
    "What does it mean for this game to be picked as Game of the Week?",
    "How do you prepare differently, if at all, for a game with this much attention on it?",
    "What's the storyline outsiders are focused on that you don't think matters as much?",
    "How does your team feel about being in the spotlight this week?",
    "What's the one thing you want people watching this game to notice about your team?",
    "How much extra pressure does a marquee matchup like this add?",
    "What's your honest read on the team across the field this week?",
    "What does a win in a game with this much attention mean for your program?",
    "How do you keep your team from overhyping a game like this?",
    "What's the biggest key to winning a matchup everyone's watching?",
    "How does this matchup compare to other big games your program has played?",
    "What's the narrative around this game that you actually agree with?",
    "How do you want your team to be remembered after a spotlight game like this?",
    "What's the one matchup within the game you're most focused on?",
    "How much do your players talk about a game getting this kind of attention?",
    "What's the biggest thing that could decide a game like this?",
    "How do you make sure your gameplan isn't shaped by the hype around this game?",
    "What's it like coaching in a game the whole league is watching?",
    "How do you want this game to be talked about after it's over?",
    "What's the biggest difference between this opponent and a typical week?",
    "How does the extra attention on this game affect your preparation this week?",
    "What's your team's mindset heading into a game everyone expects to be close?",
    "How do you handle a team that gets nervous under a bigger spotlight?",
    "What's the one storyline you wish people were talking about instead?",
    "How much does a performance in a game like this shape your program's reputation?",
  ],
  postseason: [
    "What does it mean for this program to be playing in the postseason?",
    "How different is the preparation for a playoff game versus a regular season game?",
    "What's the biggest thing your team has to get right to keep advancing?",
    "How do you keep your team even-keeled with elimination on the line?",
    "What's the standard you're holding this team to now that every game matters most?",
    "How has this team grown since the start of the season to get to this point?",
    "What's the identity this team needs to lean on in the postseason?",
    "How do you manage nerves in a locker room that hasn't been here before?",
    "What's the biggest strength you're counting on in these playoff games?",
    "How do you prepare a team for the physicality of playoff football?",
    "What's a weakness you have to hide heading into the postseason?",
    "How much does experience matter once the games become win-or-go-home?",
    "What's the toughest matchup you could see on the road through the postseason?",
    "How do you want this team playing when the season is on the line every week?",
    "What's the biggest lesson from the regular season that applies right now?",
    "How do you keep your team focused on one game at a time in the playoffs?",
    "What's a moment from the postseason so far that's defined this run?",
    "How do you handle a team that's dealing with playoff pressure for the first time?",
    "What's the message to your locker room heading into an elimination game?",
    "How close is this team to playing its best football at the right time?",
    "What's the biggest thing you need from your best players in the postseason?",
    "How do you prepare for an opponent you haven't seen much of this season?",
    "What's the difference between a team that survives the postseason and one that doesn't?",
    "How do you keep belief alive in a locker room facing elimination?",
    "What's the standard for effort you're demanding in a win-or-go-home game?",
    "How do you want the league to remember this postseason run, win or lose?",
    "What's the biggest thing this team has proven by getting this far?",
    "How do you handle the emotional weight of a deep playoff run?",
    "What's a trait this team has shown in the postseason that gives you confidence?",
    "How do you keep your team hungry after already exceeding expectations?",
  ],
  championship: [
    "What does it mean for this program to be playing for a championship?",
    "How do you put into words what this moment means for your team?",
    "What's the biggest thing your team has to get right on the sport's biggest stage?",
    "How do you keep your team from feeling the weight of a championship game?",
    "What's the standard you're holding this team to with a title on the line?",
    "How has this team's journey shaped how you're approaching this game?",
    "What's the identity this team needs to lean on in a moment like this?",
    "How do you manage nerves in a locker room playing for it all?",
    "What's the biggest strength you're counting on in the championship?",
    "How do you prepare a team for the magnitude of a title game?",
    "What's a weakness you absolutely cannot show in a game like this?",
    "How much does this opportunity change how your program is viewed?",
    "What's the toughest challenge your opponent presents in this matchup?",
    "How do you want this team playing when everything is on the line?",
    "What's the biggest lesson this whole season has been building toward?",
    "How do you keep your team from trying to do too much in a moment like this?",
    "What's a moment from this run that's defined who your team is?",
    "How do you handle the emotional weight of playing for a championship?",
    "What's the legacy this team could leave with a win here?",
    "How do you want the league to remember this team, no matter what happens?",
  ],
  offseason_madden: [
    "What's the first priority for your program heading into the offseason?",
    "How do you evaluate the season that just ended?",
    "What's the biggest lesson from this year that shapes your offseason plan?",
    "Which position are you most focused on addressing this offseason?",
    "How do you approach free agency with your program's identity in mind?",
    "What's the toughest decision you're facing this offseason?",
    "How do you decide which of your own free agents to prioritize re-signing?",
    "What's a roster weakness this offseason has to fix?",
    "How much does cap space shape your approach to this offseason?",
    "What's your draft philosophy heading into this cycle?",
    "Which need are you hoping the draft solves for you?",
    "How do you balance re-signing your own guys versus chasing outside free agents?",
    "What's the biggest change you're planning for the coaching staff, if any?",
    "How do you decide when it's time to move on from a veteran player?",
    "What's the culture shift you're aiming for heading into next season?",
    "How do you evaluate which free agents actually fit your system?",
    "What's the riskiest move you're considering this offseason?",
    "How do you plan to use the draft to build for the future versus win now?",
    "What's the one position group you refuse to neglect this offseason?",
    "How do you approach re-signing a player who had a down year?",
    "What's the biggest thing you learned about roster building this past season?",
    "How aggressive do you plan to be in free agency this cycle?",
    "What's the identity you want your next draft class to reflect?",
    "How do you balance the locker room's expectations with the business of the offseason?",
    "What's the hardest goodbye you might have to make this offseason?",
    "How do you decide what type of player fills a leadership void?",
    "What's the biggest opportunity this offseason presents for your program?",
    "How do you approach the draft when you have needs at multiple positions?",
    "What's one thing you want fans to understand about this offseason's approach?",
    "How do you want this program to look different by the time next season starts?",
  ],
  offseason_cfb: [
    "How do you evaluate the season that just wrapped up?",
    "What's the biggest thing you learned about this program this year?",
    "How do you handle players leaving for the draft or graduating?",
    "What's the toughest goodbye your program is facing this offseason?",
    "How do you approach the transfer portal with your program's identity in mind?",
    "What's the biggest need the portal has to help you address?",
    "How do you decide which of your own players to fight to keep from transferring out?",
    "What's your recruiting philosophy heading into this signing class?",
    "Which position group are you most focused on through recruiting or the portal?",
    "How do you balance retaining your locker room's culture with adding new pieces?",
    "What's the biggest change you're planning heading into next season?",
    "How do you evaluate a transfer target beyond just their statistics?",
    "What's the riskiest roster move you're considering this offseason?",
    "How do you approach training and development during this part of the year?",
    "What's the identity you want your incoming class to reflect?",
    "How do you keep your current roster locked in while others are changing teams?",
    "What's the hardest part of the roster turnover this era of the sport brings?",
    "How do you decide what type of player fills a leadership void left behind?",
    "What's the biggest opportunity this offseason presents for your program?",
    "How aggressive are you being in the transfer portal this cycle?",
    "What's one thing you want fans to understand about this offseason's approach?",
    "How do you want this program to look different by next season?",
    "What's the biggest lesson about roster management this era has taught you?",
    "How do you evaluate whether training results are actually translating to progress?",
    "What's the plan for replacing production lost to departures?",
    "How do you approach signing day with your program's long-term vision in mind?",
    "What's the biggest thing this offseason has to accomplish before next season?",
    "How do you keep your program's culture intact through constant roster change?",
    "What's a signing or portal addition you're most excited about?",
    "How do you want this recruiting cycle to define your program's next chapter?",
  ],
};

export type NonRtiMediaDayQuestion = { id: string; category: NonRtiMediaDayCategory; text: string };

export const NON_RTI_MEDIA_DAY_QUESTIONS: NonRtiMediaDayQuestion[] = (
  Object.keys(RAW_QUESTIONS) as NonRtiMediaDayCategory[]
).flatMap((category) =>
  RAW_QUESTIONS[category].map((text, index) => ({ id: `${category}:${index + 1}`, category, text })),
);

export function nonRtiMediaDayQuestionsByCategory(category: NonRtiMediaDayCategory): NonRtiMediaDayQuestion[] {
  return NON_RTI_MEDIA_DAY_QUESTIONS.filter((q) => q.category === category);
}
