import { estimateRecPlayerOverall } from "@rec/shared";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { env } from "../src/config/env.js";

type LegendRow = {
  id: string;
  name: string;
  position: string;
  est_ovr: number | null;
  attributes: Record<string, number> | null;
  abilities: Array<{ name?: string; description?: string; type?: string }> | null;
};

const apply = process.argv.includes("--apply");
const writeMigration = process.argv.includes("--write-migration");
const restUrl = `${env.SUPABASE_URL.replace(/\/$/, "")}/rest/v1`;
const headers = {
  apikey: env.SUPABASE_SERVICE_ROLE_KEY,
  Authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
  "Content-Type": "application/json",
};
const response = await fetch(`${restUrl}/rec_legend_catalog?select=id,name,position,est_ovr,attributes,abilities&order=name`, { headers });
if (!response.ok) throw new Error(`Legend catalog read failed: ${response.status} ${await response.text()}`);
const rows = (await response.json()) as LegendRow[];
const genericPositionMap: Record<string, string> = {
  DB: "CB", DL: "DT", LB: "MLB", OL: "LG",
  OT: "LT", OG: "LG", DE: "LE", OLB: "LOLB", RB: "HB",
};
const attributeCodeByName: Record<string, string> = {
  Speed: "spd", Acceleration: "acc", Agility: "agi", Strength: "str", Awareness: "awr",
  Carrying: "car", "BC Vision": "bcv", "Break Tackle": "btk", Trucking: "trk", "Stiff Arm": "sfa",
  "Change of Direction": "cod", "Spin Move": "spm", "Juke Move": "jkm", Catching: "cth",
  "Catch in Traffic": "cit", "Spectacular Catch": "spc", "Short Route Running": "srr",
  "Medium Route Running": "mrr", "Deep Route Running": "drr", Release: "rls", Jumping: "jmp",
  "Throwing Power": "thp", "Short Accuracy": "sac", "Medium Accuracy": "mac", "Deep Accuracy": "dac",
  "Throw on the Run": "run", "Throw Under Pressure": "tup", "Break Sack": "bsk", "Play Action": "pac",
  "Pass Blocking": "pbk", "Pass Block Power": "pbp", "Pass Block Finesse": "pbf", "Run Blocking": "rbk",
  "Run Block Power": "rbp", "Run Block Finesse": "rbf", "Lead Block": "lbk", "Impact Blocking": "ibl",
  "Play Recognition": "prc", Tackling: "tak", "Hit Power": "pow", "Block Shedding": "bsh",
  "Finesse Moves": "fmv", "Power Moves": "pmv", Pursuit: "pur", "Man Coverage": "mcv",
  "Zone Coverage": "zcv", Press: "prs", "Kick/Punt Return": "ret", "Kicking Power": "kpw",
  "Kicking Accuracy": "kac", Stamina: "sta", Toughness: "tou", Injury: "inj",
};
const toOvrAttributes = (attributes: Record<string, number>) => Object.fromEntries(
  Object.entries(attributes).flatMap(([name, value]) => attributeCodeByName[name] ? [[attributeCodeByName[name], value]] : []),
);
const missingAttributes = rows.filter((row) => !row.attributes || Object.keys(row.attributes).length === 0);
const missingAbilities = rows.filter((row) => !Array.isArray(row.abilities) || row.abilities.length === 0);
const invalidAbilityShapes = rows.filter((row) =>
  Array.isArray(row.abilities) && row.abilities.some((ability) =>
    !ability.name?.trim() || !ability.description?.trim() || !["xfactor", "superstar"].includes(ability.type ?? ""),
  ),
);

const mismatches = rows.flatMap((row) => {
  if (!row.attributes) return [];
  const calculated = estimateRecPlayerOverall(genericPositionMap[row.position] ?? row.position, toOvrAttributes(row.attributes)).displayOverall;
  return Number(row.est_ovr) === calculated ? [] : [{ ...row, calculated }];
});

if (apply) {
  for (const row of mismatches) {
    const result = await fetch(`${restUrl}/rec_legend_catalog?id=eq.${row.id}`, {
      method: "PATCH",
      headers,
      body: JSON.stringify({ est_ovr: row.calculated }),
    });
    if (!result.ok) throw new Error(`${row.name}: ${result.status} ${await result.text()}`);
  }
}

if (writeMigration) {
  const values = rows.map((row) => {
    if (!row.attributes) throw new Error(`${row.name} has no attributes.`);
    const calculated = estimateRecPlayerOverall(genericPositionMap[row.position] ?? row.position, toOvrAttributes(row.attributes)).displayOverall;
    return `  ('${row.id}'::uuid, ${calculated})`;
  });
  const sql = [
    "-- Generated by apps/api/scripts/audit-legend-catalog.ts from the current REC OVR model.",
    "-- Keeps every expanded-catalog row's stored OVR synchronized with its complete attributes.",
    "update public.rec_legend_catalog as catalog",
    "set est_ovr = calculated.est_ovr",
    "from (values",
    values.join(",\n"),
    ") as calculated(id, est_ovr)",
    "where catalog.id = calculated.id;",
    "",
  ].join("\n");
  writeFileSync(resolve(process.cwd(), "../../supabase/migrations/20260813190000_recalculate_expanded_legend_overalls.sql"), sql);
}

const summary = {
  total: rows.length,
  completeAttributes: rows.length - missingAttributes.length,
  completeAbilities: rows.length - missingAbilities.length,
  missingAttributes: missingAttributes.map((row) => row.name),
  missingAbilities: missingAbilities.map((row) => row.name),
  invalidAbilityShapes: invalidAbilityShapes.map((row) => row.name),
  overallMismatches: mismatches.map((row) => ({ name: row.name, stored: row.est_ovr, calculated: row.calculated })),
  updatedOveralls: apply ? mismatches.length : 0,
};

console.log(JSON.stringify(summary, null, 2));
if (missingAttributes.length || missingAbilities.length || invalidAbilityShapes.length || (!apply && mismatches.length)) {
  process.exitCode = 1;
}
