// One-off: uploads every clip in "apps/QB Throwing Motions/" to Cloudflare Stream and writes
// the resulting catalog (name + Stream uid + playback urls) to
// packages/shared/src/immortality/throwing-motions.ts. Run once; safe to re-run (creates new
// Stream videos each time, so don't re-run unless you also want to re-upload).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createStreamDirectUpload, streamPlaybackUrls, inspectStreamVideoRaw } from "../src/lib/cloudflare-stream.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const sourceDir = path.resolve(here, "../../QB Throwing Motions");
const outFile = path.resolve(here, "../../../packages/shared/src/immortality/throwing-motions.ts");

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

async function uploadOne(filePath: string, name: string): Promise<{ key: string; name: string; uid: string; hlsUrl: string; watchUrl: string }> {
  const { uid, uploadURL } = await createStreamDirectUpload({ maxDurationSeconds: 30, meta: { name: `throwing-motion:${name}` } });
  const bytes = readFileSync(filePath);
  const form = new FormData();
  form.set("file", new Blob([new Uint8Array(bytes)], { type: "video/mp4" }), path.basename(filePath));
  const uploadRes = await fetch(uploadURL, { method: "POST", body: form });
  if (!uploadRes.ok) throw new Error(`Upload failed for ${name}: HTTP ${uploadRes.status} ${await uploadRes.text().catch(() => "")}`);

  // Poll until Cloudflare finishes ingesting -- direct_upload returns immediately, the video
  // isn't playable until status.state === "ready".
  const deadline = Date.now() + 120_000;
  let ready = false;
  while (Date.now() < deadline) {
    const info = await inspectStreamVideoRaw(uid);
    if (info.state === "ready") { ready = true; break; }
    if (info.state === "error") throw new Error(`Stream ingest error for ${name}: ${info.errorReasonText ?? info.errorReasonCode ?? "unknown"}`);
    await new Promise((resolve) => setTimeout(resolve, 3000));
  }
  if (!ready) console.warn(`[WARN] ${name} (${uid}) did not report ready within 120s -- it may still finish processing shortly.`);

  const urls = streamPlaybackUrls(uid);
  return { key: slugify(name), name, uid, hlsUrl: urls.hls, watchUrl: urls.watch };
}

async function main() {
  const files = readdirSync(sourceDir).filter((f) => f.toLowerCase().endsWith(".mp4")).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  console.log(`Found ${files.length} clips in ${sourceDir}`);
  const results: Array<{ key: string; name: string; uid: string; hlsUrl: string; watchUrl: string }> = [];
  for (const [index, file] of files.entries()) {
    const name = file.replace(/\.mp4$/i, "").trim();
    console.log(`[${index + 1}/${files.length}] Uploading "${name}"...`);
    try {
      const result = await uploadOne(path.join(sourceDir, file), name);
      results.push(result);
      console.log(`  -> uid ${result.uid}`);
    } catch (err) {
      console.error(`  FAILED: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  const seenKeys = new Set<string>();
  for (const r of results) {
    let key = r.key;
    let n = 2;
    while (seenKeys.has(key)) { key = `${r.key}-${n}`; n += 1; }
    seenKeys.add(key);
    r.key = key;
  }

  const body = `// AUTO-GENERATED by apps/api/scripts/upload-throwing-motions.ts -- do not hand-edit the
// entries, regenerate instead. Each is a Cloudflare Stream video (see
// apps/api/src/lib/cloudflare-stream.ts); hlsUrl is the HLS manifest for a native <video> src
// (Safari) or an hls.js player (other browsers); watchUrl is Cloudflare's own hosted player page.
export type ThrowingMotion = { key: string; name: string; streamUid: string; hlsUrl: string; watchUrl: string };

export const THROWING_MOTIONS: ThrowingMotion[] = [
${results.map((r) => `  { key: ${JSON.stringify(r.key)}, name: ${JSON.stringify(r.name)}, streamUid: ${JSON.stringify(r.uid)}, hlsUrl: ${JSON.stringify(r.hlsUrl)}, watchUrl: ${JSON.stringify(r.watchUrl)} },`).join("\n")}
];
`;
  writeFileSync(outFile, body, "utf-8");
  console.log(`Wrote ${results.length} motions to ${outFile}`);
}

await main();
