-- Generated by scripts/dev/upload-new-storefront-headshots.mjs after Cloudflare Images upload.
with images(name, position, photo_url, source_url) as (values
('Leati Anoa''i','DT','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-leati-anoa-i-dt/public',''),
('Darin Erstad','P','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-darin-erstad-p/public',''),
('Joe Kane','QB','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-joe-kane-qb/public','https://en.wikipedia.org/wiki/Roger_Corman'),
('Vernon Littlefield','RE','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-vernon-littlefield-re/public',''),
('Will Shields','RG','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-will-shields-rg/public',''),
('John Stallworth','WR','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-john-stallworth-wr/public',''),
('Simeon Rice','RE','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-simeon-rice-re/public',''),
('Cal Hubbard','RT','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-cal-hubbard-rt/public','')
)
update public.rec_legend_catalog as catalog
set photo_url = images.photo_url
from images
where lower(catalog.name) = lower(images.name) and catalog.position = images.position;
