-- The original 78-legend seed (202607010005) undercounted by 5: pdftotext's
-- -table mode wrapped "Est. REC OVR" across extra whitespace on these 5 header
-- lines, which broke the parser's header regex and silently dropped them.
-- Confirmed against the PDF's own position-count summary table (QB10/HB10/FB6/
-- WR10/TE8/OL9/DB15/LB7/DL8 = 83; the extra +1 vs 78+5=83 was a rounding note in
-- the source, not a real 84th player) and verified against the raw extraction.
insert into public.rec_legend_catalog
  (name, position, position_group, est_ovr, height, weight, hand, jersey_number, dev_trait, archetype, build_note, attributes)
values
('Eric Dickerson', 'HB', 'offense', 87.7, '6''3"', 220, 'Right', 29, 'Superstar', 'Long-striding power speed', 'Rare size/speed with long-stride acceleration and power; less lateral than Barry/LT.', '{"Speed":94,"Acceleration":92,"Agility":87,"Strength":90,"Awareness":90,"Carrying":93,"BC Vision":96,"Break Tackle":93,"Trucking":92,"Stiff Arm":90,"Change of Direction":86,"Spin Move":82,"Juke Move":84,"Catching":70,"Catch in Traffic":65,"Spectacular Catch":58,"Short Route Running":68,"Medium Route Running":60,"Deep Route Running":50,"Release":62,"Jumping":75,"Throwing Power":40,"Short Accuracy":25,"Medium Accuracy":20,"Deep Accuracy":15,"Throw on the Run":20,"Throw Under Pressure":20,"Break Sack":80,"Play Action":30,"Pass Blocking":70,"Pass Block Power":66,"Pass Block Finesse":62,"Run Blocking":35,"Run Block Power":30,"Run Block Finesse":28,"Lead Block":45,"Impact Blocking":40,"Play Recognition":30,"Tackling":40,"Hit Power":38,"Block Shedding":30,"Finesse Moves":25,"Power Moves":25,"Pursuit":45,"Man Coverage":20,"Zone Coverage":25,"Press":15,"Kick/Punt Return":25,"Kicking Power":20,"Kicking Accuracy":15,"Stamina":96,"Toughness":94,"Injury":94,"Long Snap":40}'::jsonb),
('Terrell Owens', 'WR', 'offense', 88.3, '6''3"', 224, 'Right', 81, 'Superstar', 'Physical YAC WR', 'Elite size/speed/power/YAC; slight consistency offset through awareness/hands balance.', '{"Speed":92,"Acceleration":93,"Agility":89,"Strength":94,"Awareness":89,"Carrying":86,"BC Vision":82,"Break Tackle":90,"Trucking":86,"Stiff Arm":91,"Change of Direction":90,"Spin Move":82,"Juke Move":85,"Catching":94,"Catch in Traffic":95,"Spectacular Catch":95,"Short Route Running":92,"Medium Route Running":93,"Deep Route Running":94,"Release":95,"Jumping":96,"Throwing Power":45,"Short Accuracy":25,"Medium Accuracy":20,"Deep Accuracy":15,"Throw on the Run":20,"Throw Under Pressure":20,"Break Sack":74,"Play Action":30,"Pass Blocking":36,"Pass Block Power":32,"Pass Block Finesse":30,"Run Blocking":84,"Run Block Power":74,"Run Block Finesse":72,"Lead Block":42,"Impact Blocking":70,"Play Recognition":32,"Tackling":40,"Hit Power":40,"Block Shedding":28,"Finesse Moves":20,"Power Moves":20,"Pursuit":42,"Man Coverage":20,"Zone Coverage":25,"Press":15,"Kick/Punt Return":30,"Kicking Power":20,"Kicking Accuracy":15,"Stamina":96,"Toughness":97,"Injury":94,"Long Snap":40}'::jsonb),
('Ray Lewis', 'LB', 'defense', 88.2, '6''1"', 240, 'Right', 52, 'Superstar', 'Middle LB / enforcer', 'Elite diagnosis, tackling, leadership and hit power; not built like an edge rusher.', '{"Speed":87,"Acceleration":89,"Agility":86,"Strength":94,"Awareness":97,"Carrying":84,"BC Vision":80,"Break Tackle":84,"Trucking":86,"Stiff Arm":84,"Change of Direction":86,"Spin Move":75,"Juke Move":76,"Catching":78,"Catch in Traffic":76,"Spectacular Catch":78,"Short Route Running":55,"Medium Route Running":50,"Deep Route Running":45,"Release":50,"Jumping":90,"Throwing Power":50,"Short Accuracy":25,"Medium Accuracy":20,"Deep Accuracy":15,"Throw on the Run":20,"Throw Under Pressure":20,"Break Sack":78,"Play Action":25,"Pass Blocking":30,"Pass Block Power":28,"Pass Block Finesse":25,"Run Blocking":45,"Run Block Power":48,"Run Block Finesse":42,"Lead Block":40,"Impact Blocking":90,"Play Recognition":98,"Tackling":98,"Hit Power":99,"Block Shedding":95,"Finesse Moves":70,"Power Moves":82,"Pursuit":97,"Man Coverage":76,"Zone Coverage":82,"Press":70,"Kick/Punt Return":20,"Kicking Power":20,"Kicking Accuracy":15,"Stamina":97,"Toughness":99,"Injury":94,"Long Snap":40}'::jsonb),
('Deion Sanders', 'DB', 'defense', 88.5, '6''1"', 198, 'Right', 21, 'Superstar', 'Man corner / returner', 'All-time coverage speed and return threat; deliberately low tackling/hit power.', '{"Speed":99,"Acceleration":99,"Agility":98,"Strength":66,"Awareness":94,"Carrying":84,"BC Vision":82,"Break Tackle":78,"Trucking":70,"Stiff Arm":74,"Change of Direction":98,"Spin Move":80,"Juke Move":95,"Catching":87,"Catch in Traffic":78,"Spectacular Catch":82,"Short Route Running":60,"Medium Route Running":55,"Deep Route Running":50,"Release":55,"Jumping":96,"Throwing Power":50,"Short Accuracy":25,"Medium Accuracy":20,"Deep Accuracy":15,"Throw on the Run":20,"Throw Under Pressure":20,"Break Sack":70,"Play Action":25,"Pass Blocking":30,"Pass Block Power":28,"Pass Block Finesse":25,"Run Blocking":40,"Run Block Power":38,"Run Block Finesse":36,"Lead Block":35,"Impact Blocking":65,"Play Recognition":93,"Tackling":64,"Hit Power":55,"Block Shedding":65,"Finesse Moves":35,"Power Moves":40,"Pursuit":82,"Man Coverage":98,"Zone Coverage":94,"Press":88,"Kick/Punt Return":99,"Kicking Power":20,"Kicking Accuracy":15,"Stamina":95,"Toughness":88,"Injury":92,"Long Snap":40}'::jsonb),
('Brian Dawkins', 'DB', 'defense', 87.7, '6''0"', 210, 'Right', 20, 'Superstar', 'Strong safety / leader', 'Elite energy, hits, pursuit and zone instincts.', '{"Speed":91,"Acceleration":92,"Agility":91,"Strength":88,"Awareness":96,"Carrying":84,"BC Vision":82,"Break Tackle":78,"Trucking":70,"Stiff Arm":74,"Change of Direction":92,"Spin Move":80,"Juke Move":84,"Catching":86,"Catch in Traffic":86,"Spectacular Catch":88,"Short Route Running":60,"Medium Route Running":55,"Deep Route Running":50,"Release":55,"Jumping":92,"Throwing Power":50,"Short Accuracy":25,"Medium Accuracy":20,"Deep Accuracy":15,"Throw on the Run":20,"Throw Under Pressure":20,"Break Sack":70,"Play Action":25,"Pass Blocking":30,"Pass Block Power":28,"Pass Block Finesse":25,"Run Blocking":40,"Run Block Power":38,"Run Block Finesse":36,"Lead Block":35,"Impact Blocking":65,"Play Recognition":96,"Tackling":94,"Hit Power":97,"Block Shedding":78,"Finesse Moves":35,"Power Moves":40,"Pursuit":96,"Man Coverage":84,"Zone Coverage":93,"Press":80,"Kick/Punt Return":45,"Kicking Power":20,"Kicking Accuracy":15,"Stamina":96,"Toughness":98,"Injury":93,"Long Snap":40}'::jsonb)
on conflict (name, position) do update set
  position_group = excluded.position_group, est_ovr = excluded.est_ovr, height = excluded.height,
  weight = excluded.weight, hand = excluded.hand, jersey_number = excluded.jersey_number,
  dev_trait = excluded.dev_trait, archetype = excluded.archetype, build_note = excluded.build_note,
  attributes = excluded.attributes;
