-- Generated by scripts/dev/upload-new-storefront-headshots.mjs after Cloudflare Images upload.
with images(name, position, photo_url, source_url) as (values
('Luke Joeckel','LT','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-luke-joeckel-lt/public','https://www.espn.com/nfl/player/_/id/15796/luke-joeckel'),
('Adam Jones','CB','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-adam-jones-cb/public','https://www.espn.com/nfl/player/_/id/8421/adam-jones'),
('Danny Woodhead','HB','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-danny-woodhead-hb/public','https://www.espn.com/nfl/player/_/id/11788/danny-woodhead'),
('Brent Celek','TE','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-brent-celek-te/public','https://www.espn.com/nfl/player/_/id/10605/brent-celek')
)
update public.rec_legend_catalog as catalog
set photo_url = images.photo_url
from images
where lower(catalog.name) = lower(images.name) and catalog.position = images.position;
