-- Generated by scripts/dev/upload-new-storefront-headshots.mjs after Cloudflare Images upload.
with images(name, position, photo_url, source_url) as (values
('Boobie Miles','HB','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-boobie-miles-hb/public',''),
('Clifford Smith','SS','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-clifford-smith-ss/public','https://en.wikipedia.org/wiki/Method_Man'),
('Clifford Franklin','WR','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-clifford-franklin-wr/public','https://en.wikipedia.org/wiki/Orlando_Jones')
)
update public.rec_legend_catalog as catalog
set photo_url = images.photo_url
from images
where lower(catalog.name) = lower(images.name) and catalog.position = images.position;
