create table if not exists public.rec_team_standings_snapshots (
  id uuid primary key default gen_random_uuid(),
  league_id uuid not null references public.rec_leagues(id) on delete cascade,
  season_number integer not null,
  season_index integer,
  season_stage text not null default 'regular_season',
  week_number integer,
  team_id uuid not null references public.rec_teams(id) on delete cascade,
  madden_team_id text,
  team_name text,
  conference_id integer,
  conference_name text,
  division_id integer,
  division_name text,
  total_wins integer not null default 0,
  total_losses integer not null default 0,
  total_ties integer not null default 0,
  home_wins integer,
  home_losses integer,
  home_ties integer,
  away_wins integer,
  away_losses integer,
  away_ties integer,
  conference_wins integer,
  conference_losses integer,
  conference_ties integer,
  division_wins integer,
  division_losses integer,
  division_ties integer,
  win_pct numeric,
  win_loss_streak integer,
  standing_rank integer,
  previous_rank integer,
  playoff_seed integer,
  playoff_status integer,
  made_playoffs boolean not null default false,
  points_for integer,
  points_against integer,
  net_points integer,
  turnover_differential integer,
  team_ovr integer,
  cap_available bigint,
  cap_room bigint,
  cap_spent bigint,
  offensive_pass_yards integer,
  offensive_rush_yards integer,
  offensive_total_yards integer,
  defensive_pass_yards integer,
  defensive_rush_yards integer,
  defensive_total_yards integer,
  points_for_rank integer,
  points_against_rank integer,
  offensive_pass_yards_rank integer,
  offensive_rush_yards_rank integer,
  offensive_total_yards_rank integer,
  defensive_pass_yards_rank integer,
  defensive_rush_yards_rank integer,
  defensive_total_yards_rank integer,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (league_id, season_number, season_stage, team_id)
);

alter table public.rec_team_standings_snapshots enable row level security;

create index if not exists idx_rec_team_standings_snapshots_league_season
  on public.rec_team_standings_snapshots (league_id, season_number, season_stage);

create index if not exists idx_rec_team_standings_snapshots_team
  on public.rec_team_standings_snapshots (team_id, season_number);
