-- Generated by scripts/dev/upload-new-storefront-headshots.mjs after Cloudflare Images upload.
with images(name, position, photo_url, source_url) as (values
('Mark Gastineau','RE','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-mark-gastineau-re/public',''),
('Sid Luckman','QB','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-sid-luckman-qb/public',''),
('Darren Woodson','SS','https://imagedelivery.net/QAGFLBPDqDrzG1Yqj0cQIA/legend-darren-woodson-ss/public','')
)
update public.rec_legend_catalog as catalog
set photo_url = images.photo_url
from images
where lower(catalog.name) = lower(images.name) and catalog.position = images.position;
