import { useEffect, useState } from "react";
import { useReadyAuth } from "../../../lib/auth-context.js";
import { recApi } from "../../../lib/rec-api-client.js";
import type { PlayerStatSubmission } from "../../../types/api.js";
import { PageHeader } from "../../../components/ui/PageHeader.js";
import { Card } from "../../../components/ui/Card.js";
import { Button } from "../../../components/ui/Button.js";
import { Badge } from "../../../components/ui/Badge.js";
import { LoadingState } from "../../../components/ui/LoadingState.js";
import { ErrorState } from "../../../components/ui/ErrorState.js";

export function PlayerStatsReview(){const {guildId}=useReadyAuth();const [rows,setRows]=useState<PlayerStatSubmission[]|null>(null);const [edit,setEdit]=useState<PlayerStatSubmission|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const load=()=>recApi.listPlayerStatSubmissions(guildId).then(r=>setRows(r.submissions)).catch(e=>setError(e instanceof Error?e.message:"Failed to load player stats."));useEffect(()=>{void load()},[guildId]);
  async function status(row:PlayerStatSubmission,value:"approved"|"rejected"){setBusy(true);try{await recApi.updatePlayerStatSubmission({guildId,id:row.id,status:value});await load()}catch(e){setError(e instanceof Error?e.message:"Update failed.")}finally{setBusy(false)}}
  async function save(){if(!edit)return;setBusy(true);try{await recApi.updatePlayerStatSubmission({guildId,id:edit.id,playerName:edit.playerName,lines:edit.lines.map(l=>({category:l.category,stats:l.stats}))});setEdit(null);await load()}catch(e){setError(e instanceof Error?e.message:"Save failed.")}finally{setBusy(false)}}
  async function remove(row:PlayerStatSubmission){if(!confirm(`Remove ${row.playerName}'s submission?`))return;setBusy(true);try{await recApi.removePlayerStatSubmission(guildId,row.id);await load()}catch(e){setError(e instanceof Error?e.message:"Remove failed.")}finally{setBusy(false)}}
  return <div><PageHeader title="Player Stat Submissions" subtitle="Review, correct, approve, reject, or remove submitted player stat lines."/>{error&&<ErrorState message={error}/>} {!rows&&!error&&<LoadingState/>}<div className="stat-review-list">{rows?.map(row=><Card key={row.id}><div className="stat-review-head"><div><strong>{row.playerName}</strong><div className="form-hint">{row.teamName} · Season {row.seasonNumber} · {row.weekNumber==null?row.seasonStage:`Week ${row.weekNumber}`}</div></div><Badge status={row.status==="approved"?"approved":row.status==="rejected"?"denied":"pending"}>{row.status}</Badge></div><div className="stat-line-grid">{row.lines.map(line=><div key={line.id}><strong>{line.category.replaceAll("_"," ")}</strong><div>{Object.entries(line.stats).map(([k,v])=>`${k.replaceAll("_"," ")}: ${v}`).join(" · ")}</div></div>)}</div><div className="stat-review-actions"><Button variant="secondary" onClick={()=>setEdit(structuredClone(row))}>Edit</Button><Button variant="primary" disabled={busy} onClick={()=>status(row,"approved")}>Approve</Button><Button variant="secondary" disabled={busy} onClick={()=>status(row,"rejected")}>Reject</Button><Button variant="danger" disabled={busy} onClick={()=>remove(row)}>Remove</Button></div></Card>)}</div>{edit&&<div className="modal-backdrop"><Card className="stat-edit-modal"><h2>Edit Player Stats</h2><label className="form-field"><span className="form-label">Player name</span><input className="form-input" value={edit.playerName} onChange={e=>setEdit({...edit,playerName:e.target.value})}/></label>{edit.lines.map((line,index)=><fieldset key={line.id} className="stat-edit-fieldset"><legend>{line.category.replaceAll("_"," ")}</legend><div className="stat-edit-grid">{Object.entries(line.stats).map(([key,value])=><label className="form-field" key={key}><span className="form-label">{key.replaceAll("_"," ")}</span><input className="form-input" inputMode="numeric" type="number" min="0" value={value} onChange={e=>{const lines=[...edit.lines];lines[index]={...line,stats:{...line.stats,[key]:Number(e.target.value)}};setEdit({...edit,lines})}}/></label>)}</div></fieldset>)}<div className="stat-review-actions"><Button variant="primary" disabled={busy} onClick={save}>Save Changes</Button><Button variant="ghost" onClick={()=>setEdit(null)}>Cancel</Button></div></Card></div>}</div>}
